### ISSUE TITLE
[BUG]多个key一起删除已完成的时候，Message的提示还存在

### ISSUE THREAD

**Issue by JieAnthony** [tiny-craft/tiny-rdm#102]
**Tiny RDM Version**
Tiny RDM v1.1.2

**OS Version**
Mac

**Redis Version**
7.0.11

**Describe the bug**
多个key一起删除
![20231212-173359](https://github.com/tiny-craft/tiny-rdm/assets/38497992/24982c2d-4d16-4778-b033-40347ed605f5)

**Comment by tiny-craft** [comment]
大概删除了多少个key，中途有没有做别的操作，比如切换数据库什么的

**Comment by JieAnthony** [comment]
> 大概删除了多少个key，中途有没有做别的操作，比如切换数据库什么的

如图所示，就一起删除两个key，中途没有其他操作，等会我再试一下

**Comment by tiny-craft** [comment]
我试了几次没法重现, 包括删之前先把这个key移除掉, 不过反而发现多选删除之后有其他问题. 顺便加了个可关闭按钮在这消息提示上.

你后面还能试出来的话麻烦再说一声~

**Comment by JieAnthony** [comment]
> 我试了几次没法重现, 包括删之前先把这个key移除掉, 不过反而发现多选删除之后有其他问题. 顺便加了个可关闭按钮在这消息提示上.
> 
> 你后面还能试出来的话麻烦再说一声~

复现出来了

1. 添加KEY： **tiny_rdm_database_queues:test_test_test_test:notify**  类型为LIST value随意
2. 添加KEY： **tiny_rdm_database_queues:test_test_test_test**  类型为LIST value随意
3. 选中前缀是 **tiny_rdm_database_queues** 右侧删除

**Comment by JieAnthony** [comment]
@tiny-craft

**Comment by tiny-craft** [comment]
> 复现出来了
> 
> 1. 添加KEY： **tiny_rdm_database_queues:test_test_test_test:notify**  类型为LIST value随意
> 2. 添加KEY： **tiny_rdm_database_queues:test_test_test_test**  类型为LIST value随意
> 3. 选中前缀是 **tiny_rdm_database_queues** 右侧删除

我按这步骤试了下不会出现卡住的情况喔

**Comment by JieAnthony** [comment]
https://github.com/tiny-craft/tiny-rdm/assets/38497992/456fee46-0770-427e-9728-54d03c981b70


希望可以帮到你

**Comment by tiny-craft** [comment]
> 2023-12-15.11.35.57.mov 
> 希望可以帮到你

奇怪了，按你这个步骤做了好几次都没问题。还有其他前置步骤吗，比如连接设置填了“只显示指定数据库”，或者你这个视频前是从其他数据库切换过来之类的

**Comment by JieAnthony** [comment]
> > 2023-12-15.11.35.57.mov
> > 希望可以帮到你
> 
> 奇怪了，按你这个步骤做了好几次都没问题。还有其他前置步骤吗，比如连接设置填了“只显示指定数据库”，或者你这个视频前是从其他数据库切换过来之类的

@tiny-craft 就像视频中的那样，是刚打开应用的时候，没有任何前置步骤，数据库默认为第0个去操作的，中间没有过切换
