### ISSUE TITLE
[BUG]命令行执行LUA脚本报错

### ISSUE THREAD

**Issue by nilevols** [tiny-craft/tiny-rdm#103]
**Tiny RDM Version**
1.1.2

**OS Version**
Windows

**Redis Version**
Redis 5.0.14.1 (ec77f72d/0) 64 bit

**Describe the bug**
执行命令行 `EVAL "local a=redis.call('TIME');return a[1]*1000000+a[2]" 0` 会得到报错信息 `ERR value is not an integer or out of range`
![image](https://github.com/tiny-craft/tiny-rdm/assets/10579957/9fae1b79-3524-4003-bf0d-432fc1bb370f)

期待的结果：
![image](https://github.com/tiny-craft/tiny-rdm/assets/10579957/aa00a8ef-a23f-40db-820f-8a92f1212dd1)

Steps to Reproduce:

1. 连接Redis服务器，打开命令行Tab。
2. 输入`EVAL "local a=redis.call('TIME');return a[1]*1000000+a[2]" 0` 回车

**Comment by tiny-craft** [comment]
看起来是错误吧lua脚本的空格也切分成命令参数了

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)修复了这个问题
