### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'maxKeys')

### ISSUE THREAD

**Issue by Zgm1020** [tiny-craft/tiny-rdm#105]
**Tiny RDM Version**
1.1.2

**OS Version**
Windows11

**Redis Version**
华为云5.0.14

**Describe the bug**
第一次刷新库的时候
点击某个文件夹就报错这个

Steps to Reproduce:

1.
![image](https://github.com/tiny-craft/tiny-rdm/assets/55151533/cebbbbfb-d702-4d6d-908c-0bbb4d4e74a1)
2.

**Comment by tiny-craft** [comment]
是不是设定了只显示某个库？

**Comment by Zgm1020** [comment]
> 是不是设定了只显示某个库？

是的，选了2个库
![image](https://github.com/tiny-craft/tiny-rdm/assets/55151533/e430d950-eb5e-43b7-85a4-7986d9bebe3d)

**Comment by tiny-craft** [comment]
这个问题后面应该修复提交了, 下个版本可以留意下还有没问题

**Comment by Zgm1020** [comment]
好的，多谢

**Comment by Zgm1020** [comment]
> [最新版](https://github.com/tiny-craft/tiny-rdm/releases)修复了这个问题，可以再试下

已经好了
