### ISSUE TITLE
[FEATURE] Add JetBrains built-in fonts

### ISSUE THREAD

**Issue by UallenQbit** [tiny-craft/tiny-rdm#106]
Add JetBrains built-in fonts
JetBrains is better as default font
https://www.jetbrains.com/zh-cn/lp/mono/

**Comment by tiny-craft** [comment]
[最新版本](https://github.com/tiny-craft/tiny-rdm/releases)你可以手动输入没有列出来的字体了
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/0a146db5-af1c-4eff-95c1-92c22f25deb8)
