### ISSUE TITLE
MAC arm 版  文件损坏

### ISSUE THREAD

**Issue by Time-w** [tiny-craft/tiny-rdm#109]
我 MAC 是 M1 系统版本 14.2.1 (23C71) 
选择 mac_arm64 版本  安装后 文件损坏 
英特尔版本 没问题   
之前安装 1.0.8 也是损坏

**Comment by tiny-craft** [comment]
Duplicate of #63 

参考这里执行命令即可, 这个问题挺多人说的, 大家可能都没留意文档
