### ISSUE TITLE
[FEATURE] YAML formatter for values editor

### ISSUE THREAD

**Issue by sergey-v9** [tiny-craft/tiny-rdm#110]
as it uses Monaco editor, can it show YAML values formatted?

P.S.
huge kudos for such an incredible implementation of the familiar redis ui! you are the best

**Comment by tiny-craft** [comment]
[The latest version](https://github.com/tiny-craft/tiny-rdm/releases) already support display type YAML and XML, but auto detection still missing. It's difficult to detect by content, so for now I leave it for users to manually select.
