### ISSUE TITLE
[BUG] 窗口化或者全屏，预览撑出页面

### ISSUE THREAD

**Issue by ToTryEveryThing** [tiny-craft/tiny-rdm#112]
**Tiny RDM Version**

1.1.2

**Describe the bug**

![Snipaste_2024-01-06_22-26-36](https://github.com/tiny-craft/tiny-rdm/assets/79239899/5e62b674-75ba-45ea-b677-54b9ef646728)
![Snipaste_2024-01-06_22-26-20](https://github.com/tiny-craft/tiny-rdm/assets/79239899/8e85f479-0f3d-4e26-b98f-02fb405e601d)

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经限制了提示内容的最大宽高，超出部分会有滚动条
