### ISSUE TITLE
[BUG] 最新版本访问键报错

### ISSUE THREAD

**Issue by ChirsGod** [tiny-craft/tiny-rdm#114]
第一次进入以后显示如下：
![image](https://github.com/tiny-craft/tiny-rdm/assets/50586375/d5f8f866-b46a-405e-a960-d196ce2d221b)
点击访问某个键，出现该报错
![image](https://github.com/tiny-craft/tiny-rdm/assets/50586375/577a6a02-c287-48f7-8e94-ba48cbf79095)
报完错以后，键不显示了
![image](https://github.com/tiny-craft/tiny-rdm/assets/50586375/f908f33b-6f75-4d56-865e-bbaef7af709f)
重新点击刷新以后，又显示了该键值对
![image](https://github.com/tiny-craft/tiny-rdm/assets/50586375/4c7a5e71-aecc-4c7b-ac99-896c61b07f24)
重复点击会重复此现象。

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)修复了，可以再试试看

**Comment by tiny-craft** [comment]
这个问题先关闭了，还有问题在这里回复或者新开issue就行
