### ISSUE TITLE
[FEATURE] Allow choose system/user font rather than build-in fonts only

### ISSUE THREAD

**Issue by sky96111** [tiny-craft/tiny-rdm#115]

**Comment by tiny-craft** [comment]
In [the latest version](https://github.com/tiny-craft/tiny-rdm/releases), you can manually input font name which not show in the font selection list.

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/86b5ddb4-809a-46c9-a313-f5a344d6fee5)
