### ISSUE TITLE
[BUG]v1.1.4版本开启自动刷新，不设置秒数，快速刷新奔溃

### ISSUE THREAD

**Issue by hejojoiu** [tiny-craft/tiny-rdm#116]
**Tiny RDM Version**
v1.1.4

**OS Version**
Mac

**Redis Version**
v6.0.6

**Describe the bug**
选择一个key，第一次开启自动刷新，不设置秒速，刷新异常
第一次开启自动刷新，默认刷新秒数无，是否需要设置默认秒数和最低秒数
![image](https://github.com/tiny-craft/tiny-rdm/assets/46958050/2fe736f1-afce-4b23-ab58-f5d7361a5cac)
![image](https://github.com/tiny-craft/tiny-rdm/assets/46958050/6985c601-b426-4879-8676-352d661f1c84)

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经修复这个问题

**Comment by tiny-craft** [comment]
[1.1.6版本](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.6)已经修复这个问题
