### ISSUE TITLE
Windows 版本 Redis 连接使用报错

### ISSUE THREAD

**Issue by heyXiaoT** [tiny-craft/tiny-rdm#117]
**Tiny RDM Version**
V1.1.4

**OS Version**
Windows 11

**Redis Version**
V3.0.504 （微软维护的开源Windows版本的Redis，链接：https://github.com/microsoftarchive/redis）

**Describe the bug**
只能正确加载key，点击key的时候就会报错，具体如图
![image](https://github.com/tiny-craft/tiny-rdm/assets/30957584/278ce5eb-bf3e-4b5e-8650-a30f2b1edf84)

**Comment by tiny-craft** [comment]
Duplicate of #114

**Comment by tiny-craft** [comment]
这个问题已经提交代码，今晚应该会发布

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)修复了，可以再试试看
