### ISSUE TITLE
[BUG] 点击立即刷新按钮，错误提示优化建议

### ISSUE THREAD

**Issue by tmstack** [tiny-craft/tiny-rdm#119]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.5
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Mac
**Redis Version**
Which version of Redis are you using?
6.2.6
**Describe the bug**
点击立即刷新读取不到 Role 信息会报错，建议优化下
Steps to Reproduce:

1.点击立即刷新按钮，会弹出如下错误，用info 命令看了下，服务器确实没有返回role字段，建议增加个判断进行优化，内存情况闪了下就消失了  
<img width="699" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/56751502/ac40b059-1e72-4cc0-9bde-e8aec854529b">

2.不点立即刷新，内存情况是可以展示出来的 
<img width="680" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/56751502/677f71bb-37ed-4b79-b90a-5b6bb7e3a2ab">

**Comment by tiny-craft** [comment]
是不是你的redis服务器info命令有所限制，返回的信息不全。

1. 路径Replication/role没有值。（这里是有判断是否有值才显示，我看了下代码条件居然写错了，这里我要改下）
2. 看下路径Memory.used_memory是不是也没有值，还是值不是数字

**Comment by tmstack** [comment]
Memory.used_memory 这个值是有的
<img width="423" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/56751502/e3744591-1b62-4c45-aafa-a32083231128">
状态页默认进来是这个 
<img width="667" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/56751502/5cbf88cd-7233-4d78-ab67-db5f070f7f8e">

**Comment by tmstack** [comment]
1、这个值是有的 Memory.used_memory
![image](https://github.com/tiny-craft/tiny-rdm/assets/56751502/5822bdfc-9bfe-4064-b6e0-839997395cd9)

2、状态页默认进来是这个
![image](https://github.com/tiny-craft/tiny-rdm/assets/56751502/f0a42959-ef6b-4e66-b9ba-584db13d6f55)

**Comment by tiny-craft** [comment]
第二个问题不手动刷新前是能正常显示的？

**Comment by tmstack** [comment]
> 第二个问题不手动刷新前是能正常显示的？
是的

**Comment by tiny-craft** [comment]
> > 第二个问题不手动刷新前是能正常显示的？
> > 是的，不知道是不是你这里设置的默认值

手动刷新前，有时显示不出来，我这能重现。手动刷新后貌似重现不了。
你手动刷新后，一直刷都显示不了吗？

**Comment by tmstack** [comment]
> > > 第二个问题不手动刷新前是能正常显示的？
> > > 是的，不知道是不是你这里设置的默认值
> 
> 手动刷新前，有时显示不出来，我这能重现。手动刷新后貌似重现不了。 你手动刷新后，一直刷都显示不了吗？

是的，一直显示不了，具体情况是，显示一下就消失了，然后弹出下边的错误弹框。
<img width="679" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/56751502/b1ddf9f4-2b80-45b3-a017-c359c38c108e">

**Comment by tiny-craft** [comment]
[1.1.6版本](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.6)可以看下还没有没有这个问题 @tmstack

**Comment by tmstack** [comment]
> [1.1.6版本](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.6)可以看下还没有没有这个问题 @tmstack

试了下都正常了
