### ISSUE TITLE
[BUG]终端删除字段，光标会立即返回到最右边

### ISSUE THREAD

**Issue by hzdzyx** [tiny-craft/tiny-rdm#120]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.5
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows
**Redis Version**
Which version of Redis are you using?
7.2.4
**Describe the bug**
终端删除字段，光标会立即返回到最右边
Steps to Reproduce:

1.
![image](https://github.com/tiny-craft/tiny-rdm/assets/112613967/ac64cbfa-1f33-4dac-8b17-3ca6d79036e7)

2.如图，比如我要删除r，光标立即跳转到最右端

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)修复了，可以再试试看
