### ISSUE TITLE
[FEATURE] 有效期更友好显示

### ISSUE THREAD

**Issue by 853103174** [tiny-craft/tiny-rdm#122]
有效期能不能转换成还剩几年几月几日这种 根据有效期合理转换

**Comment by tiny-craft** [comment]
可以考虑后面给通用设置加个格式显示选择。当初把年月日都显示出来，太占用位置了，挤压了同一行其他组件，所以搁置了

**Comment by tiny-craft** [comment]
超过一天的时间，会增加天为单位的显示
<img width="201" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/c0cf56ef-a08d-4295-a6f2-1eaefb65e7ac">

**Comment by tiny-craft** [comment]
[1.1.6版本](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.6)已经加上天数显示。这个问题先关了哈
