### ISSUE TITLE
[FEATURE]期望批量删除的时候速度快点

### ISSUE THREAD

**Issue by Zgm1020** [tiny-craft/tiny-rdm#123]
需要清理批量的键的时候速度太慢，需要等好久

**Comment by tiny-craft** [comment]
大概清理多少个key？

**Comment by Zgm1020** [comment]
> 大概清理多少个key？

几百个、一两千个、还有上万的都有过，key少的可以，多了之后用这个工具清理的比较慢，不知道是不是删除的时候做限制了，但是用RedisDesktopManager工具清理就比较快

**Comment by tiny-craft** [comment]
是自己多选删除的，还是通过批量删除对话框用正则匹配来删的？
猜测因为加了实时状态，所以有时UI通知阻塞了就会慢一点，这个当时优化了不少时间。后续再加多一个不显示实时状态的勾选看看能不能提速

**Comment by Zgm1020** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/55151533/86339c0c-7d53-44e4-b1f5-259da78bf89b)
批量删除的

**Comment by Zgm1020** [comment]
> 你现在删除1万key大概要多久？

没删除完过，等得有点久，就没用了，能看到一次删除几百个key吧

**Comment by tiny-craft** [comment]
我这测试5万是2秒，我加个静默删除的选项看看，应该UI更新堵塞了

**Comment by Zgm1020** [comment]
> 我这测试5万是2秒，我加个静默删除的选项看看，应该UI更新堵塞了

好的

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)优化了删除速度，可以体验下。期待体验完回来反馈

**Comment by Zgm1020** [comment]
这次删除挺快的，完美
