### ISSUE TITLE
[BUG] 偏好设置 - 编辑器 - 字体和字体尺寸修改不起作用

### ISSUE THREAD

**Issue by kt286** [tiny-craft/tiny-rdm#125]
**Tiny RDM Version**
1.1.6

**OS Version**
Windows

**Redis Version**
7.0

**Describe the bug**
偏好设置 - 编辑器 - 字体和字体尺寸修改不起作用

**Comment by tiny-craft** [comment]
已经提交修复代码了，下个版本一起更上去。
错把app的字体和尺寸用到编辑器上了，现在要用的话，先修改常规配置里面的字体设置。
