### ISSUE TITLE
[FEATURE] 命令行支持 快捷键 emacs bash的快捷键

### ISSUE THREAD

**Issue by fanlushuai** [tiny-craft/tiny-rdm#126]

**Comment by tiny-craft** [comment]
整套快捷键有点多，而且很多对redis cli来说是用不到的，我会先把部分光标和文本操作的加上

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经支持部分快捷键Ctrl+A/E/F/B/D/H/U/K/W/P/N/L，还有哪些确实高频使用的还没添加的，可以再反馈~
