### ISSUE TITLE
[FEATURE]从Redis链接导入

### ISSUE THREAD

**Issue by Ecalose** [tiny-craft/tiny-rdm#127]
请问是否考虑添加从Redis链接导入配置的功能呢，形如redis://name:pwd@host:port

**Comment by tiny-craft** [comment]
确实有，只是没人提我以为没人用

**Comment by Ecalose** [comment]
> 确实有，只是没人提我以为没人用

hhh，我之前都是手动输的

**Comment by Ecalose** [comment]
在使用时，发现不带ssl的正常，带ssl的貌似不能自动启用ssl，需要手动启用，形如rediss://，或许是目前没有识别这块？

**Comment by tiny-craft** [comment]
可以识别，看来你是重度url用户，来说说你还有什么这方面的需求。比如还有哪些参数没识别出来

**Comment by Ecalose** [comment]
> 可以识别，看来你是重度url用户，来说说你还有什么这方面的需求。比如还有哪些参数没识别出来

hhh，我目前测试到只有ssl无法识别导入
