### ISSUE TITLE
链接不上，unknow command config

### ISSUE THREAD

**Issue by MoeMoeFish** [tiny-craft/tiny-rdm#13]
一般生产环境好像都会禁用 config 命令，应该支持这种没有 config 命令的环境。

**Comment by tiny-craft** [comment]
有影响其他功能使用吗

**Comment by MoeMoeFish** [comment]
就是根本用不了，链接的时候就报这个错了，我用了以下别的 redis 工具，同样的 redis server，没有这个问题

**Comment by tiny-craft** [comment]
@MoeMoeFish 试下最新版能不能进，config命令执行失败，现在会默认当成16个数据库

**Comment by tiny-craft** [comment]
请尝试下最新版，如还有问题再重新提issue咯
