### ISSUE TITLE
[BUG] 设置中无法获取全部字体列表

### ISSUE THREAD

**Issue by kt286** [tiny-craft/tiny-rdm#130]
**Tiny RDM Version**
1.1.6

**OS Version**
Linux

**Redis Version**
7.0

**Describe the bug**
设置中无法获取全部字体列表
猜测是只读取了系统目录里的字体，自己安装的字体读取不到

**Comment by kt286** [comment]
粗略看了下 sysfonts 的代码，貌似维护了一套字体列表  名字对不上就不显示
https://github.com/adrg/sysfont/blob/master/fonts.go

**Comment by tiny-craft** [comment]
看来是要支持手动输入字体名了
