### ISSUE TITLE
[BUG]点击设置报错

### ISSUE THREAD

**Issue by iszhangsc** [tiny-craft/tiny-rdm#136]
**Tiny RDM Version**
1.1.8

**OS Version**
Mac
**Redis Version**
5.0.4

**Describe the bug**
点击软件左下角齿轮按钮，则出现了如图所示
<img width="392" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/41824454/c8ceec11-a4c7-4fbf-8cc6-948f67eb659c">

**Comment by tiny-craft** [comment]
mac系统版本是多少？

**Comment by iszhangsc** [comment]
Mac OS 14.0  M1
关闭后多次打不开，尝试多次打开后，软件就可以点击设置了。

**Comment by tiny-craft** [comment]
> Mac OS 14.0 M1 关闭后多次打不开，尝试多次打开后，软件就可以点击设置了。

就是第一次能打开这个对话框，关闭后就打不开了，连点几次才可以？

**Comment by iszhangsc** [comment]
> > Mac OS 14.0 M1 关闭后多次打不开，尝试多次打开后，软件就可以点击设置了。
> 
> 就是第一次能打开这个对话框，关闭后就打不开了，连点几次才可以？
这里应该是关闭软件后多次打不开软件，尝试多次打开软件后，软件就可以点击设置了

**Comment by tiny-craft** [comment]
@iszhangsc 有空给我录个能重现的视频，我这没法重现...

**Comment by iszhangsc** [comment]
我复现不出来了。
