### ISSUE TITLE
[BUG] Not loading

### ISSUE THREAD

**Issue by Poil** [tiny-craft/tiny-rdm#138]
**Tiny RDM Version**
ii  tinyrdm        1.1.8        amd64        Tiny Redis Desktop Manager

**OS Version**
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
XFCE 4.16.0

**Redis Version**
N/A

**Describe the bug**
When I start the app it stays stuck grey screen with little red in the middle, sometimes I saw "new connection" button but generally it stucks before that

**Comment by tiny-craft** [comment]
Have you tried previous version? [1.1.6](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.6) or below.

**Comment by tiny-craft** [comment]
Too long no reply, if this issue is not resolved, welcome back to reopen.
