### ISSUE TITLE
[BUG]Incorrect "redis_mode" display when use sentinel

### ISSUE THREAD

**Issue by lians0** [tiny-craft/tiny-rdm#139]
**Tiny RDM Version**
V1.1.8

**OS Version**
Windows

**Redis Version**
4.0.9

**Describe the bug**
在服务上使用redis-cli连接哨兵显示的redis_mode是sentinel
![image](https://github.com/tiny-craft/tiny-rdm/assets/30581350/db635f8a-873f-4075-85ad-9a9802803334)

但是在rdm中是standalone
![image](https://github.com/tiny-craft/tiny-rdm/assets/30581350/a5f671bd-9839-4ec9-81db-4c5b7889cc08)

**Comment by tiny-craft** [comment]
哨兵模式勾选了吗

**Comment by lians0** [comment]
已经勾选了

**Comment by lians0** [comment]
> 哨兵模式勾选了吗
> ![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/2501663c-6619-4f33-9169-c56685308d16)
> 

已经勾选了

**Comment by tiny-craft** [comment]
这里我查了下，哨兵模式的方式连接，是先连到哨兵节点，然后通过哨兵节点提供的节点信息选择节点，再连到对应节点去。这里展示的是最后一步里所连的节点了，所以是没有显示错的。
