### ISSUE TITLE
[FEATURE]  查询条件不支持修改，输入错误只能重新输入

### ISSUE THREAD

**Issue by Muscleape** [tiny-craft/tiny-rdm#141]
搜索key时，输入错误，没有搜到到对应的key，想修改刚才输入的key发现不能修改，只能删掉重新输入。希望可以直接修改刚才输入的key

<img width="445" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/16682039/83342fbc-4300-4baa-b87e-20799567092f">

**Comment by tiny-craft** [comment]
不要按回车，就是筛选
按了回车是已经进入查询匹配了，这时如果要修改，直接输入新的按回车即可替换

**Comment by Muscleape** [comment]
棒   👍
