### ISSUE TITLE
[FEATURE] 支持域套接字的连接方式

### ISSUE THREAD

**Issue by qqisee** [tiny-craft/tiny-rdm#142]
就是和redis-cli -s 命令一样的连接方式
Usage: redis-cli [OPTIONS] [cmd [arg [arg ...]]]
  -s <socket>        Server socket (overrides hostname and port).

**Comment by tiny-craft** [comment]
就是url为unix://开头的连接吗

**Comment by qqisee** [comment]
是的，https://github.com/redis/go-redis/issues/3 库也是支持的

**Comment by tiny-craft** [comment]
[1.1.9](https://github.com/tiny-craft/tiny-rdm/releases)已经支持
