### ISSUE TITLE
[BUG] 点击链接无法跳转

### ISSUE THREAD

**Issue by iszhangsc** [tiny-craft/tiny-rdm#143]
**Tiny RDM Version**
1.1.8

**OS Version**
MacOS 14 M1
**Redis Version**
5.0.3
点击无法跳转链接，如果不支持跳转，建议关闭吧
<img width="731" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/41824454/3728f47c-f9ee-4ffd-bc09-4d44bf08560b">

**Comment by tiny-craft** [comment]
[1.1.9](https://github.com/tiny-craft/tiny-rdm/releases)已经修复客户端中链接无法跳转的问题，并且偏好设置可以关闭链接跳转
