### ISSUE TITLE
get server info fail:context canceled?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [tiny-craft/tiny-rdm#145]
**Tiny RDM Version**
最新的1.1.8

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
windows

**Redis Version**
v5.0.5

**Describe the bug**
这是因为key太多了嘛？

![image](https://github.com/tiny-craft/tiny-rdm/assets/16663435/0a197b12-e02b-4e99-9788-4b72ecfbf7cd)
右侧的面板也出不来信息
![image](https://github.com/tiny-craft/tiny-rdm/assets/16663435/fc617571-fc50-40b5-bc84-ca3292d8a532)

项目是个挺好的项目，希望可以持续的更新。

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment]
看起来是连接太久导致超时之类的，是软件启动第一次连接就这样，还是经过了其他操作后这样。
比如重复多次断开连接-打开连接之类的操作后

**Comment by pigLoveRabbit520** [comment]
打开就这样了

**Comment by pigLoveRabbit520** [comment]
我改了，但还是转圈。。
![image](https://github.com/tiny-craft/tiny-rdm/assets/16663435/04fd5734-e76c-4df0-8d9c-4520fa883909)

**Comment by tiny-craft** [comment]
改成10也会这样吗。还有右上角的自动刷新也先停止
<img width="271" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/bc697262-76ef-4fae-afe2-bbe33a7df510">
