### ISSUE TITLE
查看 zset 数据闪退

### ISSUE THREAD

**Issue by heathcliff-hu** [tiny-craft/tiny-rdm#148]
**Tiny RDM Version**
v1.1.8

**OS Version**
Mac 14.3

**Redis Version**
3.2.9

**Describe the bug**
点击 zset 类型的值闪退。

报错日志如下

```
FAT | json: unsupported value: -Inf
```

**复现步骤**

1. `redis-cli zadd test 333 aa`，点击 test 查看，未闪退
2. `redis-cli zadd test -INF bb`, 点击 test 查看，闪退

**Comment by tiny-craft** [comment]
[1.1.9](https://github.com/tiny-craft/tiny-rdm/releases)增加了Inf支持，可以使用看看
