### ISSUE TITLE
[FEATURE] 希望搜索框的小标签可以实现双击修改功能

### ISSUE THREAD

**Issue by ManyHoo** [tiny-craft/tiny-rdm#149]
目前的搜索是，一旦回车确认后就已经固定了，无法修改搜索关键词，只能在后面追加。

举个使用场景：搜索后发现没有想要的结果，想更改部分关键词再次搜索比较麻烦。

**希望能改成传统的搜索框或者增加双击标签修改标签内容选项**，这对于搜索比较长的key真的很有帮助，非常感谢！

![image](https://github.com/tiny-craft/tiny-rdm/assets/30287072/05b507d0-738f-4a19-b98a-09a197205e7d)

**Comment by tiny-craft** [comment]
[1.1.9](https://github.com/tiny-craft/tiny-rdm/releases)已经支持双击标签快速修改
