### ISSUE TITLE
win11打不开，报病毒

### ISSUE THREAD

**Issue by wangran99** [tiny-craft/tiny-rdm#15]
win11报错，移动版和安装版都无法打开。win11报病毒

**Comment by imic07** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/16321067/6f6639ff-dddc-4d6e-8c0b-4896b6ee20c9)

**Comment by tiny-craft** [comment]
好像360这些没有证书签名都直接报毒，后续我再看看弄个正规的签名。如果不放心可以先自行拉取代码编译生成。
