### ISSUE TITLE
请问我应该如何连接redis-cluster集群呢？

### ISSUE THREAD

**Issue by zigaai** [tiny-craft/tiny-rdm#150]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.8

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
windows 10

**Redis Version**
Which version of Redis are you using?
7.0.11

**Describe the bug**
使用redis-cli命令可以连接集群
tiny-rdm客户端连接总是报400, 是我哪里配置有问题吗？
![image](https://github.com/tiny-craft/tiny-rdm/assets/50167241/70a6b5b9-f79d-43ad-a5d3-41532a6c113b)
![image](https://github.com/tiny-craft/tiny-rdm/assets/50167241/fb96e000-959f-46b5-beee-88f2096a4464)

redis-cli连接正常
![image](https://github.com/tiny-craft/tiny-rdm/assets/50167241/6fc3c3da-eba8-4601-b0fa-ba930b5c9429)

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment]
你本地能通过命令访问吗，我看你第二张图应该是通过远程SSH后再使用命令行连的

**Comment by zigaai** [comment]
> 你本地能通过命令访问吗，我看你第二张图应该是通过远程SSH后再使用命令行连的

本地是通过另一台虚拟机命令行连过去的，理论上应该都是通的
redis-cli连接虚拟机地址是192.168.100.100
server地址是192.168.100.101

**Comment by tiny-craft** [comment]
那不一定是通的，你确认下对外暴露的端口和你填的对不对对不对，本机能不能ping通它，或者本机运行的代码能不能连上。确认都没错还不行的话，你把docker-compose文件发上来我试下。
之前有个配置哨兵模式也是弄错了，所以一直连不上的，看下能不能参考下 #82

**Comment by zigaai** [comment]
确实本机客户端是连不上，我大概了解了，谢谢你的回答
