### ISSUE TITLE
官网链接失效

### ISSUE THREAD

**Issue by CGITJ** [tiny-craft/tiny-rdm#157]
**OS Version**
Windows

**Describe the bug**
官网链接失效
![1](https://github.com/tiny-craft/tiny-rdm/assets/101928057/bd135f8c-26fb-4f87-b808-be9084e37b97)

**Comment by tiny-craft** [comment]
这个不是失效，是还没时间完善其他页面哈😆

**Comment by tiny-craft** [comment]
最近都在给官网填内容，欢迎围观和发表意见。
这个issue就先关闭了，有什么内容关于Tiny RDM或者是Redis的，都还可以在这里说。
