### ISSUE TITLE
[FEATURE] 列表页 tip 和内容页 Unicode 转中文

### ISSUE THREAD

**Issue by duanluan** [tiny-craft/tiny-rdm#158]
比如 Another Redis Desktop Manager 列表页是这样的
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/72b2bb0e-b13e-46cf-afc6-0956e4845cb3)
点开后是这样的
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/9685d817-ea29-4843-a5a8-cde11abebdfd)
但是在 Tiny RDM 点开内容是这样
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/78d113fb-8259-4683-ae1d-ce10b8b7ded1)
底下的解码/解压方式切换了遍也没用，希望能 Unicode 转中文

**Comment by tiny-craft** [comment]
这么巧，这个问题我早上路上走的时候刚好在想这个功能，是不是真的要做。因为go的json是不自动转的，这样的话，我可能需要全局自己再转一遍，大的json文本可能就有性能问题了。容我再想想~

**Comment by duanluan** [comment]
> 这么巧，这个问题我早上路上走的时候刚好在想这个功能，是不是真的要做。因为 go 的 json.Indent 是不自动转的，这样的话，我可能需要全局自己再转一遍，大的 json 文本可能就有性能问题了。容我再想想～

一开始下的时候就发现这个问题了，现在还比较少用 Tiny RDM 也是这个原因。
一般不会在一个 key 里存特别大的内容吧，可以一样列表原样显示，详情给个选项再转。

**Comment by duanluan** [comment]
1.1.9 用 Unicode JSON 缩进有问题，而且切换的时候字段顺序有明显变化，比较突兀。
<img src="https://github.com/tiny-craft/tiny-rdm/assets/14957667/0fa9608e-691a-48c8-92d2-1971cc81e9fe" width=400/>
<img src="https://github.com/tiny-craft/tiny-rdm/assets/14957667/2654799c-2378-43db-8e26-750a60d68d28" width=400/>

**Comment by tiny-craft** [comment]
这就是我不想用这个方式的原因，转为map再转回json字符串，字段会无序的。先用着吧，后面我看看有没有更好的解决办法

**Comment by duanluan** [comment]
能记住查看方式吗？一个 List 当中有几条数据，每编辑一条都要手动切换一次。
要是能同时设置 tip 的查看方式就好了。

**Comment by tiny-craft** [comment]
[v1.1.10](https://github.com/tiny-craft/tiny-rdm/releases)版本已经可以保存`Unicode JSON`的字段顺序，并且会保存最后手动选择的查看方式，欢迎使用

**Comment by duanluan** [comment]
没有记住查看方式，完全卸载（包括Roaming\TinyRDM）后仍然可复现。
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/29efc18e-4082-434a-bbde-0ea6dc44edb9)
![20240323-174334](https://github.com/tiny-craft/tiny-rdm/assets/14957667/2e48f158-d651-4809-ad72-4ac92d60f968)

**Comment by tiny-craft** [comment]
String类型的也不行？
