### ISSUE TITLE
[BUG]慢日志列表滚动显示不全

### ISSUE THREAD

**Issue by amsterdan5** [tiny-craft/tiny-rdm#161]
**Tiny RDM Version**
v1.1.8

**OS Version**
mac m1

**Redis Version**
6.2.7

**Describe the bug**
慢日志滚动到底部内容显示不全，前面的数据没了
![1708564904521](https://github.com/tiny-craft/tiny-rdm/assets/13082949/9efe8442-2bf0-4fe6-95da-bc2983126893)

**Comment by tiny-craft** [comment]
应该是有一条日志内容太长占用高度太多了，导致这个table的虚拟表格有问题。这个我看看怎么解决

**Comment by amsterdan5** [comment]
好的，有计划加入热词统计，键值分析优化等功能吗

**Comment by tiny-craft** [comment]
> 好的，有计划加入热词统计，键值分析优化等功能吗

短期内还没有，最近应该会以修补和补全使用文档为主

**Comment by tiny-craft** [comment]
新版本慢日志列表暂时移除虚拟滚动了，这样就不会一行里面内容太长而导致显示空白了
