### ISSUE TITLE
[BUG]1.1.9 win x64安装包没有安装，会直接运行TinyRDM

### ISSUE THREAD

**Issue by MerFrederick** [tiny-craft/tiny-rdm#163]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.9
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows 10
**Redis Version**
Which version of Redis are you using?
6.2.4
**Describe the bug**

Steps to Reproduce:

1.双击TinyRDM_Setup_1.1.9_windows_x64.exe
2.TinyRDM会直接启动

**Comment by nadirvishun** [comment]
测试同样情况

**Comment by tiny-craft** [comment]
[Tiny RDM.exe.zip](https://github.com/tiny-craft/tiny-rdm/files/14382554/Tiny.RDM.exe.zip)
帮忙试下这个是不是安装包，我现在没有Windows电脑，不知道是不是wails新版打包有问题😂

**Comment by MerFrederick** [comment]
> [Tiny RDM.exe.zip](https://github.com/tiny-craft/tiny-rdm/files/14382554/Tiny.RDM.exe.zip) 帮忙试下这个是不是安装包，我现在没有Windows电脑，不知道是不是wails新版打包有问题😂

这个依旧有相同问题，1.1.8是正常的。

**Comment by tiny-craft** [comment]
那应该是wails 2.8的打包参数`nsis`不起作用了，我手头有Windows电脑时再试下传个安装包。
现在用可以将绿色版的先直接覆盖已安装目录下的exe

**Comment by tiny-craft** [comment]
@MerFrederick @nadirvishun Windows安装包重新传了

**Comment by MerFrederick** [comment]
> @MerFrederick @nadirvishun Windows安装包重新传了

可以安装，但是版本号不对，是v0.0.0，会提示升级。

**Comment by tiny-craft** [comment]
这个手动打包的，github action我晚点修改下再重新打下，找到action问题了😭

**Comment by nadirvishun** [comment]
刚下载测试正常了
