### ISSUE TITLE
[FEATURE] 能否设置默认为 JSON 格式预览, 或者某种类型默认 JSON 格式预览

### ISSUE THREAD

**Issue by AYiXi** [tiny-craft/tiny-rdm#167]
<img width="449" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/28703786/ef2538c8-5995-4fd8-a5b6-127ad9d9773b">

**Comment by tiny-craft** [comment]
下一个版本应该会加记录，再次打开这个key使用最后一次手动切换的格式

**Comment by AYiXi** [comment]
> 下一个版本应该会加记录，再次打开这个key使用最后一次手动切换的格式

合理
