### ISSUE TITLE
阴影

### ISSUE THREAD

**Issue by 2536629322** [tiny-craft/tiny-rdm#17]
浅色模式可以不可以给边框加一个阴影

**Comment by tiny-craft** [comment]
给应用加了外边框 e584d7f，先看看Windows下使用会不会还是很奇怪，加阴影的话Windows10以下圆角显示有点问题。等我想下有没有更好的方案

**Comment by 2536629322** [comment]
好的👍

**Comment by akschy** [comment]
> 给应用加了外边框 [e584d7f](https://github.com/tiny-craft/tiny-rdm/commit/e584d7f0780886b36e48397ab262c0735634578a)，先看看Windows下使用会不会还是很奇怪，加阴影的话Windows10以下圆角显示有点问题。等我想下有没有更好的方案

现在来看没有阴影win11还是不太能分得清层级。其实不用执着于显示圆角，win10 本身的风格就是直角，可以跟随系统显示窗口，在win10是直角，win 11 是圆角，更能融合系统风格

**Comment by tiny-craft** [comment]
最新版已经把Windows下系统窗口阴影加回来了，欢迎使用

**Comment by 2536629322** [comment]
> 最新版已经把Windows下系统窗口阴影加回来了，欢迎使用

一直在用，感谢大佬的辛苦付出😊
