### ISSUE TITLE
[BUG] 貌似试了一下MacOS 10.15.7

### ISSUE THREAD

**Issue by ailunbolinkenasi** [tiny-craft/tiny-rdm#170]
貌似打开白屏
<img width="1024" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/90432556/0f0f201f-8b20-4257-9a8d-e57ff985ca43">

**Comment by tiny-craft** [comment]
是的，`Monaco Editor`对10.15以下的WKWebview兼容性有问题，并且除了这个，其他界面和组件的兼容性也或多或少有问题，所以暂时没精力兼容了...
