### ISSUE TITLE
[BUG]value序列号化不能正常显示

### ISSUE THREAD

**Issue by anonymous2100** [tiny-craft/tiny-rdm#172]
**Tiny RDM Version**
1.1.9

**OS Version**
windows

**Redis Version**
3.2.12

**Describe the bug**
string类型的kay-value，value被序列化之后，查看时不能正常显示

![1](https://github.com/tiny-craft/tiny-rdm/assets/63840237/e4f7d11e-9dab-4242-bada-2ca71a176586)
![2](https://github.com/tiny-craft/tiny-rdm/assets/63840237/2a4a9d53-fa14-485f-a831-cba9ce1d4839)

**Comment by tiny-craft** [comment]
这个是转16进制的方式不同，`RESP`是忽略转换英文这些，`redis insight`这些就直接全文转成16进制，`Tiny RDM`转16进制方式是后者。你这个情况应该用`Raw`的方式查看是可以看到后面序列号的
