### ISSUE TITLE
[BUG]Windows版本的注册表中的版本号不对

### ISSUE THREAD

**Issue by MerFrederick** [tiny-craft/tiny-rdm#174]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.9
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows
**Redis Version**
Which version of Redis are you using?

**Describe the bug**
控制面板中显示的版本号为1.0.0，原因是注册表HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Tiny CraftTiny RDM下DisplayVersion为1.0.0
Steps to Reproduce:

1.打开控制面板\程序\程序和功能
2.搜索Tiny RDM，版本号显示为1.0.0

**Comment by tiny-craft** [comment]
只有`1.1.9`这样吗，之前的版本有没有留意会不会这样

**Comment by MerFrederick** [comment]
> 只有`1.1.9`这样吗，之前的版本有没有留意会不会这样

刚测试了下1.1.8，没有此问题。

**Comment by tiny-craft** [comment]
好的，谢谢反馈，这个版本Windows的安装包因为github action有问题，所以是我本地打的。github action已经修复过了，下个版本重新让它打就不会有这个问题了

**Comment by weilence** [comment]
右键查看属性版本也不对，不知道跟这个有没有关系？
![image](https://github.com/tiny-craft/tiny-rdm/assets/11787429/2fad97be-cc86-4ad3-ada3-645a055663bf)

**Comment by tiny-craft** [comment]
[v1.1.10](https://github.com/tiny-craft/tiny-rdm/releases)已经修复这个问题
