### ISSUE TITLE
[BUG] 量大一点加载直接卡死

### ISSUE THREAD

**Issue by AYiXi** [tiny-craft/tiny-rdm#175]
https://github.com/tiny-craft/tiny-rdm/assets/28703786/e63aac23-d00f-4826-8503-b572bc7223ec

**Comment by tiny-craft** [comment]
电脑硬件配置大概是什么？
视频中是多少条数据？
我这大量数据可能快速滚动会卡，不过还没遇到卡死的情况

**Comment by zhifeifu** [comment]
hash 存储 一个大KEY 400多kb的json。卡死。

**Comment by tiny-craft** [comment]
> hash 存储 一个大KEY 400多kb的json。卡死。

只hash内每一个key都是400kb的json还是其中一两个？有没有选了格式是`JSON`，还是只选了`Raw`

**Comment by zhifeifu** [comment]
> > hash 存储 一个大KEY 400多kb的json。卡死。
> 
> 只hash内每一个key都是400kb的json还是其中一两个？有没有选了格式是`JSON`，还是只选了`Raw`

hash 存储的其中一个field的值是一个400多kb大小的json字符串。在左边key值点击时就卡死了。

**Comment by tiny-craft** [comment]
> hash 存储的其中一个field的值是一个400多kb大小的json字符串。在左边key值点击时就卡死了。

什么系统，是机器配置比较低吗。我试过20M的json也不会这样，下图是刚试的2MB的JSON字符串

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/13422cf0-d9fa-4e90-9fd5-ab50a9d0d0f8)

**Comment by tiny-craft** [comment]
hash等多数据的类型已经禁用自动格式检测和格式化，因为容易卡死
