### ISSUE TITLE
[FEATURE] 支持精确查找吗，有时想看一个 key 的内容，必须通过搜索

### ISSUE THREAD

**Issue by j20cc** [tiny-craft/tiny-rdm#176]
如果 key 比较多的话，扫描起来很慢，但是我只是想看一个指定 key 的内容

**Comment by tiny-craft** [comment]
很巧，这两天正在做

**Comment by tiny-craft** [comment]
Duplicate of #164

**Comment by tiny-craft** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/46af8ec4-119c-4151-87f6-44ec44a875e7)

[v1.1.10](https://github.com/tiny-craft/tiny-rdm/releases)版本已经支持键`完全匹配`
