### ISSUE TITLE
[BUG] String类型的值在不同查看方式保存后下显示结果不一致

### ISSUE THREAD

**Issue by Aliothmoon** [tiny-craft/tiny-rdm#179]
Tiny-RDM v1.1.9

![image](https://github.com/tiny-craft/tiny-rdm/assets/107878625/ab49f757-0a7a-41d7-88e9-6313d50ed391)
修改后进行保存
![image](https://github.com/tiny-craft/tiny-rdm/assets/107878625/60b908d0-4f98-49c4-ae79-3b792b78339f)
在切换查看方式后，显示结果变为初始查看值
![image](https://github.com/tiny-craft/tiny-rdm/assets/107878625/6e2baffc-b0d9-4d87-93c9-8df7147ee733)
刷新后结果正常，希望能够在保存后自动刷新不同查看方式显示结果。

此外在开启定时刷新后，显示结果会被强制覆盖，在Win11 22H2 下出现 monaco-editor 的闪烁，希望能够消除渲染的闪烁。

**Comment by tiny-craft** [comment]
这个问题在这个提交 b46cc6c436666f36f9b27c19b0cb400522b004f2 中已经修复，会包含在下个版本的更新中

还有闪烁是不是因为有个前置的loading动画让你认为是在闪烁？如果是其他原因，最好给我个截图或者视频我看看什么情况

**Comment by Aliothmoon** [comment]
应该是loading效果导致的，中间会有短暂的闪烁情况
![image](https://github.com/tiny-craft/tiny-rdm/assets/107878625/982478fa-0004-4861-8944-d347e2d314fa)
，能否支持像AnotherRedisDesktopManager一样编辑器无感的刷新呢？

**Comment by Aliothmoon** [comment]
是的，Win11 22H2
