### ISSUE TITLE
建议：添加过滤DB的功能

### ISSUE THREAD

**Issue by wowguoqing** [tiny-craft/tiny-rdm#18]
现在的开发场景：甲方提供redis等环境，好几个项目组共用一个连接，分配不同DB，所以想说，能不能设置连接的默认DB，以及过滤DB

**Comment by whtiehack** [comment]
还有.db显示不全.需要一个类似 rdm的这个配置:

![image](https://github.com/tiny-craft/tiny-rdm/assets/12741016/feb78f79-8216-4e66-aaf8-52fa25afe9ca)

**Comment by tiny-craft** [comment]
@whtiehack 这个数据库发现限制设置的是什么，比如设20就只限时最多20个数据库吗。我这的resp貌似不是这个逻辑，不是很懂它的设定是啥意思

**Comment by whtiehack** [comment]
> @whtiehack 这个数据库发现限制设置的是什么，比如设20就只限时最多20个数据库吗。我这的resp貌似不是这个逻辑，不是很懂它的设定是啥意思

![image](https://github.com/tiny-craft/tiny-rdm/assets/12741016/705b4192-f1e3-43dc-8e2f-5bfca50a97df)


这是这个展示的db数量,  db0 ,db1 , dbxxx

tiny-rdm只展示了16个

![image](https://github.com/tiny-craft/tiny-rdm/assets/12741016/057e37df-3f5f-4dc2-ad1b-c0a232848953)


---

实际上 有这么多db

![image](https://github.com/tiny-craft/tiny-rdm/assets/12741016/3696211d-42b0-4eb9-aaa1-ce70ff9b7cb9)



![image](https://github.com/tiny-craft/tiny-rdm/assets/12741016/33d62527-c7e7-4d13-9b07-3b49d4fd3eb6)

**Comment by tiny-craft** [comment]
> > @whtiehack 这个数据库发现限制设置的是什么，比如设20就只限时最多20个数据库吗。我这的resp貌似不是这个逻辑，不是很懂它的设定是啥意思
> 
> ![image](https://user-images.githubusercontent.com/12741016/273377400-705b4192-f1e3-43dc-8e2f-5bfca50a97df.png)
> 
> 这是这个展示的db数量, db0 ,db1 , dbxxx
> 
> tiny-rdm只展示了16个
> 
> ![image](https://user-images.githubusercontent.com/12741016/273377436-057e37df-3f5f-4dc2-ad1b-c0a232848953.png)
> 
> 实际上 有这么多db
> 
> ![image](https://user-images.githubusercontent.com/12741016/273377450-3696211d-42b0-4eb9-aaa1-ce70ff9b7cb9.png)
> 
> ![image](https://user-images.githubusercontent.com/12741016/273377572-33d62527-c7e7-4d13-9b07-3b49d4fd3eb6.png)

这个问题1.0.2版本以上还是显示不对吗，是不是你的redis服务器没有config get命令。或者你起了别名?

**Comment by whtiehack** [comment]
@tiny-craft 1.0.2没问题了

**Comment by tiny-craft** [comment]
1.0.4已经支持数据库筛选设定，显示全部/显示指定/隐藏指定
