### ISSUE TITLE
不打招呼报分辨率，已删除

### ISSUE THREAD

**Issue by br7roy** [tiny-craft/tiny-rdm#181]
![image](https://github.com/tiny-craft/tiny-rdm/assets/14069594/7960f1a3-5c14-4aca-9b84-cb3ccae146d0)
![image](https://github.com/tiny-craft/tiny-rdm/assets/14069594/54400dee-6db6-4730-bbd6-6d24cbf5b299)
![image](https://github.com/tiny-craft/tiny-rdm/assets/14069594/83f6602e-9783-4140-835d-7254c9cb50e5)

**Comment by tiny-craft** [comment]
这只是个简单的启动统计，代码都在仓库里，[这是代码路径](https://github.com/tiny-craft/tiny-rdm/blob/main/frontend/index.html)，统计系统用的开源的[umami](https://github.com/umami-software/umami)

**Comment by tiny-craft** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/d7501dc2-a646-46f2-8d25-6f3418831d4d)

本来也只是想简单统计下每日用户活跃，匆匆接了`UMAMI`，确实没留意到它默认上传分辨率([相关文档链接](https://umami.is/docs/tracker-functions))。

[v1.1.10](https://github.com/tiny-craft/tiny-rdm/releases)版本已经加入声明和提供选项选择，用户初次启动软件会弹出，并且在`偏好设置`中也加入了开关选项和[《隐私政策》](https://redis.tinycraft.cc/zh/guide/privacy.html)链接。这所有统计行为都是开源的，欢迎监督就是了。

最后无论你还用不用`Tiny RDM`，都感谢反馈这个问题。我们江湖再见~
