### ISSUE TITLE
[FEATURE] 支持多种key 分隔符

### ISSUE THREAD

**Issue by subchen** [tiny-craft/tiny-rdm#183]
目前每个server只能配置一种分隔符，默认是`:`，但是在一些情况下，可能存在各种格式的可能，所以最好能支持多种分隔符，比如 `:/`。就是说遇到 `:` 或者 `/` 都会进行分割。

**Comment by tiny-craft** [comment]
关于多分隔符为什么不支持，这里的回复#66有说明

**Comment by subchen** [comment]
多谢，能明白你的顾虑，如果有很好规范的话，一个分隔符是足够的。

就是担心没有好的规范，长时间的项目，人员流动导致各种样式都存在。
