### ISSUE TITLE
状态tab页中的活动状态会耗费大量的msedgewebview2.exe的 CPU 时间[BUG]

### ISSUE THREAD

**Issue by yunnysunny** [tiny-craft/tiny-rdm#188]
**Tiny RDM Version**
1.1.9

**OS Version**
win10

**Redis Version**
6.0.5
**Describe the bug**
将界面停留在 状态 标签页下的 活动状态 时，由于实时绘制的状态曲线会耗费大量的 msedgewebview2.exe CPU 时间
Steps to Reproduce:

1. 打开状态页，查看 活动状态 ，msedgewebview2.exe CPU 升上去。
2. 切换到其他 tab 页，msedgewebview2.exe CPU 将为 0

**Comment by tiny-craft** [comment]
开了自动更新吗

**Comment by yunnysunny** [comment]
开启了自动刷新，默认5s刷新

**Comment by tiny-craft** [comment]
帮忙再看看不开自动刷新情况下，和不开自动刷新，只是手动定时点右上角刷新按钮，会不会这样

**Comment by yunnysunny** [comment]
不开自动刷新，手动点刷新按钮，也会高

**Comment by tiny-craft** [comment]
经检查是`chart.js`每次更新数据重绘会消耗不少资源，尤其是开启了动画的情况下需要每更新一次数据就需要重绘多次。目前临时办法是禁用动画，后续有时间我再尝试下使用`echart`看看资源消耗如何。

欢迎使用[v1.1.10](https://github.com/tiny-craft/tiny-rdm/releases)版本体验。
