### ISSUE TITLE
一些可用性的问题

### ISSUE THREAD

**Issue by ydq** [tiny-craft/tiny-rdm#19]
<img width="1136" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/250eded7-0d06-4cbb-989a-b12abfc04d57">

## Env
tiny-rdm version: 1.0.1
os version:  MacOS Ventura 13.5.2 (Apple M1 arm)

## 有如下问题和建议

1. 我们线上有超1亿的 key，这种情况下，直接 scan 全部的 key 会导致本地直接挂掉（RDM/RESP 也有这个问题，目前发现 redis-pro 和 medis 可以使用，其中 medis 也是支持 key 按照 tree 模式展开的，但它是懒加载的，在最下面提供一个 “scan more” 的按钮 ）
2. 我们线上的 db 数量 超过16个，目前没找到超过16个的db 在哪操作和管理
3. 新建链接界面，文本框不支持鼠标选中（本意是想框选默认值然后删除，结果变成了移动整个窗体）
4. 同时开启多个链接后，切换右侧 server 的 tab 后，右侧 info 信息，除了名称变了之外其它信息不自动触发刷新，容易看错
5. light 主题下 失去焦点后 窗体控制按钮（关闭、最小化、最大化）颜色和背景色融为了一体，而 dark 主题却能看得到
6. 期望添加 命令模式，支持直接执行 redis 命令（类似于 medis）

**Comment by tiny-craft** [comment]
@ydq 
1. key分段加载在未来的版本规划中
2. 获取db数不符的问题最新版已经修复
3. 编辑框会拖动窗口最新版已经修复
4. 切换tab后信息没刷新最新版已修复
5. 这个是哪个系统上的？我macOS上没发现问题。其他系统没留意
6. 命令行模式也在未来版本规划中

**Comment by ydq** [comment]
> @ydq
> 
> 1. key分段加载在未来的版本规划中
> 2. 获取db数不符的问题最新版已经修复
> 3. 编辑框会拖动窗口最新版已经修复
> 4. 切换tab后信息没刷新最新版已修复
> 5. 这个是哪个系统上的？我macOS上没发现问题。其他系统没留意
> 6. 命令行模式也在未来版本规划中

@tiny-craft 关于上述第5点
测试的一直是 MacOS 系统，我现在已经升级到最新的 MacOS Sonoma 14 了，暂时也没复现

---

但是发现了另外一个问题（可能是与 Sonoma 的兼容问题？手头没有旧版系统了，无法测试旧版是否有此问题了）


我电脑不是刘海屏，但是也喜欢主动调整成了和刘海屏Mac一样的一直显示顶部菜单栏（即其它软件全屏最大化也会显示顶部的纯黑色菜单栏）
> 新版系统设置路径：设置 - 控制中心 - 最底部 - 自动隐藏和显示菜单了 - 设置为“永不”
> PS：MacOS 13 也支持这么设置，不太记得旧版系统是否也有这个问题

<img width="827" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/c8eafcbf-f73f-46e3-a76e-bb7ec80ed569">


然后发现 tiny-RDM 全盘之后出现很怪异的显示（下面是和其它软件「Chrome」对比的截图和录屏）：

|App|默认状态|鼠标悬浮|
|---|---|---|
|Tiny RDM|<img width="236" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/6a418992-b380-48ea-9d63-0bdf5e90a3e0">|<img width="301" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/8b391124-2d63-4135-9821-0b725f8d88c7">|
|Chrome|<img width="326" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/d3811292-f1e4-4a2a-8937-d27ff99a39ae">|<img width="316" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/996d0a2d-67f1-48c7-a85d-cc419fd3d28a">|

|Tiny RDM 录屏|Chrome 录屏|
|---|---|
|<video src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/67c3abf9-5cb0-41f1-a156-421e8be52fd1" width="195"  ></video>|<video src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/ac138039-10b8-4a28-bbea-5ed98e2e0484" width="246" muted autoplay loop ></video>|


- 强制显示了顶部控制栏（默认应该是隐藏，鼠标浮动到顶部才会下浮显示）
- 顶部控制栏遮盖了默认一直显示的菜单栏
- 全屏模式下，直角屏幕能看得到最大化之后顶部窗体的圆角（深色主题特别明显）

**Comment by tiny-craft** [comment]
👍🏻描述得很详细

- macOS下全屏显示圆角还在这个是我已知问题，目前wails没有被动监听窗口变化的方式，所以我还在考虑其他实现方式
- 标题栏问题估计也不好弄，wails提供的系统级接口不多。我是旧的系统，所以一直没留意到这个问题，后面有新系统的电脑我再看看能不能弄😂

**Comment by ydq** [comment]
> 👍🏻描述得很详细
> 
> * macOS下全屏显示圆角还在这个是我已知问题，目前wails没有被动监听窗口变化的方式，所以我还在考虑其他实现方式
> * 标题栏问题估计也不好弄，wails提供的系统级接口不多。我是旧的系统，所以一直没留意到这个问题，后面有新系统的电脑我再看看能不能弄😂


家里旧的 MacBook 试了下（系统 MacOS 12.7 Monterey），也有最大化标题栏顶部被盖住的问题

---

另外发现一个不重要的小问题， 我家里有两台比较旧的 Macbook，一台 2014 款 13 寸 MacBook Pro，一台 2016 款 12 寸的 MacBook，系统默认的缩放分辨率都是 1280 * 800 （后面出的macbook 默认分辨率都高一些应该不会有这个问题）

而 TinyRDM 的最小高度会导致在非全屏状态下，窗体底部会超出工作区域被dock栏给盖住（目前窗体默认限制的最低高度应该是要大于 默认分辨率 800 的高度 减去 顶部菜单栏 再减去底部的 dock 栏 的剩余高度）

<img width="530" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/7695c85f-86d5-4548-bbc0-0d8c61cd4b75">


<img width="446" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/b294c433-cc90-44f9-9725-66af20389a9a">


<img width="1280" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/cc5aa6ac-0644-4435-8dae-35b42a7d6ad6">

暂时只能全屏使用 或者 先全屏再退出全屏让系统强制调整窗体的大小（无伤大雅的小问题，比较老机器了，并非开发主力机）

**Comment by tiny-craft** [comment]
好，分辨率这个问题我记一下。之前担心缩太小影响观感和布局做了下限制，确实忽略了低分辨率的效果
