### ISSUE TITLE
[FEATURE] 设置自定义key加载数量

### ISSUE THREAD

**Issue by venomtic** [tiny-craft/tiny-rdm#190]
是否可以加入自定义key加载数量设置？

**Comment by tiny-craft** [comment]
偏好设置里面有，SCAN数量
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/b90533b0-d82c-4afb-b65c-f7e2ef628877)

**Comment by tiny-craft** [comment]
如果是要设置每次加载数量，要在对应连接上直接进行编辑，高级配置里面有“单次加载键数量”，应该就是你想要的效果
