### ISSUE TITLE
[BUG]redis server端实际有写入数据，但工具上查不到

### ISSUE THREAD

**Issue by hei-ying** [tiny-craft/tiny-rdm#192]

**Comment by tiny-craft** [comment]
哪个版本Tiny RDM？
写入的是什么数据（Key，还是Hash这些复杂结构里面的）？
在Tiny RDM上怎么查的？键列表上查还是复杂结构内的筛选？

`1.1.9`之前的版本键列表查询有点问题，如果不是`1.1.9`可以尝试更新到这个版本

**Comment by tiny-craft** [comment]
太久没回复了，这个问题如果还没解决，欢迎再回来重开issue
