### ISSUE TITLE
[FEATURE] 可以添加一个 javaserialize 吗

### ISSUE THREAD

**Issue by wuduanpiao** [tiny-craft/tiny-rdm#193]
可以添加一个 javaserialize 吗
![image](https://github.com/tiny-craft/tiny-rdm/assets/5276177/f6863812-9cc1-4a84-bcf8-eb26947667d3)

**Comment by tiny-craft** [comment]
使用自定义解码，自己用java写一个即可，Go实现其他语言的反序列化兼容性不好。
`1.1.9`版本以上支持自定义，[具体教程链接在这](https://redis.tinycraft.cc/zh/guide/custom-decoder/)

**Comment by jay-xon** [comment]
自己写好难，研究半天都没搞出来，可能我水平有限，还是建议内置下。

**Comment by tiny-craft** [comment]
> 自己写好难，研究半天都没搞出来，可能我水平有限，还是建议内置下。

以为每个用户的序列化都不通用，所以没办法内置。只能看后面找时间写个Java外置给大家参考了

**Comment by tiny-craft** [comment]
@wuduanpiao @jay-xon 你们说的java序列化，是指java内置的序列化，还是使用jackson或fastjson序列化后的字符串

**Comment by jay-xon** [comment]
> @wuduanpiao @jay-xon 你们说的java序列化，是指java内置的序列化，还是使用jackson或fastjson序列化后的字符串

就java内置的序列化，之前用的AnotherRedisDesktopManager就内置有这个javaserialize，看能不能也内置支持下。
![image](https://github.com/tiny-craft/tiny-rdm/assets/40010547/ce8a74b4-2d1f-45ab-9e01-91a95fc2273d)

**Comment by HujwCreator** [comment]
> > 你们说的java序列化，是指java内置的序列化，还是使用jackson或fastjson序列化后的字符串
> 
> 就java内置的序列化，之前用的AnotherRedisDesktopManager就内置有这个javaserialize，看能不能也内置支持下。 ![图像](https://private-user-images.githubusercontent.com/40010547/332357203-ce8a74b4-2d1f-45ab-9e01-91a95fc2273d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1OTE1MDMsIm5iZiI6MTcxODU5MTIwMywicGF0aCI6Ii80MDAxMDU0Ny8zMzIzNTcyMDMtY2U4YTc0YjQtMmQxZi00NWFiLTllMDEtOTFhOTVmYzIyNzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAyMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiOTZjNTE0MWY2MGQ4OThhZTlkNmY3ZTk2YmE3NjA1YTY0OTRjODBhMzFjYmY4ZDU3YjJjODVhNWEyMjdjYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3-9ngYpy-hZ1aXldvhEuWajkGN27sgC38Uy6_q1HwA)

+1  从AnotherRedisDesktopManager过来之后，发现很多键乱码了，才知道是没有序列化

**Comment by tiny-craft** [comment]
看来用Tiny RDM的java开发者不少，Pro会考虑把Java序列化内置的，Go的Java序列化库都很久，太多问题所以目前不折腾先

**Comment by zerlynn** [comment]
> 看来用Tiny RDM的java开发者不少，Pro会考虑把Java序列化内置的，Go的Java序列化库都很旧，太多问题所以目前不折腾先

很多使用redis的都是java开发者。所以缓存很多java类。希望能快速支持。不然java开发者都只能使用AnotherRedisDesktopManager等工具来查看key。

**Comment by tiny-craft** [comment]
> > 看来用Tiny RDM的java开发者不少，Pro会考虑把Java序列化内置的，Go的Java序列化库都很旧，太多问题所以目前不折腾先
> 
> 很多使用redis的都是java开发者。所以缓存很多java类。希望能快速支持。不然java开发者都只能使用AnotherRedisDesktopManager等工具来查看key。

说得很有道理😁

**Comment by SherlockerSun** [comment]
issue关闭还以为内置了，结果还是没有，还是老老实实用AnotherRedisDesktopManager吧
