### ISSUE TITLE
[BUG]连接后Console中无法输入命令

### ISSUE THREAD

**Issue by wzlstudy** [tiny-craft/tiny-rdm#194]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.9
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
macOS Sonoma 14.4
**Redis Version**
Which version of Redis are you using?
7.2.3
**Describe the bug**
连接上Redis后，在Console中无法输入英文
Steps to Reproduce:
<img width="715" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/54768887/844668d3-cb04-432a-b48c-544f24562698">
如图，输入法切换到英文后，无法输入英文字母，但切换到中文后，可以输入中文内容

**Comment by wzlstudy** [comment]
Mac上安装的搜狗输入法，应该不是输入法问题

**Comment by tiny-craft** [comment]
切换到英文后，是指切换到这个吗
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/db365823-245d-4052-9558-a8847d53b8b7)

**Comment by wzlstudy** [comment]
<img width="162" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/54768887/273ebb1c-239a-41db-849f-d25cbadcce27">
是的

**Comment by tiny-craft** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/c6dfa220-f4eb-4398-ba52-edc0f8bc1dbd)
这个吗，我这搜狗输入法好像没法切换到你这种标题栏状态。搜狗是什么版本，Mac是Intel还是Arm得

**Comment by wzlstudy** [comment]
<img width="408" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/54768887/c078ed1c-f1d5-49c1-983d-73220d09e86f">
就是中英文切换，切换到英文后，就输入不了了

**Comment by tiny-craft** [comment]
感觉可以先更新搜狗输入法试下，我的搜狗是`6.14`，目前没发现有问题。
你这个版本的输入法我晚点装来看看会不会有这个问题

**Comment by wzlstudy** [comment]
嗯，升级后可以了

**Comment by loulangogogo** [comment]
我的输入法是 6.16.0 最新版，但是无法输入
