### ISSUE TITLE
[BUG] deepin V23 打开白屏

### ISSUE THREAD

**Issue by kt286** [tiny-craft/tiny-rdm#195]
**Tiny RDM Version**
1.1.10

**OS Version**
Linux  deepin v23

**Redis Version**
7.0

**Describe the bug**
打开后白屏，中间有半个红色 loading 圆圈

![image](https://github.com/tiny-craft/tiny-rdm/assets/10684972/523afdbb-5bf5-42f8-929e-407a8234bbde)

**Comment by tiny-craft** [comment]
是`deb`还是`AppImage`啊

**Comment by kt286** [comment]
> 是`deb`还是`AppImage`啊

deb包，而且下载代码 dev 的时候也白屏

**Comment by tiny-craft** [comment]
dev模式下，go控制台和web控制台有什么报错没

**Comment by kt286** [comment]
web 控制台没有任何输出
![image](https://github.com/tiny-craft/tiny-rdm/assets/10684972/ade06ea9-582b-4b82-ad7c-144318c006f0)

go控制台输入见文件，其中可能值得关注的信息如下
![image](https://github.com/tiny-craft/tiny-rdm/assets/10684972/1621d302-3154-4301-9296-e40abefbb914)

[go 输出.txt](https://github.com/tiny-craft/tiny-rdm/files/14685793/go.txt)

**Comment by raojinlin** [comment]
@kt286 设置下这个环境变量，在运行看看：
```
export WEBKIT_DISABLE_COMPOSITING_MODE=1
```

**Comment by kt286** [comment]
> @kt286 设置下这个环境变量，在运行看看：
> 
> ```
> export WEBKIT_DISABLE_COMPOSITING_MODE=1
> ```

可以了
