### ISSUE TITLE
请问“总是显示最新”按钮是什么作用？

### ISSUE THREAD

**Issue by MerFrederick** [tiny-craft/tiny-rdm#196]
监控页和发布/订阅页的两个红色按钮

**Comment by tiny-craft** [comment]
就是有新的内容，滚动条都滚到最新内容那。
看来这描述还是不太明了，我在找找其他软件的描述参考😂

**Comment by MerFrederick** [comment]
> 就是有新的内容，滚动条都滚到最新内容那。 看来这描述还是不太明了，我在找找其他软件的描述参考😂

理解了。按钮究竟是红色还是白色时激活此功能也不太清楚，提示都是“总是显示最新”，方便时也可以优化下。
