### ISSUE TITLE
[FEATURE] JSON 查看页面希望变成彩色的

### ISSUE THREAD

**Issue by AYiXi** [tiny-craft/tiny-rdm#197]
<img width="1899" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/28703786/e33e5250-1879-40ef-be93-a1c8ed2aabd6">
如图, 编辑页面都是彩色的, 查看页面是灰色的, 不好区分

**Comment by tiny-craft** [comment]
列表内再加高亮，会有比较严重的性能问题，甚至滑动列表都有点卡顿了。
原来是有的，因为这个原因我又去掉了😂

**Comment by jiongjiongJOJO** [comment]
> 列表内再加高亮，会有比较严重的性能问题，甚至滑动列表都有点卡顿了。 原来是有的，因为这个原因我又去掉了😂

列表能否隐藏起来不要解析，很多时候需要的是点开查看解析的内容，外面只需要看个大致就行
