### ISSUE TITLE
列表排序优化建议

### ISSUE THREAD

**Issue by hawcgn** [tiny-craft/tiny-rdm#198]
***希望数字排序时，按实际大小做正序。见图：***

![Snipaste_2024-03-22_08-55-35](https://github.com/tiny-craft/tiny-rdm/assets/150403800/f18586c7-90b8-43c9-9ce8-ffcf8547d3b4)

**Comment by tiny-craft** [comment]
最新版排序已经将数字类型的字符串优先并按数字的实际值排序
