### ISSUE TITLE
[BUG] key太多的时候，左侧树列表刷新不出来

### ISSUE THREAD

**Issue by 89333367** [tiny-craft/tiny-rdm#199]
**Tiny RDM Version**
1.1.10

**OS Version**
Windows11

**Redis Version**
3.2.2

**Describe the bug**
![image](https://github.com/tiny-craft/tiny-rdm/assets/20157752/a4de61d8-a80e-4a12-b4ff-b81f66cbcadf)

Steps to Reproduce:
点击加载所有剩余键，然后就卡死了，每次都卡死。

**Comment by tiny-craft** [comment]
你说的`卡死`是指真个应用窗口都变成了未响应，还是只是你截图那的圈一直在转？

300多万个key全加载出来需要挺长时间的，这取决于你redis服务器带宽，以及机器配置（构建树状结构视图也是需要消耗不少资源）。

我建议你就加载部分，通过上面搜索框模糊匹配你所需的。因为300多万key就算全加载出来，你也不会全都需要马上编辑。

**Comment by 89333367** [comment]
> 你说的`卡死`是指真个应用窗口都变成了未响应，还是只是你截图那的圈一直在转？
> 
> 300多万个key全加载出来需要挺长时间的，这取决于你redis服务器带宽，以及机器配置（构建树状结构视图也是需要消耗不少资源）。
> 
> 我建议你就加载部分，通过上面搜索框模糊匹配你所需的。因为300多万key就算全加载出来，你也不会全都需要马上编辑。

嗯，是整个窗口都无响应了。
然后模糊匹配，我只想匹配ne:realtime:*这种，这里面就上百万key，还是会卡死。
如果能加载一点，左侧的树就append一下，就好了，不用等待所有数据都返回，再刷新树，是不是会好一点？

**Comment by tiny-craft** [comment]
> 嗯，是整个窗口都无响应了。 然后模糊匹配，我只想匹配ne:realtime:*这种，这里面就上百万key，还是会卡死。 如果能加载一点，左侧的树就append一下，就好了，不用等待所有数据都返回，再刷新树，是不是会好一点？

1. 再缩小匹配范围

2. 点`加载更多`这个按钮，会继续加载下一部分。
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/608f2099-d817-4571-906d-3bde814d2076)

你说的方式应该是点`加载全部`，然后分批次追加，这种方式在key少的时候会视觉上变慢，因为重新构建视图的数据结构和重绘是需要大量性能的。而在数据量大的时候，到了未响应的瓶颈，依然会未响应...
