### ISSUE TITLE
【PERFORMANCE】性能问题

### ISSUE THREAD

**Issue by yiding-he** [tiny-craft/tiny-rdm#2]
![图片](https://github.com/tiny-craft/tiny-rdm/assets/900606/90f1b186-a013-4b5a-b6e6-c01c42c6fed3)
这也是几乎所有的 Redis 客户端开发者都忽略的性能问题：

1. 尝试列举所有的 key，导致网络带宽被占满，同时客户端自己也无法操作；
2. 列举出所有的 key 会导致客户端的内存暴涨，无法进行操作。

**Comment by ddv12138** [comment]
我也是同样的问题，key太多直接卡死，没必要一次列出所有库，也没必要一次获取所有key

**Comment by tiny-craft** [comment]
这个也是我刚开始做的时候纠结的问题，究竟要不要一次加载。分段加载的话，又不太好排序。后续考虑增加“一次加载所有”和“一次只加载指定数量Key”的选项

**Comment by yiding-he** [comment]
这个问题的核心矛盾是 Redis 的 Key 没有分层结构，也没有提供按照指定分隔符来列举前缀的 API，所以最好的办法是不要用树结构，也不要尝试列举全部的 key，而是让用户先提供一个前缀然后进行列举，而且每次列举有限制比如不超过 1000 条。总之就是我客户端资源有限，缩小搜索范围的责任应该交给用户。

**Comment by ddv12138** [comment]
可以参考下[AnotherRedisDesktopManager](https://github.com/qishibo/AnotherRedisDesktopManager)
大致逻辑是默认一次只拿一部分，默认按照`:`分层，但是也提供让用户选择一次性按照当前筛选条件加载全部

**Comment by Zhao-github** [comment]
除了本地和服务器性能问题，还有就是需要兼顾key查询搜索，需要关注慢查询命令操作，比如keys，比如scan等等。还有就是遇到大的hash或者list的时候，需要取舍

**Comment by KKKKKKKEM** [comment]
补充一下，好像现在如果一个 Key （例如 Set）里面的 Value 很多的时候，点击查看这个 Key 就会很慢很慢，能感觉到明显的卡顿，是否应该支持一下翻页模式，这样可以快速加载出来，然后需要加载剩下的可以由用户自己翻页
因为量大的时候，很多需求可能仅仅是查看这个 Key 里面还有多少value， 而不是查看所有的 Value 都是什么

**Comment by tiny-craft** [comment]
> 补充一下，好像现在如果一个 Key （例如 Set）里面的 Value 很多的时候，点击查看这个 Key 就会很慢很慢，能感觉到明显的卡顿，是否应该支持一下翻页模式，这样可以快速加载出来，然后需要加载剩下的可以由用户自己翻页 因为量大的时候，很多需求可能仅仅是查看这个 Key 里面还有多少value， 而不是查看所有的 Value 都是什么

这个后续版本会做，key分段加载下一个新版会上，list/hash/set/zset/steam的分页估计下一个版本

**Comment by tiny-craft** [comment]
1.0.8版本已经增加key分批加载和相关配置项

**Comment by KKKKKKKEM** [comment]
不好意思，借这个 issue 提几个问题
1. 数级别的按钮没有小刷新按钮了嘛 ？
![image](https://github.com/tiny-craft/tiny-rdm/assets/30348060/a1fff567-bd75-4c61-8705-e833ab066d23)

2. Key 分批加载出现以下情况能否在优化一下：
例如有一部分 Key ：
xxx:1
xxx:2
xxx:3
yyy:1
yyy:2
yyy:3

因为分批加载， 假设加载阈值是 3，目前的情况是加载了 xxx:1, xxx:2, yyy:1, 没有加载 xxx:3，yyy:2，yyy:3
理论上是不是应该加载的 xxx:1, xxx:2，xxx:3 而不是目前的情况？也就是先加载类似的 （需要排序），否则很容易误以为 xxx:3 本来就不存在（但是实际上是存在的，只是因为分批没有加载出来，所以每次都需要点击加载全部才知道到底存不存在）

**Comment by tiny-craft** [comment]
> 不好意思，借这个 issue 提几个问题
> 
> 1. 数级别的按钮没有小刷新按钮了嘛 ？
>    ![image](https://user-images.githubusercontent.com/30348060/280200237-a1fff567-bd75-4c61-8705-e833ab066d23.png)
> 2. Key 分批加载出现以下情况能否在优化一下：
>    例如有一部分 Key ：
>    xxx:1
>    xxx:2
>    xxx:3
>    yyy:1
>    yyy:2
>    yyy:3
> 
> 因为分批加载， 假设加载阈值是 3，目前的情况是加载了 xxx:1, xxx:2, yyy:1, 没有加载 xxx:3，yyy:2，yyy:3 理论上是不是应该加载的 xxx:1, xxx:2，xxx:3 而不是目前的情况？也就是先加载类似的 （需要排序），否则很容易误以为 xxx:3 本来就不存在（但是实际上是存在的，只是因为分批没有加载出来，所以每次都需要点击加载全部才知道到底存不存在）

1. 分批加载情况下，如果没层还加单独刷新，那还没加载的部分，是应该全部加载，还是只刷新当前层级下有的key呢？如果是前者，那假设这个层级下占了90%的key，那分批加载就没意义了，而且打乱了根节点分批加载的游标；如果是后者，好似用处不大
2. 分批用的是SCAN命令，SCAN命令是无需的，所以无法保证一定会按字符编码顺序先加载前面的

**Comment by KKKKKKKEM** [comment]
> > 不好意思，借这个 issue 提几个问题
> > 
> > 1. 数级别的按钮没有小刷新按钮了嘛 ？
> >    ![image](https://user-images.githubusercontent.com/30348060/280200237-a1fff567-bd75-4c61-8705-e833ab066d23.png)
> > 2. Key 分批加载出现以下情况能否在优化一下：
> >    例如有一部分 Key ：
> >    xxx:1
> >    xxx:2
> >    xxx:3
> >    yyy:1
> >    yyy:2
> >    yyy:3
> > 
> > 因为分批加载， 假设加载阈值是 3，目前的情况是加载了 xxx:1, xxx:2, yyy:1, 没有加载 xxx:3，yyy:2，yyy:3 理论上是不是应该加载的 xxx:1, xxx:2，xxx:3 而不是目前的情况？也就是先加载类似的 （需要排序），否则很容易误以为 xxx:3 本来就不存在（但是实际上是存在的，只是因为分批没有加载出来，所以每次都需要点击加载全部才知道到底存不存在）
> 
> 1. 分批加载情况下，如果没层还加单独刷新，那还没加载的部分，是应该全部加载，还是只刷新当前层级下有的key呢？如果是前者，那假设这个层级下占了90%的key，那分批加载就没意义了，而且打乱了根节点分批加载的游标；如果是后者，好似用处不大
> 2. 分批用的是SCAN命令，SCAN命令是无需的，所以无法保证一定会按字符编码顺序先加载前面的

那是否可以添加一个全部加载的模式呢？ 然后全部加载模式下加会来源的小刷新

因为目前一般使用需求如下：
1. 库内 Key 很多，但是 Key 都有命名规则，如 前缀:项目名:模块名
2. 进入后可能当前只需要关注该模块，所以会一层层展开树，直到模块名这一级别
3. 可能需要过一段时间就刷新该模块名，看看都有什么类型的 Key（因为 Key 是会一直变化的）

**Comment by tiny-craft** [comment]
@KKKKKKKEM 7b3c3df 这个提交已经把前缀刷新加回来了，只要所有加载完就可刷新，最近会发新版本。
如果需要一次全部加载，可以设置里面把单次加载的次数调大，或者点“加载全部”即可。

**Comment by tiny-craft** [comment]
[v1.1.0](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.0)目前为止已经支持key分批加载，也支持复杂类型结构内的数据分批加载。这个issue就先关闭了。有什么问题欢迎新开issue反馈
