### ISSUE TITLE
[BUG] Mac下会导致打开调度中心时掉帧卡顿

### ISSUE THREAD

**Issue by HappyDadGITHUB** [tiny-craft/tiny-rdm#200]
**Tiny RDM Version**
1.1.10

**OS Version**
macOS 11.6.3

**Redis Version**
7.2

**Describe the bug**
打开 Tiny RDM 后，四指向上滑动，非常卡顿。

Steps to Reproduce:

1.打开 Tiny RDM
2.四指向上滑动

**Comment by tiny-craft** [comment]
你的四指向上滑动是打开`调度中心`吗

**Comment by HappyDadGITHUB** [comment]
> 你的四个指向上滑动是打开`调度中心`吗

是的。当我想切换其他应用的时候，如果打开了 Tiny RDM后，会非常卡顿。如果关闭了，则卡顿消失。

**Comment by tiny-craft** [comment]
经检查发现是开了窗体开了半透效果就会导致掉帧，下个版本会修复
