### ISSUE TITLE
[BUG]打开会提示安装python3，这是为什么

### ISSUE THREAD

**Issue by ZaiHer21** [tiny-craft/tiny-rdm#201]
**Tiny RDM Version**
What version of Tiny RDM are you using?

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

**Redis Version**
Which version of Redis are you using?

**Describe the bug**

Steps to Reproduce:

1.
2.
![image](https://github.com/tiny-craft/tiny-rdm/assets/99528059/4f8a1ccd-243a-469a-909a-36e465b80ba5)

**Comment by tiny-craft** [comment]
有截图吗？没有依赖python哦，除非需要用pickle，但是也不会提示，只有装了才会出pickle解码选项

**Comment by tiny-craft** [comment]
看到图了，刚没加载出来，是mac什么系统

**Comment by ZaiHer21** [comment]
> 看到图了，刚没加载，是mac什么系统出来的

<img width="920" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/99528059/079ee458-1f51-4ff5-8671-5d54fe98629b">
是这个版本

**Comment by tiny-craft** [comment]
@ZaiHer21 能帮忙测试下，你的系统下在终端直接执行
```bash
python3
```
或者
```bash
python3 -v
```
是会弹出这个安装提示吗

---
如果上面的都会弹出那个安装提示
或者再试下
```bash
which python3
```
和
```bash
whereis python3
```
这两个是不是也有提示

**告诉下我只有在终端输出而没有弹出安装提示的命令，以及会输出的内容。** 谢谢~

**Comment by tiny-craft** [comment]
@ZaiHer21 可以的话帮我顺便看看这个包打开会不会提示。我换了一种检查`python3`命令是否存在的判断方式
[tinyrdm.zip](https://github.com/tiny-craft/tiny-rdm/files/14741189/tinyrdm.zip)

**Comment by tiny-craft** [comment]
@ZaiHer21 有空的话试下最新版还会不会有提示
