### ISSUE TITLE
[FEATURE] 搜索“完全匹配”按钮作用不明显

### ISSUE THREAD

**Issue by duanluan** [tiny-craft/tiny-rdm#203]
模糊匹配：
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/6fd99bab-1c65-4a20-82b9-ade96852cda0)
点击完全匹配按钮后没变化，再点一下搜索才行
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/431efd32-ebcf-42a8-bd26-a211cd2eae75)
这种效果（点击搜索或回车）算不算完全匹配？选不选“完全匹配”没区别
![image](https://github.com/tiny-craft/tiny-rdm/assets/14957667/63a60397-db65-4597-821a-2ba2981ff2d2)

**Comment by tiny-craft** [comment]
要按下搜索或者回车才会对数据库检索，也就是变成tag状态，类似图一和图三，但是图二只是对当前列出的数据进行筛选显示。

也就是通过回车后在数据库查询，再输一次不会车，可以达到组合条件的效果

**Comment by tiny-craft** [comment]
需要更多关于检索和筛选的操作，可以参考这篇用户指南https://redis.tinycraft.cc/zh/guide/filter/
