### ISSUE TITLE
[BUG] 使用自定义解码, php的serialize 无法解码

### ISSUE THREAD

**Issue by stevqin** [tiny-craft/tiny-rdm#205]
**Tiny RDM Version**
What version of Tiny RDM are you using?

配置了 php的路径, 并指定了反序列化参数. 界面效果依旧无法 将 php 的 serialize 序列化内容 解析成 json方式展示;

![image](https://github.com/tiny-craft/tiny-rdm/assets/57753404/7a5e747d-0fdf-417a-88c4-29027b288902)

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

**Redis Version**
Which version of Redis are you using?

**Describe the bug**

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment]
这里配置填错了，如果你要通过自定义实现一个php反序列化器，[可以参考这里教程](https://redis.tinycraft.cc/zh/guide/custom-decoder/)。

另外最新版Tiny RDM已经有内置PHP解码，无需上面步骤自己创建解码器。只要环境变量配置了php执行路径，也就是你通过终端直接输入`php -v`是能输出当前php版本的，Tiny RDM右下角的列表就会出现PHP选项。你现在应该是没有把这个php.exe的路径配到环境变量，所以Tiny RDM检查不出来。关于如何配置php环境，[可以参考这里](https://www.php.cn/faq/531762.html)。

**Comment by stevqin** [comment]
右下角选择 None 的模式, 字符是这样的:

s:935:"a:1:{s:9:"user_info";a:26:{s:2:"id";i:4680;s:8:"username";s:9:"BA0011166";s:6:"avatar";s:64:"https://wework.qpic.cn/wwpic/111222_SydzwcvFRCiW0at_1697454554/0";s:8:"realname";s:9:"俞思明";s:9:"job_title";s:18:"数据管理专员";s:9:"dept_name";s:61:"供应链管理中心_物流部_成衣仓_计划组_数据组";s:8:"disabled";i:0;s:5:"email";N;s:6:"mobile";s:11:"13800138000";s:10:"store_code";N;s:15:"data_permission";N;s:10:"has_system";a:1:{i:0;s:6:"guanbi";}s:20:"data_permission_mode";s:3:"and";s:14:"has_brand_list";a:0:{}s:27:"has_manage_region_name_list";a:0:{}s:14:"has_store_list";a:0:{}s:20:"has_extra_store_list";a:0:{}s:15:"last_login_time";s:19:"2024-03-25 15:55:30";s:11:"login_count";i:192;s:11:"create_time";N;s:9:"create_ip";i:0;s:11:"update_time";s:19:"2024-03-25 20:15:33";s:9:"join_date";s:10:"2023-07-03";s:14:"dimission_date";N;s:11:"client_from";s:6:"OA_SSO";s:6:"device";s:23:"Chrome 83 on Windows 10";}}";


右下角选择默认自带的 PHP 的模式, 显示出来的字符是这样的;

"a:1:{s:9:\"user_info\";a:26:{s:2:\"id\";i:4680;s:8:\"username\";s:9:\"BA0011166\";s:6:\"avatar\";s:64:\"https://wework.qpic.cn/wwpic/111222_SydzwcvFRCiW0at_1697454554/0\";s:8:\"realname\";s:9:\"俞思明\";s:9:\"job_title\";s:18:\"数据管理专员\";s:9:\"dept_name\";s:61:\"供应链管理中心_物流部_成衣仓_计划组_数据组\";s:8:\"disabled\";i:0;s:5:\"email\";N;s:6:\"mobile\";s:11:\"13800138000\";s:10:\"store_code\";N;s:15:\"data_permission\";N;s:10:\"has_system\";a:1:{i:0;s:6:\"guanbi\";}s:20:\"data_permission_mode\";s:3:\"and\";s:14:\"has_brand_list\";a:0:{}s:27:\"has_manage_region_name_list\";a:0:{}s:14:\"has_store_list\";a:0:{}s:20:\"has_extra_store_list\";a:0:{}s:15:\"last_login_time\";s:19:\"2024-03-25 15:55:30\";s:11:\"login_count\";i:192;s:11:\"create_time\";N;s:9:\"create_ip\";i:0;s:11:\"update_time\";s:19:\"2024-03-25 20:15:33\";s:9:\"join_date\";s:10:\"2023-07-03\";s:14:\"dimission_date\";N;s:11:\"client_from\";s:6:\"OA_SSO\";s:6:\"device\";s:23:\"Chrome 83 on Windows 10\";}}"


根据文档配置的 PHP， 使用的php脚本后；
结果与 自带的 PHP 模式 显示结果一致。
![image](https://github.com/tiny-craft/tiny-rdm/assets/57753404/fb2eb69c-0051-45a7-a667-9796d9ec6093)

**Comment by tiny-craft** [comment]
> s:935:"a:1:{s:9:"user_info";a:26:{s:2:"id";i:4680;s:8:"username";s:9:"BA0011166";s:6:"avatar";s:64:"https://wework.qpic.cn/wwpic/111222_SydzwcvFRCiW0at_1697454554/0";s:8:"realname";s:9:"俞思明";s:9:"job_title";s:18:"数据管理专员";s:9:"dept_name";s:61:"供应链管理中心_物流部_成衣仓_计划组_数据组";s:8:"disabled";i:0;s:5:"email";N;s:6:"mobile";s:11:"13800138000";s:10:"store_code";N;s:15:"data_permission";N;s:10:"has_system";a:1:{i:0;s:6:"guanbi";}s:20:"data_permission_mode";s:3:"and";s:14:"has_brand_list";a:0:{}s:27:"has_manage_region_name_list";a:0:{}s:14:"has_store_list";a:0:{}s:20:"has_extra_store_list";a:0:{}s:15:"last_login_time";s:19:"2024-03-25 15:55:30";s:11:"login_count";i:192;s:11:"create_time";N;s:9:"create_ip";i:0;s:11:"update_time";s:19:"2024-03-25 20:15:33";s:9:"join_date";s:10:"2023-07-03";s:14:"dimission_date";N;s:11:"client_from";s:6:"OA_SSO";s:6:"device";s:23:"Chrome 83 on Windows 10";}}";


你这段PHP序列化字符是不是格式有误，没法反序列化的，它是通过serialize方法得来的吗，你反序列化前的对象是什么样的？
你可以用在线工具`反序列化成JSON`试下：  https://www.bejson.com/transfor/phpserialize/，没办法转成JSON

以下是通过php代码直接反序列化的例子，也没法用。我还附带了我测试用的例子，你都可以运行下看看输出结果
[php_test.php.zip](https://github.com/tiny-craft/tiny-rdm/files/14751608/php_test.php.zip)

**Comment by stevqin** [comment]
> > s:935:"a:1:{s:9:"user_info";a:26:{s:2:"id";i:4680;s:8:"username";s:9:"BA0011166";s:6:"avatar";s:64:"[https://wework.qpic.cn/wwpic/111222_SydzwcvFRCiW0at_1697454554/0";s:8:"realname";s:9:"俞思明";s:9:"job_title";s:18:"数据管理专员";s:9:"dept_name";s:61:"供应链管理中心_物流部_成衣仓_计划组_数据组";s:8:"disabled";i:0;s:5:"email";N;s:6:"mobile";s:11:"13800138000";s:10:"store_code";N;s:15:"data_permission";N;s:10:"has_system";a:1:{i:0;s:6:"guanbi";}s:20:"data_permission_mode";s:3:"and";s:14:"has_brand_list";a:0:{}s:27:"has_manage_region_name_list";a:0:{}s:14:"has_store_list";a:0:{}s:20:"has_extra_store_list";a:0:{}s:15:"last_login_time";s:19:"2024-03-25](https://wework.qpic.cn/wwpic/111222_SydzwcvFRCiW0at_1697454554/0%22;s:8:%22realname%22;s:9:%22%E4%BF%9E%E6%80%9D%E6%98%8E%22;s:9:%22job_title%22;s:18:%22%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86%E4%B8%93%E5%91%98%22;s:9:%22dept_name%22;s:61:%22%E4%BE%9B%E5%BA%94%E9%93%BE%E7%AE%A1%E7%90%86%E4%B8%AD%E5%BF%83_%E7%89%A9%E6%B5%81%E9%83%A8_%E6%88%90%E8%A1%A3%E4%BB%93_%E8%AE%A1%E5%88%92%E7%BB%84_%E6%95%B0%E6%8D%AE%E7%BB%84%22;s:8:%22disabled%22;i:0;s:5:%22email%22;N;s:6:%22mobile%22;s:11:%2213800138000%22;s:10:%22store_code%22;N;s:15:%22data_permission%22;N;s:10:%22has_system%22;a:1:%7Bi:0;s:6:%22guanbi%22;%7Ds:20:%22data_permission_mode%22;s:3:%22and%22;s:14:%22has_brand_list%22;a:0:%7B%7Ds:27:%22has_manage_region_name_list%22;a:0:%7B%7Ds:14:%22has_store_list%22;a:0:%7B%7Ds:20:%22has_extra_store_list%22;a:0:%7B%7Ds:15:%22last_login_time%22;s:19:%222024-03-25) 15:55:30";s:11:"login_count";i:192;s:11:"create_time";N;s:9:"create_ip";i:0;s:11:"update_time";s:19:"2024-03-25 20:15:33";s:9:"join_date";s:10:"2023-07-03";s:14:"dimission_date";N;s:11:"client_from";s:6:"OA_SSO";s:6:"device";s:23:"Chrome 83 on Windows 10";}}";
> 
> 你这段PHP序列化字符是不是格式有误，没法反序列化的，它是通过serialize方法得来的吗，你反序列化前的对象是什么样的？ 你可以用在线工具`反序列化成JSON`试下： [https://www.bejson.com/transfor/phpserialize/，没办法转成JSON](https://www.bejson.com/transfor/phpserialize/%EF%BC%8C%E6%B2%A1%E5%8A%9E%E6%B3%95%E8%BD%AC%E6%88%90JSON)
> 
> 以下是通过php代码直接反序列化的例子，也没法用。我还附带了我测试用的例子，你都可以运行下看看输出结果 [php_test.php.zip](https://github.com/tiny-craft/tiny-rdm/files/14751608/php_test.php.zip)

关于原始格式， 我在 php -a 的控制台里进行 反序列化， 是可以转换成 数组的；
但这个原始格式，复制到 在线反序列化的网站， 又需要经过两次反序列化才能转成 json。 很神奇了

**Comment by tiny-craft** [comment]
> 关于原始格式， 我在 php -a 的控制台里进行 反序列化， 是可以转换成 数组的； 但这个原始格式，复制到 在线反序列化的网站， 又需要经过两次反序列化才能转成 json。 很神奇了

你`php -a`里面是怎么反序列化的

**Comment by stevqin** [comment]
> > 关于原始格式， 我在 php -a 的控制台里进行 反序列化， 是可以转换成 数组的； 但这个原始格式，复制到 在线反序列化的网站， 又需要经过两次反序列化才能转成 json。 很神奇了
> 
> 你`php -a`里面是怎么反序列化的

刚刚尝试在 你提供的 php反序列化的代码中， 连续进行了2次 unserialize 后就成功了；

![image](https://github.com/tiny-craft/tiny-rdm/assets/57753404/b93f7c1a-6757-4315-ae2e-e593616df8e0)

**Comment by tiny-craft** [comment]
> > > 关于原始格式， 我在 php -a 的控制台里进行 反序列化， 是可以转换成 数组的； 但这个原始格式，复制到 在线反序列化的网站， 又需要经过两次反序列化才能转成 json。 很神奇了
> > 
> > 
> > 你`php -a`里面是怎么反序列化的
> 
> 刚刚尝试在 你提供的 php反序列化的代码中， 连续进行了2次 unserialize 后就成功了；
> 
> ![image](https://private-user-images.githubusercontent.com/57753404/316715689-b93f7c1a-6757-4315-ae2e-e593616df8e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjMzNzYsIm5iZiI6MTcxMTQyMzA3NiwicGF0aCI6Ii81Nzc1MzQwNC8zMTY3MTU2ODktYjkzZjdjMWEtNjc1Ny00MzE1LWFlMmUtZTU5MzYxNmRmOGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzMTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzViZGY4YTM1ZmYzOTE5ODhkZmZhZjUxNWZiNjUxNTZlMmEyODY4YmU1MjUzMDYxNDg3MTE0ODEzZTBhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cryZc7URG6ZFV6im_MEdUK96zkw4pg16fCEST65bxw4)

那就是你代码中写入redis之前进行了连续两次序列化

**Comment by tiny-craft** [comment]
猜测你写入redis的通用逻辑原来就会调用`serialize`，但是你又手动调了一次。
你可以做的有以下两种：
1. 修改你代码逻辑，直接写入php对象
2. 根据[Tiny RDM官方解码教程](https://redis.tinycraft.cc/zh/guide/custom-decoder/)，修改代码序列化和反序列化都改成两次。然后创建成一个适合你业务的自定义解码器

**Comment by stevqin** [comment]
> 猜测你写入redis的通用逻辑原来就会调用`serialize`，但是你又手动调了一次。 你可以做的有以下两种：
> 
> 1. 修改你代码逻辑，直接写入php对象
> 2. 根据[Tiny RDM官方解码教程](https://redis.tinycraft.cc/zh/guide/custom-decoder/)，修改代码序列化和反序列化都改成两次。然后创建成一个适合你业务的自定义解码器

感谢大神~
