### ISSUE TITLE
[BUG] key is not fully displayed

### ISSUE THREAD

**Issue by Yaqr-rong** [tiny-craft/tiny-rdm#216]
The key is not fully displayed, it actually exists
![图片](https://github.com/tiny-craft/tiny-rdm/assets/43138377/5d2700bc-351c-452f-832f-c6dc08cb4afc)
![企业微信截图_17120259404377](https://github.com/tiny-craft/tiny-rdm/assets/43138377/3e21e1d4-7717-4438-bb25-45ddf0ab6908)

**Comment by tiny-craft** [comment]
<img width="418" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/d3863a9b-6e08-4a52-b6b7-4c16fb9825ea">

<img width="334" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/e845f095-e535-48fc-9bf6-24b8cf36ee6d">

Here is the total load progress of keys, looks like you haven't fully loaded all the keys yet.
Tiny RDM loads massive keys in segments. You can either continuously press `Load More Key` or directly press `Load All Left Keys` until the progress bar is 100%.

In addition you can also go to the `Connection` -> `Advanced` -> `Keys Per Load` and set the number of segmented loads to be triggered.

<img width="624" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/9b295c79-a14b-43a4-b805-cd156b83fb48">

---

上图中图1是所有key的数量加载进度，图2也有数值对应的进度。你的Key太多了，触发了 Tiny RDM的分段加载。你可以持续点加载`加载更多键`或者直接点`加载剩余所有键`（图2右下角圈中的按钮）来加载剩余所有键。

此外你也可以到`连接设置`->`高级配置`->`单次加载键数量`中设定触发分段加载的数量。

**Comment by tiny-craft** [comment]
Please visit the user guide for more info about `Key Loading`: https://redis.tinycraft.cc/guide/key-loading/

如需了解更多关于`键加载`相关的内容，可以访问：https://redis.tinycraft.cc/zh/guide/key-loading/
