### ISSUE TITLE
[FEATURE]要是能按照这个样子的开发个mongodb的就好了

### ISSUE THREAD

**Issue by KnightBlood** [tiny-craft/tiny-rdm#221]
要是能按照这个样子的开发个mongodb的就好了

希望出一个mongodb的版本

**Comment by AYiXi** [comment]
+1, 不如直接整合, 搞个navicate吧哈哈哈哈

**Comment by tiny-craft** [comment]
> +1, 不如直接整合, 搞个navicate吧哈哈哈哈

这个确实是未来考虑的方向之一。不过大概率不是基于这个项目来做。至于是什么形式，等我想好了，会在公众号等地方发的，敬请期待😂
