### ISSUE TITLE
可以链接Docker中redis吗？

### ISSUE THREAD

**Issue by gongxiaobo** [tiny-craft/tiny-rdm#224]
我使用这软件可以链接我本地的redis，但是我docker中运行的redis就链接不上？能帮助我解决一下这个问题吗？

**Comment by Aulaydev** [comment]
可以。如果部署在云服务器上看看是不是端口没开？

**Comment by tiny-craft** [comment]
你把端口映射出本地来，就可以连了，和本地的没区别

**Comment by gongxiaobo** [comment]
我是本地运行的redis容器，我是把端口映射出来了的。

<img width="613" alt="redis_" src="https://github.com/tiny-craft/tiny-rdm/assets/12946147/fbcbed7e-1ecd-431f-a235-c7fce6cb1952">
<img width="277" alt="redis_c" src="https://github.com/tiny-craft/tiny-rdm/assets/12946147/d1121c73-6314-4280-8217-e66351f5da64">

**Comment by tiny-craft** [comment]
> 我是本地运行的redis容器，我是把端口映射出来了的。
> 
> <img alt="redis_" width="613" src="https://private-user-images.githubusercontent.com/12946147/322838688-fbcbed7e-1ecd-431f-a235-c7fce6cb1952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzA0MDcsIm5iZiI6MTcxMzI3MDEwNywicGF0aCI6Ii8xMjk0NjE0Ny8zMjI4Mzg2ODgtZmJjYmVkN2UtMWVjZC00MzFmLWEyMzUtYzdmY2U2Y2IxOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZmNjMjIzMjRiODJjMDdhYzc2ZTcyYTQyZDJmMGQ0NjY1ZTRkMzJmMWZkYjI1MGI4MDU0MWQ1NGY1NDQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_sv0FSLvThrsgGlrLIge3QjS06xL5kLELDEYqG0jxA"> <img alt="redis_c" width="277" src="https://private-user-images.githubusercontent.com/12946147/322838746-d1121c73-6314-4280-8217-e66351f5da64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNzA0MDcsIm5iZiI6MTcxMzI3MDEwNywicGF0aCI6Ii8xMjk0NjE0Ny8zMjI4Mzg3NDYtZDExMjFjNzMtNjMxNC00MjgwLTgyMTctZTY2MzUxZjVkYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDEyMjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNTk3YjdkZTY1NTNhMTRjNjhkM2NjZDU2YjcwYmIxYTUyMTEwYzQ3ZWQ4OGY5ZWNlYzA1YmJhOTY2OTY3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ST0I_qjr_h2ADm4mgPEOUh3YxoafOIPm-nLBIDco9iU">

这是提示账号密码失败。用户名你确定是`root`吗，默认情况下用户名是空的

**Comment by gongxiaobo** [comment]
我找到问题了。我不用写用户名，只写密码就可以链接了？这是为啥？

**Comment by gongxiaobo** [comment]
我使用docker-compose.yaml运行的docker
`
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
`
然后我的.env文件配置了用户名和密码，
“
REDIS_USER=root
REDIS_PASSWORD='123456'
”
可能没有配置成功。多谢各位的帮助！
