### ISSUE TITLE
[BUG]删除键的 bug

### ISSUE THREAD

**Issue by sunxiatao** [tiny-craft/tiny-rdm#226]
**Tiny RDM Version**
1.1.11

**OS Version**
Windows

**Redis Version**
6

**Describe the bug**
删除键后，显示所选键不存在或未选中任何键，请尝试刷新后重试，然后通过程序再次添加这个键，然后在软件中刷新，右侧还是显示所选键不存在或未选中任何键，请尝试刷新后重试

Steps to Reproduce:

1.删除键
2.通过程序再次添加这个键

**Comment by tiny-craft** [comment]
右键删除还是多选删除，还是匹配删除？

**Comment by sunxiatao** [comment]
就点垃圾桶按钮删除键

**Comment by tiny-craft** [comment]
> 就点垃圾桶按钮删除键

就选中key之后右侧出现的删除按钮是吧？
删除之后它还留在key列表是吗？

**Comment by sunxiatao** [comment]
![PixPin_2024-04-18_13-41-28](https://github.com/tiny-craft/tiny-rdm/assets/58552103/4acb4af1-2fd7-4d9c-ab35-37d5e67ac491)
@tiny-craft

**Comment by sunxiatao** [comment]
> > 就点垃圾桶按钮删除键
> 
> 就选中key之后右侧出现的删除按钮是吧？ 删除之后它还留在key列表是吗？
![PixPin_2024-04-18_13-41-28](https://github.com/tiny-craft/tiny-rdm/assets/58552103/ced6f42e-43c1-43e1-af69-9cfa05131ed1)
@tiny-craft

**Comment by tiny-craft** [comment]
最新版已经修复这个问题
