### ISSUE TITLE
[FEATURE] Windows 安装包可以提供包含 WebView2 的完整版吗？

### ISSUE THREAD

**Issue by xiazhichen24** [tiny-craft/tiny-rdm#228]
非常好的 Redis 客户端，我一开始在我自己的 WIndows 上安装，除了安装的时候感觉慢以外，其它体验都比 Redis Insight 要好，所以我想把公司项目的 Windows Server 2019 上的 Redis Insight 也替换成 Tiny RDM。

遇到的问题是安装完后还需要 WebView2，可问题是服务器是离线的，这意味着我需要去下载 WebView2 的离线安装包并上传到服务器，虽然做一次没什么工作量，但是这对我后续向同事们推荐 Tiny RDM 产生了困难。我要不断跟他们说如果你们的服务器不能联网的话，请同时下载 WebView2 并安装。这个情况就不如 Redis Insight 直接一个安装包丢给他们，不用解释他们就能安装使用。

虽然不带 WebView2 的安装包可以做到很小（11 MB vs Redis Insight 80 MB），但无法保证离线 Windows 也可以直接安装使用。所以我建议提供一个完整安装版，这样即使是没有网络的 Windows 或者网络很慢的 Windows 都可以直接安装使用。

另外，我觉得其实 Windows 可以默认提供完整版的（包含 WebView2），安装文件大的代价比没有网络或者网络慢要去手动下载 WebView2 要小得多，更利于用户间传播。

**Comment by tiny-craft** [comment]
Windows10和11后面的版本是自带webview的，Windows Server可以没有自带，而且Wails也没有提供内嵌webview的打包方式。

而且即使有这种方法，包体加起来比electron自带chrome要更大，已经非常不划算了，兼容性上还不如chrome。不过这个方式后续准备重做的时候会考虑进去。
