### ISSUE TITLE
部分优化建议

### ISSUE THREAD

**Issue by KKKKKKKEM** [tiny-craft/tiny-rdm#23]
首先感谢提供好用的软件，以下是几点建议

1. 希望能支持对多种数据格式的展示的优化，例如 JSON / Text 等等
2. 进入到一个Key 里面之后，如果这个Key 是 Set 之类的， 希望能显示出这个队列一共有多少 Value，也就是有一个 Size 功能
3. 可以快捷的对 Set / hash / Zset / List 里面的 Value 进行复制
4. 过滤键的功能能否支持多个过滤条件呢？

**Comment by haitanghuadeng** [comment]
针对第2点补充一下，不仅仅是Set，还有List、Hash也需要。

**Comment by tiny-craft** [comment]
截至[v1.1.2](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.2)版本，上面说的几条建议基本都添加或改进了，欢迎更新使用~
