### ISSUE TITLE
[BUG] 命令行进行数据写入后乱码，无法写入等问题

### ISSUE THREAD

**Issue by tieing** [tiny-craft/tiny-rdm#231]
平台： windows11
RDM version：v1.1.11
redis version:  v7.0.15

1. 使用set命令设置一个非英文（中文，日文，韩文等）的值。
2. 使用get命令查询成功，但是字符显示乱码。
3. 通过redis-cli工具查询，发现这个值在存入时就已经乱码。并非查询显示问题。
5. 有的字符不支持输入。
6. 以上情况不只存在于 ’get’ 'set' 命令，其他命令也存在这些问题。

![屏幕截图 2024-04-17 104659](https://github.com/tiny-craft/tiny-rdm/assets/29286699/1f943e69-4ed0-4704-9759-912c20f38a72)

**Comment by jksusu** [comment]
平台： mac arm64
RDM version：v1.1.11
redis version: v6.26

同样问题已经复现

**Comment by tiny-craft** [comment]
> 4. 有的字符不支持输入

这个是指哪些字符？还是输入法的问题？

**Comment by tieing** [comment]
字符可能是我电脑输入法问题，一直没重现问题。谢谢

**Comment by tiny-craft** [comment]
试下最新版还有没有这个问题[最新版](https://github.com/tiny-craft/tiny-rdm/releases)
