### ISSUE TITLE
[BUG] Kaspersky detects the app as a malicious object

### ISSUE THREAD

**Issue by ajunior** [tiny-craft/tiny-rdm#233]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.11

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows 11

**Redis Version**
Which version of Redis are you using?

**Describe the bug**
It's not a bug itself. The reason I opened this issue is that Kaspersky is deleting the app because it has been detected as a malicious object.

Steps to Reproduce:

1. Download the executable
2. Install the app

```
Event: Object deleted
Component: Intrusion Prevention
Result description: Deleted
Type: Trojan
Name: Trojan-Dropper.Win32.Agent.tgjugh
Threat level: High
Object path: C:\Users\Junior\Downloads\TinyRDM_Setup_1.1.11_windows_x64.exe//
Object name: tinyrdm.exe
MD5: F62B858ECE07E20DD57F65F485D768CF
```

**Comment by tiny-craft** [comment]
The application packaged by wails will be regarded as a virus by some antivirus software, which I can't solve for the moment. It can only be manually trusted by the user himself, or compiled and installed from the source code.

**Comment by tiny-craft** [comment]
> > The application packaged by wails will be regarded as a virus by some antivirus software, which I can't solve for the moment. It can only be manually trusted by the user himself, or compiled and installed from the source code.
> 
> @tiny-craft @ajunior I have contacted Kaspersky technical support, they confirmed that is a False Positive and will be fixed within 24 hours.

Thank you very much.

**Comment by ajunior** [comment]
> > The application packaged by wails will be regarded as a virus by some antivirus software, which I can't solve for the moment. It can only be manually trusted by the user himself, or compiled and installed from the source code.
> 
> @tiny-craft @ajunior I have contacted Kaspersky technical support, they confirmed that is a False Positive and will be fixed within 24 hours.

I really appreciate it. Thanks!
