### ISSUE TITLE
[FEATURE] 当我缓存的内容较大时，打不开，会报此错误

### ISSUE THREAD

**Issue by webguosai** [tiny-craft/tiny-rdm#234]
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/2c3ea1ff-9595-48e2-a12e-a3ae55d7d9a6)
希望能有一个地方进行设置，能够自定义内容查看的大小
版本v1.1.8

**Comment by tiny-craft** [comment]
这个key是什么类型的，里面的内容是什么格式？大概多大？

**Comment by webguosai** [comment]
> 这个key是什么类型的，里面的内容是什么格式？大概多大？

格式为string 类型，保存的数据是 php 经过`serialize`函数序列化的内容
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/d233ec7f-920e-4fa3-a509-9a4fa7a556b6)

**Comment by tiny-craft** [comment]
[Tiny RDM.exe.zip](https://github.com/tiny-craft/tiny-rdm/files/15032770/Tiny.RDM.exe.zip)

@webguosai 试下这个包还会不会报`Maximum call stack size exceeded`这个错

**Comment by webguosai** [comment]
> [Tiny RDM.exe.zip](https://github.com/tiny-craft/tiny-rdm/files/15032770/Tiny.RDM.exe.zip)
> 
> @webguosai 试下这个包还会不会报`Maximum call stack size exceeded`这个错

ok，这个exe没有报错了，并且能成功预览到内容
还有一个问题是，同样的我的数据是php serialize序列化的内容，预览后是这样乱码的，但我换成`Raw`的查看方式后，数据就能清晰的查看了，所以我在想能不能将这个查看方式，做到设置里面去，让用户自己来选择查看方式，以后打开就都是这个设置的查看方式 @tiny-craft 
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/c73f3a86-2e1b-41a5-9a89-3963ed67c152)

**Comment by tiny-craft** [comment]
> ok，这个exe没有报错了，并且能成功预览到内容 还有一个问题是，同样的我的数据是php serialize序列化的内容，预览后是这样乱码的，但我换成`Raw`的查看方式后，数据就能清晰的查看了，所以我在想能不能将这个查看方式，做到设置里面去，让用户自己来选择查看方式，以后打开就都是这个设置的查看方式 @tiny-craft ![image](https://private-user-images.githubusercontent.com/2083784/323824591-c73f3a86-2e1b-41a5-9a89-3963ed67c152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTkzNDksIm5iZiI6MTcxMzQ5OTA0OSwicGF0aCI6Ii8yMDgzNzg0LzMyMzgyNDU5MS1jNzNmM2E4Ni0yZTFiLTQxYTUtOWE4OS0zOTYzZWQ2N2MxNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDM1NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFlNGFkN2EyODdkYWYzYzhhNDQ2N2QxN2VjNGY0NzgzNzNmOWUzYWZkNDc5M2VkNGY1YTVkMjI4YjkxYWM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G-GD7x8Acoaa5MhVdN2SbDYDAtKOMgAlbL6NNKqFUJ4)

你的Tiny RDM没有php序列化的查看选项吗？它会检查环境变量有没有php，有的话就会出现在解码菜单，也会自动解码。

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/c91d6037-7430-4d06-8796-8b3ede415141)

**Comment by webguosai** [comment]
> > ok，这个exe没有报错了，并且能成功预览到内容 还有一个问题是，同样的我的数据是php serialize序列化的内容，预览后是这样乱码的，但我换成`Raw`的查看方式后，数据就能清晰的查看了，所以我在想能不能将这个查看方式，做到设置里面去，让用户自己来选择查看方式，以后打开就都是这个设置的查看方式 @tiny-craft ![image](https://private-user-images.githubusercontent.com/2083784/323824591-c73f3a86-2e1b-41a5-9a89-3963ed67c152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTkzNDksIm5iZiI6MTcxMzQ5OTA0OSwicGF0aCI6Ii8yMDgzNzg0LzMyMzgyNDU5MS1jNzNmM2E4Ni0yZTFiLTQxYTUtOWE4OS0zOTYzZWQ2N2MxNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDM1NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzFlNGFkN2EyODdkYWYzYzhhNDQ2N2QxN2VjNGY0NzgzNzNmOWUzYWZkNDc5M2VkNGY1YTVkMjI4YjkxYWM0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G-GD7x8Acoaa5MhVdN2SbDYDAtKOMgAlbL6NNKqFUJ4)
> 
> 你的Tiny RDM没有php序列化的查看选项吗？它会检查环境变量有没有php，有的话就会出现在解码菜单，也会自动解码。
> 
> ![image](https://private-user-images.githubusercontent.com/137850705/323827336-c91d6037-7430-4d06-8796-8b3ede415141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDU1NzAsIm5iZiI6MTcxMzUwNTI3MCwicGF0aCI6Ii8xMzc4NTA3MDUvMzIzODI3MzM2LWM5MWQ2MDM3LTc0MzAtNGQwNi04Nzk2LThiM2VkZTQxNTE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNTQxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Njc1ZjM5ZmY4NzM0ZTcwZDNiYzRmMWFhMjA3ZTk4ZGQ5ZWE1YjA1NTkxMTlmYzk5MjZkNDhmNTdkNmIzMDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Q0n8sLsQRuQ1FUNjTasY7NPweBi0yvFiLg86gW5tKA)

按照上面的确实可以将php的反序列转成json，但那只是普通的数据类型，我这边的场景是，在redis中写入的是序列化的类
比如：
```php
require_once __DIR__.'/Abc.php';
$s = serialize(new \Abc());
// 把$s 写入到缓存中
```


- Abc.php
```php
<?php

class Abc
{
    protected $message;
    public function __construct()
    {
        for ($i = 0; $i < 10000; $i++) {
            $this->message .= '我是类';
        }
    }
}

```
写入到缓存后，打开就是这样
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/3e9b51b3-f9e8-4c14-8751-2ec155b7850e)
如果我选`Raw`格式的话，是能看得到反序列后的内容的(这正是我想要的)
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/966f2b14-0b60-4cc8-bd19-e0011524cd41)
如果我很多key都是这种无法自动 `解码/解压方式` 而这时每次都要点开`查看方式`来选择`Raw`，就比较麻烦，所以我想可不可以做到设置里面，默认让我选择查看`Raw`的查看方式，这样是不是就会更好一些呢 @tiny-craft 

![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/8d9cdf39-7454-4ad8-8909-43e852478208)

**Comment by tiny-craft** [comment]
用raw格式，如果包含了无法显示的字符，可能会是乱码。这个我再优化下自动识别的逻辑。

还有我发现打包成正式版后无法没法正常检测系统是否有安装`php`和`python`了，导致有运行环境的用户，`php`和`pickle`解码也都不能用了，这个要查下。这个直接代码运行没有问题，又是个奇怪的问题

**Comment by tiny-craft** [comment]
我先解决掉`php`检测问题，你到时再看解码后的内容是不是完整的。

`raw`格式不一定会显示完整，有些字符是没法显示的。

或者你可以按照官方指南手动创建一个php解码器：https://redis.tinycraft.cc/zh/guide/custom-decoder/

**Comment by tiny-craft** [comment]
`Maximum call stack size exceeded`的问题最新版已经修复
