### ISSUE TITLE
[FEATURE] 建议弹窗均支持ESC进行关闭

### ISSUE THREAD

**Issue by hellcox** [tiny-craft/tiny-rdm#235]
![image](https://github.com/tiny-craft/tiny-rdm/assets/18309773/41cc36fe-960f-4c79-959b-b31684ddf788)

**Comment by tiny-craft** [comment]
会不会误触？我之前有这种困惑

**Comment by hellcox** [comment]
我个人觉得还好，一般不会误触，即便误触了也没啥影响

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经支持绝大部分弹窗使用esc退出
