### ISSUE TITLE
[FEATURE]添加一个前缀搜索功能

### ISSUE THREAD

**Issue by seth-shi** [tiny-craft/tiny-rdm#237]
左上角搜索框前缀或者什么搜索, 可以变化树的结构

**Comment by tiny-craft** [comment]
`*abc`这种？还是`abc*`

**Comment by seth-shi** [comment]
> `*abc`这种？还是`abc*`
![image](https://github.com/tiny-craft/tiny-rdm/assets/28035971/f096dd76-015f-469e-97b7-f82b7990d9dd)
![image](https://github.com/tiny-craft/tiny-rdm/assets/28035971/8ae6de3d-d2d2-4a76-bd3b-4f8c4a7bd670)


看到这个功能了, 但是是在新建数据库的时候选择,
图中两个功能用没分清

**Comment by seth-shi** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/28035971/f954ea34-2743-40fa-99cb-832f15feb046)
 
过滤 key 查看建议像首页数据库那样的过滤? 上面是过滤已经筛选出来的 key, 下面是决定筛选什么 key

**Comment by tiny-craft** [comment]
> ![image](https://private-user-images.githubusercontent.com/28035971/324666234-f954ea34-2743-40fa-99cb-832f15feb046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Mzk2NDgsIm5iZiI6MTcxMzgzOTM0OCwicGF0aCI6Ii8yODAzNTk3MS8zMjQ2NjYyMzQtZjk1NGVhMzQtMjc0My00MGZhLTk5Y2ItODMyZjE1ZmViMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxOWViNTQ0MTM0NzQwNDI2ZDdiMDYyMzRmYTRlYzZhMDI1OTc5ZDFlNGRkNzk0ZTI2ZjA2NGUwNGNhM2U2OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YF9jx5D0KaR6wMp8acz1N4QMzOkoqSrunB1TOtJMVbg)
> 
> 过滤 key 查看建议像首页数据库那样的过滤? 上面是过滤已经筛选出来的 key, 下面是决定筛选什么 key

搞上下两个输入框，太迷惑了，你可以看看相关用户指南，能不能满足你需求 https://redis.tinycraft.cc/zh/guide/filter/

**Comment by seth-shi** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/28035971/dd94355d-65a5-41c5-8a34-0a03a96480f4)

很不错, 建议在这里增加一句话: 输入是过滤, 按下回车是查找. 好的产品可以不用看文档的.
1. 再提个点, 按下回车之后, 可以底下的进度条加一个批次 ( 比如是第几批查询中 )
