### ISSUE TITLE
[BUG]集群下无法启用订阅功能

### ISSUE THREAD

**Issue by lin-tree** [tiny-craft/tiny-rdm#239]
**Tiny RDM Version**
1.1.11 Portable

**OS Version**
Windows 10 专业版 22H2 19045.4291

**Redis Version**
5.0.8 linux 集群 三主三从

**Describe the bug**
配置为redis集群时，集群下无法开启订阅。
使用 redisinsight 测试过集群，排除了集群的问题。

Steps to Reproduce:

1. 常规配置下连接地址填入某个master节点（内网192.168网段 6379端口），不配密码，集群模式勾选当前为集群节点
2. 连接成功切换到 **发布/订阅** tab，输入频道 test 点击 **开启订阅** ，报错 create redis client fail
![图片](https://github.com/tiny-craft/tiny-rdm/assets/18462798/bf94a4ba-6bc7-48f3-b937-addecb1bad76)

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经修复了集群模式下的订阅，可以试下

**Comment by lin-tree** [comment]
> [最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经修复了集群模式下的订阅，可以试下

可以啦，感谢~
