### ISSUE TITLE
分组下添加第二个链接的时候， 报链接异常

### ISSUE THREAD

**Issue by lifaxin** [tiny-craft/tiny-rdm#24]

**Comment by lifaxin** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/100394261/65b5f578-56b6-4ec6-a245-4dc8bb3cddf0)

**Comment by tiny-craft** [comment]
@lifaxin 我在Windows和Mac上都没法重现，有没有具体的复现步骤。或者说是连接名/分组名用了比较特殊的字符之类的

**Comment by tiny-craft** [comment]
@lifaxin 这个问题我复现了，最新版看下还有没有问题
