### ISSUE TITLE
[BUG] 升级到 1.1.12打开客户端后是白板

### ISSUE THREAD

**Issue by HappyDadGITHUB** [tiny-craft/tiny-rdm#241]
**Tiny RDM Version**
1.1.12

**OS Version**

Mac 11.6.3

**Redis Version**
Which version of Redis are you using?

**Describe the bug**
升级到 1.1.12打开客户端后是白板
<img width="1791" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/164606296/247eafd6-68aa-4d2a-b8ce-a4939d3c4c60">

**Comment by tiny-craft** [comment]
`1.1.11`没问题吗

**Comment by binglww** [comment]
@tiny-craft 1.1.11没有白屏，1.1.12打开是白的，macos 11.2.3

**Comment by tiny-craft** [comment]
> @tiny-craft 1.1.11没有白屏，1.1.12打开是白的，macos 11.2.3

Intel芯片是吗

**Comment by binglww** [comment]
> > @tiny-craft1.1.11没有白屏，1.1.12打开是白屏的，macos 11.2.3
> 
> 英特尔芯片是吗

是的

**Comment by tiny-craft** [comment]
> > > @tiny-craft1.1.11没有白屏，1.1.12打开是白屏的，macos 11.2.3
> > 
> > 
> > 英特尔芯片是吗
> 
> 是的

[Tiny RDM.zip](https://github.com/tiny-craft/tiny-rdm/files/15144876/Tiny.RDM.zip)
试下这个包会不会，我怀疑又是Monaco Editor的锅

**Comment by binglww** [comment]
> > > > @tiny-craft1.1.11没有白屏，1.1.12打开是白屏的，macos 11.2.3
> > > 
> > > 
> > > 英特尔芯片是吗
> > 
> > 
> > 是的
> 
> [Tiny RDM.zip](https://github.com/tiny-craft/tiny-rdm/files/15144876/Tiny.RDM.zip) 试下这个包会不会，我怀疑又是Monaco Editor的锅

这个可以正常使用，就是打开会白3s左右

**Comment by tiny-craft** [comment]
> 这个可以正常使用，就是打开会白3s左右

那确实是Monaco Editor新版本又开始不兼容旧的macos了，我晚点替换下`1.1.12`的包
白3s应该是加载界面吧，中间会有个红色转圈加载指示的，没有吗？

**Comment by binglww** [comment]
> > 这个可以正常使用，就是打开会白3s左右
> 
> 那确实是Monaco Editor新版本又开始不兼容旧的macos了，我晚点替换下`1.1.12`的包 白3s应该是加载界面吧，中间会有个红色转圈加载指示的，没有吗？

打开显示页面全白，3s后红色loading一闪而过，然后界面显示淡入显示出来

https://github.com/tiny-craft/tiny-rdm/assets/45476065/ae76407d-3da7-40e0-9e8a-aff0c2f91375

**Comment by tiny-craft** [comment]
> > > 这个可以正常使用，就是打开会白3s左右
> > 
> > 
> > 那确实是Monaco Editor新版本又开始不兼容旧的macos了，我晚点替换下`1.1.12`的包 白3s应该是加载界面吧，中间会有个红色转圈加载指示的，没有吗？
> 
> 打开显示页面全白，3s后红色loading一闪而过，然后界面显示淡入显示出来
> 
>  2024-04-29.11.30.36.mov

[1.1.12](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.1.12/TinyRDM_1.1.12_mac_intel.dmg)我已经重新打包了一个，可以下载这个看看。

你视频里怎么感觉这么卡，而且布局还错位了😂

**Comment by binglww** [comment]
> > > > 这个可以正常使用，就是打开会白3s左右
> > > 
> > > 
> > > 那确实是Monaco Editor新版本又开始不兼容旧的macos了，我晚点替换下`1.1.12`的包 白3s应该是加载界面吧，中间会有个红色转圈加载指示的，没有吗？
> > 
> > 
> > 打开显示页面全白，3s后红色loading一闪而过，然后界面显示淡入显示出来
> > 2024-04-29.11.30.36.mov
> 
> [1.1.12](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.1.12/TinyRDM_1.1.12_mac_intel.dmg)我已经重新打包了一个，可以下载这个看看。
> 
> 你视频里怎么感觉这么卡，而且布局还错位了😂

电脑并不卡，也不知道为啥哪么慢，你刚发的这个试了还是一样（打开显示页面全白，3s后红色loading一闪而过），icon位置也是乱的，但是我用另外一个电脑试了，打开和界面显示都是正常的，可能还是我这个电脑的问题，系统版本比较旧😂
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/3d5287b3-9f86-4836-b222-d7ee5748b946)
![image](https://github.com/tiny-craft/tiny-rdm/assets/45476065/e2b8e59e-4aa0-41fb-8cc4-81682b29adb5)

**Comment by tiny-craft** [comment]
> 电脑并不卡，也不知道为啥哪么慢，你刚发的这个试了还是一样（打开显示页面全白，3s后红色loading一闪而过），icon位置也是乱的，但是我用另外一个电脑试了，打开和界面显示都是正常的，可能还是我这个电脑的问题，系统版本比较旧😂 ![image](https://private-user-images.githubusercontent.com/45476065/326325596-3d5287b3-9f86-4836-b222-d7ee5748b946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjI4MTYsIm5iZiI6MTcxNDM2MjUxNiwicGF0aCI6Ii80NTQ3NjA2NS8zMjYzMjU1OTYtM2Q1Mjg3YjMtOWY4Ni00ODM2LWIyMjItZDdlZTU3NDhiOTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAzNDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzViYWMzNGRiNzUzZWMzMDg1ODVmMDMwZjAxZTBlYmMyZDZjZjQ5MjYxMWNmMjYwMzRkNjI3Mzg2ZmNkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hueSDLi8EDGx7c818QovZBlTyuaZIFH-uabhsMb3mBo) ![image](https://private-user-images.githubusercontent.com/45476065/326325615-e2b8e59e-4aa0-41fb-8cc4-81682b29adb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjI4MTYsIm5iZiI6MTcxNDM2MjUxNiwicGF0aCI6Ii80NTQ3NjA2NS8zMjYzMjU2MTUtZTJiOGU1OWUtNGFhMC00MWZiLThjYzQtODE2ODJiMjlhZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAzNDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZjlmNDg0YjljMmU1ZDkxZjQwMmU0ZTQyNzE0OTE4YzE4YmMwYmEyZDNmNmNjNTQwNmRmMGI3ZmU4MDVmZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzEvPSowmJdgKKD_Rp7XGQjLpncyHKmQ1d5Tpkix1fQ)

是系统太久，webkit兼容性不太好导致的。之前是10.x有这个问题的，没想到11也有。
这个版本的版本号写入有问题，估计晚点还得改

**Comment by tiny-craft** [comment]
这个问题已经修复了，重新下载[v1.1.12](https://github.com/tiny-craft/tiny-rdm/releases)版本的安装包即可

**Comment by houzs1024** [comment]
@tiny-craft  老师，白屏问题有解决吗？

**Comment by tiny-craft** [comment]
> [@tiny-craft](https://github.com/tiny-craft) 老师，白屏问题有解决吗？

要不要尝试下重写版本[Redisee - https://redisee.com](https://redisee.com)，使用Avalonia重做，webkit的坑不想趟了，我尽量兼容mac 11.x，手上好像没这个版本的机器😂
