### ISSUE TITLE
[FEATURE] 点击左边key时，右边应当刷新显示

### ISSUE THREAD

**Issue by webguosai** [tiny-craft/tiny-rdm#242]
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/88073641-46e2-46ca-b9db-6842373205a9)
在点击某个左侧的key，显示右侧内容后，重复点击这个左侧的key应该刷新右侧的显示(现在不会再刷新，除非点了其它的key,才会刷新)，请作者优化这个体验吧 @tiny-craft

**Comment by tiny-craft** [comment]
这样的话如果双击三击可能会导致很多不必要的刷新。`F5`和`CDM+R`现在可以刷新

**Comment by webguosai** [comment]
可以支持双击刷新吗

**Comment by tiny-craft** [comment]
> 可以支持双击刷新吗

这个好像确实可以考虑，不过属于隐藏操作，估计就只有你和我知道啊😂

**Comment by webguosai** [comment]
我觉得可以加(对于我这种强迫症患者来说😂)

**Comment by tiny-craft** [comment]
行，我再想想。这个双击本来是想留给多标签使用的。

**Comment by tiny-craft** [comment]
最新版改为，重复点击同一个已选中的key，间隔1秒以上会重新刷新
