### ISSUE TITLE
[FEATURE]好像用不了help

### ISSUE THREAD

**Issue by xzhhh425** [tiny-craft/tiny-rdm#244]
![image](https://github.com/tiny-craft/tiny-rdm/assets/74334875/f6621175-eaaa-4763-9a6c-97088e2646e0)

**Comment by tiny-craft** [comment]
Redis Command里面没有`Help`这个命令喔：https://redis.io/docs/latest/commands/

**Comment by xzhhh425** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/74334875/7946e409-33d3-453a-8399-e11f6949a35c)
啊这，可是我在命令行可以敲出来:monocle_face:

**Comment by tiny-craft** [comment]
> ![image](https://private-user-images.githubusercontent.com/74334875/326649546-7946e409-33d3-453a-8399-e11f6949a35c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDU0MTQsIm5iZiI6MTcxNDQ0NTExNCwicGF0aCI6Ii83NDMzNDg3NS8zMjY2NDk1NDYtNzk0NmU0MDktMzNkMy00NTNhLTgzOTktZTExZjY5NDlhMzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAyNDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDJmOWNmODhkOGY1ZWZkNGM2YTA0MjQ2NjYyOTAxODkyMDFmODZlNjM0YzE1MTYwZGNkMDhjM2JkMDE1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jXgzFO3QLxflgs7dK91rSavKnmqR5QEaH6-WZoddTVA) 啊这，可是我在命令行可以敲出来:monocle_face:

那估计这只是redis-cli命令，redis通讯里面不支持。不过命令帮助有考虑在未来加上

**Comment by xzhhh425** [comment]
麻烦了
