### ISSUE TITLE
[BUG] 复制值提示复制到剪切板，实际没复制上

### ISSUE THREAD

**Issue by LTQ1995** [tiny-craft/tiny-rdm#246]
Tiny RDM Version
1.1.12

OS Version
macOS Sonoma  版本14.4.1 (23E224)

Describe the bug
1. 复制值提示复制到剪切板，实际没复制上

**Comment by tiny-craft** [comment]
是点哪个按钮还是快捷键

**Comment by ydq** [comment]
> 是点哪个按钮还是快捷键

@tiny-craft  测试下来应该是值包含中文的时候无法复制，复制的内容为空，但如果不包含中文的时候是可以正常复制的

**Comment by tiny-craft** [comment]
最新版已经可以复制带有中文的值
