### ISSUE TITLE
[BUG]为什么macbook打开tiny-rdm工具会弹出安装python3

### ISSUE THREAD

**Issue by PrAyttt** [tiny-craft/tiny-rdm#247]
**Tiny RDM Version**
What version of Tiny RDM are you using?

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

**Redis Version**
Which version of Redis are you using?

**Describe the bug**

Steps to Reproduce:

1.
2.
<img width="1024" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/99107143/ca837a80-b168-4c0c-8413-5bc9ac85ae1f">
<img width="969" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/99107143/0cb34845-4bce-4882-93cf-9de9bd4fedf0">
<img width="500" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/99107143/eec575f1-36f6-4787-9435-046ba47f3058">

**Comment by tiny-craft** [comment]
客户端现在是什么版本。启动的时候会尝试检查有没有安装python而决定要不要把`pickle`解码也列出来。
之前有用户反馈，当时用的是调用命令`python --version`来检查。后面改为go内置函数来查询python安装路径，问了提issue的人没回复我了。如果你不是最新版，试下最新版还会不会这样提示。如果还有我看看其他解决方法。

**Comment by PrAyttt** [comment]
我昨天刚下的，最新版本

**Comment by tiny-craft** [comment]
> 我昨天刚下的，最新版本

查了下是因为没装`xcode-select`就会导致这样提示。但是如果不装`xcode-select`我又没法编译这个应用了。所以没法调试，只能再想下其他办法了。

**Comment by tiny-craft** [comment]
> > 我昨天刚下的，最新版本
> 
> 查了下是因为没装`xcode-select`就会导致这样提示，它提示的是安装`命令行开发者工具`，而不是`python3`。

但是如果不装`xcode-select`我又没法编译这个应用了，所以没法调试。你也可以点确认安装xcode-select，一般开发者都需要这个环境😂，不然等新版本我看有没有别的办法去掉这个检查了。

**Comment by PrAyttt** [comment]
xcode-select我安装了的，只是系统有两个python版本很烦，就把xcode里面的python3删了

**Comment by tiny-craft** [comment]
> xcode-select我安装了的，只是系统有两个python版本很烦，就把xcode里面的python3删了

你是这么删除xcode的Python3的，强行删除`/usr/bin/python3`这个文件吗？

**Comment by tiny-craft** [comment]
Duplicate of #201

**Comment by tiny-craft** [comment]
请问最新版还会不会弹这个提示

**Comment by PrAyttt** [comment]
没有了哦大佬，感谢更新，之前老是弹窗就没有用，你不回复issue我都忘记更新了
