### ISSUE TITLE
[BUG]在连接到redis后，切换db后，右侧栏【命令行】点击进去还是db0

### ISSUE THREAD

**Issue by shadowlaser** [tiny-craft/tiny-rdm#249]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.12

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
win11
**Redis Version**
Which version of Redis are you using?
5.2.0
**Describe the bug**
在连接到redis后，点击左下侧db列表，选择非db0进行切换，右侧栏【命令行】点击进去还是db0

不确定是不是问题还是设计如此，感谢

**Comment by tiny-craft** [comment]
键浏览器和命令行两个区域目前是独立不同步的

**Comment by shadowlaser** [comment]
> 键浏览器和命令行两个区域目前是独立不同步的

了解，这个算是没有这个功能的
