### ISSUE TITLE
[BUG]hash key中一条记录点击编辑之后记录显示高度会被撑开

### ISSUE THREAD

**Issue by shadowlaser** [tiny-craft/tiny-rdm#250]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.12
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
win11
**Redis Version**
Which version of Redis are you using?
5.2.0
**Describe the bug**
1. 选择一个有多个字段的hash键
2. 选择其中一条记录，点击右侧编辑，然后直接点击【x】关闭

hash键的固定高度，会被值撑开，记录中的值从之前的超过长度隐藏显示成全部显示

Steps to Reproduce:

1.
4.

**Comment by tiny-craft** [comment]
因为选中之后，里面的内容被自动识别了。所以所有值都会按识别的格式进行重新格式化显示。可以在左下角手动重新改为`Raw`格式，这个key对应的内容在本地连接中就会一直使用手动选择的格式

**Comment by shadowlaser** [comment]
> 因为选中之后，里面的内容被自动识别了。所以所有值都会按识别的格式进行重新格式化显示。可以在左下角手动重新改为`Raw`格式，这个key对应的内容在本地连接中就会一直使用手动选择的格式

了解，不过这是大佬你说的它为什么会显示成这样，也就是这个现象的产生的原因
这个是不是你这边期望的设计？

**Comment by tiny-craft** [comment]
> 了解，不过这是大佬你说的它为什么会显示成这样，也就是这个现象的产生的原因 这个是不是你这边期望的设计？

原本就是为了让它能把自动识别后的内容也在列表中直接显示。你说的情况只是因为这些内容多了换行，而导致这一格被撑开了。我看看再怎么优化下，内容中换行太多的时候确实不友好

**Comment by shadowlaser** [comment]
> > 了解，不过这是大佬你说的它为什么会显示成这样，也就是这个现象的产生的原因 这个是不是你这边期望的设计？
> 
> 原本就是为了让它能把自动识别后的内容也在列表中直接显示。你说的情况只是因为这些内容多了换行，而导致这一格被撑开了。我看看再怎么优化下，内容中换行太多的时候确实不友好

加油！无论格式是啥，这边的列表高度应该都不应该撑开，对着

**Comment by witt-bit** [comment]
> > 了解，不过这是大佬你说的它为什么会显示成这样，也就是这个现象的产生的原因 这个是不是你这边期望的设计？
> 
> 原本就是为了让它能把自动识别后的内容也在列表中直接显示。你说的情况只是因为这些内容多了换行，而导致这一格被撑开了。我看看再怎么优化下，内容中换行太多的时候确实不友好

上个版本是右边开侧边栏再格式化，列表就是Raw
