### ISSUE TITLE
[BUG]不支持使用IPv6连接

### ISSUE THREAD

**Issue by q7164518** [tiny-craft/tiny-rdm#251]
**Tiny RDM Version**
v1.1.12

**OS Version**
Windows11

**Redis Version**
7.2.4

**Describe the bug**
使用IPv6地址无法连接

![image](https://github.com/tiny-craft/tiny-rdm/assets/22828478/ee75fe2c-dfcf-4826-b649-7a30e73985f6)

**Comment by tiny-craft** [comment]
这个我确实没试过，不过看官方仓库，貌似go-redis还不支持ipv6：https://github.com/redis/go-redis/issues/2978

你可以试下ssh能不能连上，然后再在远程服务器本地登录redis服务

**Comment by q7164518** [comment]
> 这个我确实没试过，不过看官方仓库，貌似go-redis还不支持ipv6：[redis/go-redis#2978](https://github.com/redis/go-redis/issues/2978)
> 
> 你可以试下ssh能不能连上，然后再在远程服务器本地登录redis服务

这个问题倒是不大. 我可以用ipv4连接, 只是这个还是要支持下最好. 关了吧, 谢谢

**Comment by tiny-craft** [comment]
> > 这个我确实没试过，不过看官方仓库，貌似go-redis还不支持ipv6：[redis/go-redis#2978](https://github.com/redis/go-redis/issues/2978)
> > 你可以试下ssh能不能连上，然后再在远程服务器本地登录redis服务
> 
> 这个问题倒是不大. 我可以用ipv4连接, 只是这个还是要支持下最好. 关了吧, 谢谢

嗯，驱动支持的话到时直接填地址就可以了
