### ISSUE TITLE
[FEATURE] 键详情列表的显示格式 与 行编辑的显示格式 可以分开配置就好了

### ISSUE THREAD

**Issue by beanyim** [tiny-craft/tiny-rdm#253]

**Comment by tiny-craft** [comment]
你说的是打开行编辑之后被自动识别，但是不影响hash列表上所用显示的格式是吧？

**Comment by beanyim** [comment]
是的，现在对hash结构进行行编辑选择显示格式后，退出行编辑，列表的显示格式也随之变化，导致数据量大的时候，会等待渲染卡顿

**Comment by tiny-craft** [comment]
> 是的，现在对hash结构进行行编辑选择显示格式后，退出行编辑，列表的显示格式也随之变化，导致数据量大的时候，会等待渲染卡顿

这个问题昨天提交中(70354c14ec463390863a8ff6c51f6a9182b16627)已经修改了，确实大批量格式化显示会导致复杂结构有严重性能问题，而且还可能不美观，下个版本会一同更新。

**Comment by beanyim** [comment]
> > 是的，现在对hash结构进行行编辑选择显示格式后，退出行编辑，列表的显示格式也随之变化，导致数据量大的时候，会等待渲染卡顿
> 
> 这个问题昨天提交中([70354c1](https://github.com/tiny-craft/tiny-rdm/commit/70354c14ec463390863a8ff6c51f6a9182b16627))已经修改了，确实大批量格式化显示会导致复杂结构有严重性能问题，而且还可能不美观，下个版本会一同更新。

好，我关闭问题
