### ISSUE TITLE
[FEATURE] 希望扩大树状图中条目的选择范围

### ISSUE THREAD

**Issue by z-hanzhe** [tiny-craft/tiny-rdm#255]
我不清楚其他人的使用体验是什么样的，我个人很讨厌这种鼠标点空的感觉，希望能优化一下

![screenshots](https://github.com/tiny-craft/tiny-rdm/assets/58802604/e1a5134e-f021-4a64-9ae1-b0f33889e8f4)

**Comment by tiny-craft** [comment]
这个可以有
