### ISSUE TITLE
help to connect upstash

### ISSUE THREAD

**Issue by superlbr** [tiny-craft/tiny-rdm#256]
hi, upstash is a online redis service, https://console.upstash.com/redis

don't know how to connect in tiny-rdm, here's upstash connect example

use redis-cli
```
redis-cli --tls -u redis://default:****@apn1-eminent-gull-34340.upstash.io:34340
```
use javascript
```
import { Redis } from '@upstash/redis'

const redis = new Redis({
  url: 'https://apn1-eminent-gull-34340.upstash.io',
  token: '********',
})

const data = await redis.set('foo', 'bar');
```

**Comment by tiny-craft** [comment]
@superlbr **You should enable `SSL/TLS`, here is an example connection to upstash.**

<img width="617" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/49aedad7-772a-42a5-b218-34e1196a535a">
<img width="619" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/125b1f2a-bac4-497c-b984-faabca975641">

**Comment by tiny-craft** [comment]
Or you can copy the code in `Go` tab, select the URL part which like `rediss://default:Abzod,euDFiOWJjODgzNTg2N2U0OGQzYTlmZTViOW,IDWU3OWRhN3AxNDgzNzg@flexible-polecat-12378.upstash.io:6379`

<img width="992" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/6d2b99eb-2f4e-443c-9387-178c7741de49">

and then `Add Connection`-> `Parse URL from Clipboard`

<img width="630" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/6e6d3e7c-1f99-4150-90d6-45ae2268a833">

**Comment by superlbr** [comment]
many thanks
