### ISSUE TITLE
[FEATURE] 不支持 Command + W 关闭窗口

### ISSUE THREAD

**Issue by GiaoGiaoCat** [tiny-craft/tiny-rdm#258]
**Tiny RDM Version**
1.1.12

**OS Version**
MacOS ARM

Describe the bug
在主界面无法通过系统通用快捷键 Command + W 关闭主程序窗口，以实现让程序仅出现在 Docker 栏的目的。必须要点 MacOS 系统下通用的左上角的红色关闭小圆点，来关闭程序主界面，操作习惯与 MacOS 生态不统一。
当连接上 Redis 客户端的时候，也无法用快捷键 Command + W 关闭内部窗口，必须点击窗口的 X 才能关闭掉。

**Comment by GiaoGiaoCat** [comment]
是的。但 Tiny 的问题是：应用级别 `Command+W` 没有触发任何行为。我的系统上在 Tiny 处于激活状态的情况下 `Command+W`  有声音提示，可能是触发了 Tiny 应用的其它动作。

**Comment by tiny-craft** [comment]
最新版已经支持快捷键关闭标签页窗口
