### ISSUE TITLE
[BUG]添加key 显示bug

### ISSUE THREAD

**Issue by kar-aoyama** [tiny-craft/tiny-rdm#259]
**Tiny RDM Version**
main分支的wails dev 启动

**OS Version**
windows10 专业版

**Redis Version**
redis 7

**Describe the bug**
添加key，显示bug

Steps to Reproduce:

1. 打开连接，默认db0  添加数据，选中db1
2. db0也会出现这个key，点击key 会出现key not exists
![1715928418240](https://github.com/tiny-craft/tiny-rdm/assets/43236429/8093f26a-1d6d-40e9-8d75-773e50c90c0a)

**Comment by tiny-craft** [comment]
你这个类型图标是`N`的状态，是不是在db0的时候就是这样了。还是从db0切换到db1的时候，这个key还没加进去

**Comment by kar-aoyama** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/43236429/448ec447-151f-48c4-8c25-be30bd44bce4)


> 你这个类型图标是`N`的状态，是不是在db0的时候就是这样了。还是从db0切换到db1的时候，这个键还没有加进去
我把db1重置了，在db0添加键str选中db1, db0会出现这个为N的key，db1也会显示一个key

**Comment by tiny-craft** [comment]
> ![image](https://private-user-images.githubusercontent.com/43236429/331914741-448ec447-151f-48c4-8c25-be30bd44bce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzE4NjUsIm5iZiI6MTcxNjE3MTU2NSwicGF0aCI6Ii80MzIzNjQyOS8zMzE5MTQ3NDEtNDQ4ZWM0NDctMTUxZi00OGM0LThjMjUtYmUzMGJkNDRiY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAyMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNDFkZjYzMzMyYTg2NjE0MzAwOTBkNWM2YmI3NTlhN2RiNTJiNzgyMGY0NTM2MWQ5MzJhNzkyNzRmNWE3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.civs-jPg8KzuR8UH3rwKiLVRl4EhtDWO36sovG-0obc)
> 
> 我把db1重置了，在db0添加键str选中db1, db0会出现这个为N的key，db1也会显示一个key

重置是指清空db1所有数据？

**Comment by kar-aoyama** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/43236429/331914741-448ec447-151f-48c4-8c25-be30bd44bce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzE4NjUsIm5iZiI6MTcxNjE3MTU2NSwicGF0aCI6Ii80MzIzNjQyOS8zMzE5MTQ3NDEtNDQ4ZWM0NDctMTUxZi00OGM0LThjMjUtYmUzMGJkNDRiY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAyMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNDFkZjYzMzMyYTg2NjE0MzAwOTBkNWM2YmI3NTlhN2RiNTJiNzgyMGY0NTM2MWQ5MzJhNzkyNzRmNWE3OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.civs-jPg8KzuR8UH3rwKiLVRl4EhtDWO36sovG-0obc)
> > 我把db1重置了，在db0添加键str选中db1，db0会出现这个为N的键，db1也显示一个键
> 
> 重置是指清空db1所有数据？

是的，但是添加key的时候 db0和db1都会显示有，如上图
