### ISSUE TITLE
[FEATURE]子查看 hash 子字段时候，也添加刷新按钮

### ISSUE THREAD

**Issue by ctfang** [tiny-craft/tiny-rdm#260]
当前必须要要点击刷新后，不同步编辑行窗口的内容

**Comment by tiny-craft** [comment]
这里会有个体验上的问题。如果某次刷新这个子字段不存在，那在界面上是即时删除它，还是保留它呢。
如果即时删除它，那下次它再次存在，这时候界面列表里面已经找不到它了
如果保留它，那它如果将来也不会再存在，这就是一个虚假存在的数据
---
这个可以讨论下

**Comment by ctfang** [comment]
按钮放到子页面的窗口，按钮名称是：重新载入。 那么有什么理由保留它的。

这个场景在于复杂的 hash 结构中，子字段也是一个 json 值，那么调试过程经常需要刷新和观察它变化

**Comment by tiny-craft** [comment]
最新版1.1.13已经支持单字段刷新。如果字段不存在或者刷新失败，这一行数据会加上删除线。下次再次刷新如果成功会移除删除线
