### ISSUE TITLE
[FEATURE] 命令行可以默认使用redis-cli吗

### ISSUE THREAD

**Issue by webguosai** [tiny-craft/tiny-rdm#261]
redis-cli 会有命令补全提示，会更友好一些
![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/aa226f45-ddce-4ee8-b164-f2eea1d509b7)

![image](https://github.com/tiny-craft/tiny-rdm/assets/2083784/5844ab2a-ea9e-4bbc-bdb0-d65c439713bf)

**Comment by tiny-craft** [comment]
目前没办法调用redis-cli。而且用户的电脑上不一定就装有redis

**Comment by webguosai** [comment]
好吧
