### ISSUE TITLE
[FEATURE] Stream数据结构Value列宽度不够

### ISSUE THREAD

**Issue by Awadabang** [tiny-craft/tiny-rdm#263]
![image](https://github.com/tiny-craft/tiny-rdm/assets/49111776/f101a261-201e-4f6e-8374-285532823699)
建议加入列宽限制强制换行

**Comment by tiny-craft** [comment]
列头上可以通过鼠标拖动调整宽度

**Comment by Awadabang** [comment]
宽度拉到最大还是放不下；而且没有横向滚动条，想看全了只能copy出来

**Comment by tiny-craft** [comment]
行，我看下怎么调整

**Comment by tiny-craft** [comment]
最新版已经加入自动换行
