### ISSUE TITLE
[FEATURE] 显示可以从居中对齐切换为左对齐

### ISSUE THREAD

**Issue by doglex** [tiny-craft/tiny-rdm#264]
![1x](https://github.com/tiny-craft/tiny-rdm/assets/7918755/213206d1-0871-419b-974e-25c7c8d1e29b)

如图，因为每行开头都是时间戳，
左对齐，从上往下查找数据会方便一些

**Comment by tiny-craft** [comment]
这个后面看看要不要加个可以切换对齐方式的选项

**Comment by tiny-craft** [comment]
最新版已经增加文本对齐选项
