### ISSUE TITLE
[BUG] 自定义解码  TypeError: e is not iterable

### ISSUE THREAD

**Issue by wxip** [tiny-craft/tiny-rdm#266]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.13
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows
**Redis Version**
Which version of Redis are you using?
7.2.4
**Describe the bug**
偏好设置-自定义解码
添加一个解码器,运行参数为空,保存
再次点开自定义解码,报错
![image](https://github.com/tiny-craft/tiny-rdm/assets/25923931/2788756c-1b45-4510-b2b7-657d8e675792)

**Comment by wxip** [comment]
数据重置后恢复正常,可能是历史数据问题

**Comment by tiny-craft** [comment]
最新版已经修复这个问题
