### ISSUE TITLE
[FEATURE]希望查询时，后台自动给查询词前后加上*，否则每次查询都要手动加上*

### ISSUE THREAD

**Issue by NB611** [tiny-craft/tiny-rdm#269]
希望查询时，后台自动给查询词前后加上*，否则每次查询都要手动加上*

**Comment by tiny-craft** [comment]
你说的是这么吗

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/4329075d-225b-4a0c-b249-d82089ae9d88)

**Comment by tiny-craft** [comment]
太长时间没有回复了，这个查询是会自动加上前后缀`*`的，除非选中了`完全匹配`，你可能没有按下回车，所以没有进入条件查询状态，而是在输入筛选状态。

如果相关问题还是没有解决，我再重开issue

**Comment by NB611** [comment]
可能是默认只加载了部分key。没选中完全匹配，不加*查不出来，但是加了*可以查出来

**Comment by tiny-craft** [comment]
> 可能是默认只加载了部分key。没选中完全匹配，不加_查不出来，但是加了_可以查出来

是集群之类的吗

**Comment by NB611** [comment]
是单机部署

**Comment by tiny-craft** [comment]
> 是单机部署

如果结果特别多，也是会分段加载的。因为是无序的，所以不保证第一次查出来的就是你想要的。要么缩小查询范围，要么加载全部看看。

如果加载全部都没有，但是你加了`*`又能出现的。可以把key名和查询条件给我，我再试试看
