### ISSUE TITLE
redis的config命令重命名后，无法正常使用

### ISSUE THREAD

**Issue by MACDfree** [tiny-craft/tiny-rdm#27]
处于安全考虑，我们公司默认的redis部署包会将FLUSHALL、CONFIG、EVAL进行重命名。这会导致tiny-rdm连接时就报错。

```
(error) ERR unknown command `config`, with args beginning with: `get`, `databases`,
```

**Comment by MACDfree** [comment]
不知道这种情况是否普遍。建议可以在连接的高级设置中增加命令的重命名配置。

**Comment by tiny-craft** [comment]
@MACDfree 最新版config命令失败会默认当成16个数据库，看下能不能正常使用。至于命令别名后续会考虑添加配置

**Comment by MACDfree** [comment]
可以正常使用了。很好用、很漂亮的工具！
