### ISSUE TITLE
[BUG] JSON数据没有格式化

### ISSUE THREAD

**Issue by QingYiShiDeCha** [tiny-craft/tiny-rdm#271]
# 数据没有格式化

1.
![image](https://github.com/tiny-craft/tiny-rdm/assets/53112705/a401b183-041d-46ad-8cc8-41a71ecf4ad5)

2.

**Comment by tiny-craft** [comment]
这段JSON发文本我测试下

**Comment by QingYiShiDeCha** [comment]
***@***.******@***.******@***.******@***.******@***.******@***.******@***.***":"com.humen.common.domain.entity.UmsRole","creator":"admin","deleted":0,"id":2L,"roleLabel":"normal","roleName":"普通角色","sort":2,"status":0,"updater":"admin"}],"sex":0,"status":0,"updater":"admin","username":"qingcha"},"token":"1bbe6c40ae714c07b67954363f835819","username":"qingcha"}

&nbsp;


爱在离别时
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 晚上6:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tiny-craft/tiny-rdm] [BUG] JSON数据没有格式化 (Issue #271)














 
这段JSON发文本我测试下

**Comment by tiny-craft** [comment]
邮件回复乱码了哦

**Comment by wxip** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/25923931/c9bc81e5-751f-4bd6-8dde-1689be93eee5)
json格式不对吧,2L这种不应该出现的

**Comment by tiny-craft** [comment]
@QingYiShiDeCha 你这个是什么版本，我最新版的大概试了你的格式，没有问题。还是我这里和你给的例子结构还不太一样？

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/dde2690f-ed25-4d1b-a502-b9e8774f876f)

**Comment by tiny-craft** [comment]
太长时间没回复了，试下最新版如果还是不能格式化你的JSON，欢迎把文本内容发出来重开issue
