### ISSUE TITLE
[FEATURE]命令行HOME、END、鼠标点击指定位置以及和SHIFT按键配合选中的功能不可用。

### ISSUE THREAD

**Issue by tinylit** [tiny-craft/tiny-rdm#273]

**Comment by tiny-craft** [comment]
`Home`和`End`最新版已经支持，中键暂不打算支持。Shift键有哪些常用操作？

**Comment by tinylit** [comment]
> `Home`和`End`最新版已经支持，中键暂不打算支持。Shift键有哪些常用操作？

按着 **SHIFT** 键，可以选中内容，如果按着 **SHIFT** 键，点击文本内容；在光标位置，**SHIFT** + **←** 可以向左逐个选中字符，**SHIFT** + **→** 可以向右逐个选中字符；**SHIFT** + **↑** 可以就当前光标位置，向上选中和当前光标位置垂直对齐（有可能因为字符不同不能对齐，有需要就近处理的可能），逐行向上选中内容，**SHIFT** + **↓** 同理向下逐行选中；**SHIFT** + **HOME** 选中当前光标到最前的所有字符；**SHIFT** + **END** 选中当前光标到最后的所有字符；以上是我常用的内容选中快键键，希望能被采纳，谢谢！

**Comment by tinylit** [comment]
> > 已更新，谢谢支持！！按着 **SHIFT** 键，可以选中内容，如果按着 **SHIFT** 键，点击文本内容；在光标位置，**SHIFT** + **←** 可以向左逐个选中字符，**SHIFT** + **→** 可以向右逐个选中字符；**SHIFT** + **↑** 可以就当前光标位置，向上选中和当前光标位置垂直对齐（有可能因为字符不同不能对齐，有需要就近处理的可能），逐行向上选中内容，**SHIFT** + **↓** 同理向下逐行选中；**SHIFT** + **HOME** 选中当前光标到最前的所有字符；**SHIFT** + **END** 选中当前光标到最后的所有字符；以上是我常用的内容选中快键键，希望能被采纳，谢谢！
> 
> 我看了下这些在大部分常规终端工具上都是没有，那就暂时不考虑加进来了

好的。
