### ISSUE TITLE
[BUG]筛选的输入框的左侧按类型筛选的选项，该类型有数据，但选择后查不出来对应类型的数据。

### ISSUE THREAD

**Issue by tinylit** [tiny-craft/tiny-rdm#274]
**Tiny RDM Version**
What version of Tiny RDM are you using?

> v1.1.13

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

> Windows 11

**Redis Version**
Which version of Redis are you using?

> v5.0.4

**Comment by tiny-craft** [comment]
选了类型，输入框里面有没有内容，或者说类型筛选前是不是填过内容，后来清空了之类的操作

**Comment by tinylit** [comment]
打开数据库后直接切换类型，不操作输入框，也是一样的过滤结果为空，但是就当前页也是有该类型数据的。

**Comment by tiny-craft** [comment]
> 打开数据库后直接切换类型，不操作输入框，也是一样的过滤结果为空，但是就当前页也是有该类型数据的。

是不是因为没有这个类型的数据所以才为空？如果可以的话麻烦传个重现的操作视频我参考下

**Comment by tinylit** [comment]
https://github.com/tiny-craft/tiny-rdm/assets/26321525/1d35da6f-0612-4e4f-9711-af68ca1c422a

你好，这是录频，由于在公司不方便录音，我简单描述一下：
1、打开Tiny RDM客户端。
2、打开Redis链接数据库（默认是db12）。
3、打开【inventory】目录时，可以看到目录下有【STRING】类型的数据。
4、切换搜索类型时，显示【无数据】。

**Comment by tinylit** [comment]
> > 打开数据库后直接切换类型，不操作输入框，也是一样的过滤结果为空，但是就当前页也是有该类型数据的。
> 
> 是不是因为没有这个类型的数据所以才为空？如果可以的话麻烦传个重现的操作视频我参考下

https://github.com/tiny-craft/tiny-rdm/assets/26321525/1d35da6f-0612-4e4f-9711-af68ca1c422a

你好，这是录频，由于在公司不方便录音，我简单描述一下：
1、打开Tiny RDM客户端。
2、打开Redis链接数据库（默认是db12）。
3、打开【inventory】目录时，可以看到目录下有【STRING】类型的数据。
4、切换搜索类型时，显示【无数据】。

**Comment by tiny-craft** [comment]
>  Video_2024-06-13_092318.mp4 
> 你好，这是录频，由于在公司不方便录音，我简单描述一下： 1、打开Tiny RDM客户端。 2、打开Redis链接数据库（默认是db12）。 3、打开【inventory】目录时，可以看到目录下有【STRING】类型的数据。 4、切换搜索类型时，显示【无数据】。

谢谢，步骤很清晰。不过我按一样的步骤还是没法重现，晚点找个Windows的试试。这里有用到哨兵或者集群吗？

**Comment by tinylit** [comment]
> > Video_2024-06-13_092318.mp4
> > 你好，这是录频，由于在公司不方便录音，我简单描述一下： 1、打开Tiny RDM客户端。 2、打开Redis链接数据库（默认是db12）。 3、打开【inventory】目录时，可以看到目录下有【STRING】类型的数据。 4、切换搜索类型时，显示【无数据】。
> 
> 谢谢，步骤很清晰。不过我按一样的步骤还是没法重现，晚点找个Windows的试试。这里有用到哨兵或者集群吗？

不客气，感谢您的支持，辛苦了。我现在连接的是局域网测试环境，目前是单机的，没有集群，云服务准备用的阿里云的集群，也希望支持一下，谢谢。

**Comment by jianhao84** [comment]
我也遇到这个问题了，本地单机redis，建了几个String，在ALL类型下可以查看和搜索，但是切到String类型下就看不到了。下载的最新版本

**Comment by tiny-craft** [comment]
> 我也遇到这个问题了，本地单机redis，建了几个String，在ALL类型下可以查看和搜索，但是切到String类型下就看不到了。下载的最新版本

我这没法重现，你们那些`String`类型是真的就是`String`类型吗，还是实际上是ReJSON之类的高级类型

**Comment by tinylit** [comment]
> > 我也遇到这个问题了，本地单机redis，建了几个String，在ALL类型下可以查看和搜索，但是切到String类型下就看不到了。下载的最新版本
> 
> 我这没法重现，你们那些`String`类型是真的就是`String`类型吗，还是实际上是ReJSON之类的高级类型

是的，就是`STRING`类型，是通过`StackExchange.Redis`框架写入`C#`的`String`类型。

**Comment by tiny-craft** [comment]
经测试发现类型筛选从Redis 6.x才开始支持，以下是官方文档原话：

> Starting with Redis version 6.0.0: Added the TYPE subcommand.

所以目前处理方式是5.x及以下版本先禁用类型选择，后续Pro版本在增加复杂查询的同时会考虑支持低版本的类型筛选。

**Comment by tinylit** [comment]
> 经测试发现类型筛选从Redis 6.x才开始支持，以下是官方文档原话：
> 
> > Starting with Redis version 6.0.0: Added the TYPE subcommand.
> 
> 所以目前处理方式是5.x及以下版本先禁用类型选择，后续Pro版本在增加复杂查询的同时会考虑支持低版本的类型筛选。

好的，确实，我们另外一个6.2.14的实例就可以生效。
