### ISSUE TITLE
[FEATURE] ESC 关闭 modal

### ISSUE THREAD

**Issue by liaozan** [tiny-craft/tiny-rdm#275]
既然都[支持了 command+w 关闭标签页](https://github.com/tiny-craft/tiny-rdm/issues/258)，要不要考虑支持一下 ESC 关闭 modal 呢

客户端列表那里，习惯性的按 ESC 关闭 modal，结果没反应。。

**Comment by liaozan** [comment]
sorry。。试了下其他地方，好像都可以，就是客户端列表那里不行

**Comment by tiny-craft** [comment]
> sorry。。试了下其他地方，好像都可以，就是客户端列表那里不行

客户端列表不是modal哦，那个只是tips
