### ISSUE TITLE
[BUG]搜狗输入法的英文状态空格异常

### ISSUE THREAD

**Issue by liufeilong1014** [tiny-craft/tiny-rdm#277]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.13
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
版本14.0 (23A344
**Redis Version**
Which version of Redis are you using?
v5.0.13
**Describe the bug**
在命令行里无法切换库, 在搜狗输入法英文状态下
<img width="1117" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/131238932/39af175f-89dc-4955-90ab-6f9de75ed49b">

Steps to Reproduce:

1.把搜狗输入法输换到英文状态
2.在命令行里输入select 后面无法输入数字

**Comment by tiny-craft** [comment]
搜狗五笔？有没有更新到新版的搜狗？之前有人反馈搜狗拼音会无法输入，后来又莫名好了

**Comment by tiny-craft** [comment]
最新版已经修复这个问题。搜狗输入法的英文输入末尾默认加入了空格，但又不是常规的空格，而是`nbsp;`，所以导致命令没法执行
