### ISSUE TITLE
[FEATURE] 希望在string 类型key的value 查看方式上支持protobuf 解析

### ISSUE THREAD

**Issue by jiayiming001** [tiny-craft/tiny-rdm#278]
> 希望在string 类型key的value 查看方式上支持protobuf 解析

**Comment by jiayiming001** [comment]
可以参考another redis desktop

**Comment by tiny-craft** [comment]
这些需要自行定义协议不太通用的解码方式，目前还不打算支持。可以考虑使用自定义解码自行实现。

后续pro版本会考虑加更多便捷的解码方式。
