### ISSUE TITLE
[BUG]Bit Value Incorrect in Binary View

### ISSUE THREAD

**Issue by yangma12** [tiny-craft/tiny-rdm#279]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.1.13

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
win11
**Redis Version**
Which version of Redis are you using?

**Describe the bug**
使用位图setbit test116 0 1后，查看结果显示的二进制值错误，但是16进制正确，两者显示的不一样
Steps to Reproduce:

1. setbit test116 0 1
2.

**Comment by tiny-craft** [comment]
The latest version already fix this issue.
