### ISSUE TITLE
[BUG] 用ssh隧道连不上redis

### ISSUE THREAD

**Issue by NB611** [tiny-craft/tiny-rdm#281]
**Tiny RDM Version**
What version of Tiny RDM are you using?
V1.1.13
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
win11 24H2
**Redis Version**
Which version of Redis are you using?
V5.0.5
**Describe the bug**
我有两个redis服务，一个用ssh隧道可以连接，另一个连不上，报错截图：
![image](https://github.com/tiny-craft/tiny-rdm/assets/20264874/47cfef5e-3604-43c1-8746-0671f2946597)

我用Another Redis Desktop Manager 这个软件， 两个redis都可以连上。

**Comment by tiny-craft** [comment]
这个看起来是服务端拒绝连接，你对比下这两个服务器的ssh配置有什么不同。
你是不是用root用户登录，然后服务端又禁止了root远程登录。可以查下`/etc/ssh/sshd_config`配置看看

**Comment by tiny-craft** [comment]
或者通过ssh连接到这个服务器的数量刚好超过你设定的了

**Comment by NB611** [comment]
不好意思，ip前面有个空格。

**Comment by tiny-craft** [comment]
哦哦，不过我确实可以考虑地址trim以下前后空格，复制经常会复制多
