### ISSUE TITLE
[BUG]缓存key列表与实际的key列表对应

### ISSUE THREAD

**Issue by taskgirl123** [tiny-craft/tiny-rdm#282]
![微信图片_20240613180804](https://github.com/tiny-craft/tiny-rdm/assets/54127592/c5188402-a128-48c2-923a-4db6da7c8680)
实际是5个key。左侧显示只有两个，断开重连，重启以后都没有恢复

**Comment by tiny-craft** [comment]
是不是没有全部key加载
上方会有加载量的进度条
<img width="318" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/fffd6c25-0cbb-4f5b-b2f9-038b59a98c5a">

下方有个`加载下一批`和`加载全部剩余`

<img width="324" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/af825822-d8e2-4498-aed1-ca308df8db77">

**Comment by tiny-craft** [comment]
这个问题先关闭了，如果按我说的还没解决，欢迎重开讨论
