### ISSUE TITLE
[FEATURE]建议”批量删除键“功能使用lua，别查询出来

### ISSUE THREAD

**Issue by Diluka** [tiny-craft/tiny-rdm#283]
我要批量删除10万个key，卡死了，还不能取消，只能杀进程

**Comment by tiny-craft** [comment]
这个卡死是客户端UI层的卡死吧？用Lua解决不了客户端卡死，删除的时候也只是一个`delete`命令，那是因为key太多，查询出来再更新到界面上会卡，这个原来有考虑加多一个不查询就直接删除的按钮。

**Comment by Diluka** [comment]
用bull-board清除队列就很快，它就是lua，并且不会查询出来，直接删

**Comment by tiny-craft** [comment]
> 用bull-board清除队列就很快，它就是lua，并且不会查询出来，直接删

查询出来时我额外加了`KEYS`命令，为的是确认删除的键没有问题。你也可以通过命令行直接输入`delete prefix:*`来快速删除模式匹配的key，`DELETE`命令肯定比执行Lua要快

**Comment by tiny-craft** [comment]
这个我看下加个直接删除的选项，就可以降低删除大量key界面卡主的问题

**Comment by tiny-craft** [comment]
最新版已经加入不查询出结果根据表达式直接删除结果
