### ISSUE TITLE
鼠标扫过搜索按钮时，弹窗提醒希望不聚焦点

### ISSUE THREAD

**Issue by wilsendd** [tiny-craft/tiny-rdm#284]
<img width="484" alt="2024-06-16_10-34-30" src="https://github.com/tiny-craft/tiny-rdm/assets/64250565/31b941e8-3569-4af3-9b1e-04c778c4dfff">

**Comment by tiny-craft** [comment]
最新版鼠标在提示上时不再保留提示，仅在按钮上才会出现
