### ISSUE TITLE
[BUG] 数据库数量多导致的卡、慢问题

### ISSUE THREAD

**Issue by YELANDAOKONG** [tiny-craft/tiny-rdm#287]
**Tiny RDM Version**
v1.1.13

**OS Version**
Windows 11

**Redis Version**
Redis 7.2.5

**Describe the bug**
在数据库数量很多的情况下，点击底部切换数据库编号会卡死一段时间，同时整个程序也会比较卡

Steps to Reproduce:

1. 启动Redis并配置数据库数量为65536
2. 使用Tiny RDM连接

**Comment by tiny-craft** [comment]
是指db多的情况下？大概多少个？

**Comment by YELANDAOKONG** [comment]
> 是指db多的情况下？大概多少个？

emm...65536个

**Comment by tiny-craft** [comment]
db 65536??? 
服务器连接配置里面，可以设定只显示指定数据库和不显示指定数据库。你把常用的库列出来，减少列表的db显示数量试下，有没有改善。

> 这个设置第一次切换有bug，你切换到后面选项第一次下面输入框不显示，要确认之后再次编辑就会有显示了。
> 这个问题我前两天修复了。

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/a29e6b15-78d5-47ec-a557-94163d4a596f)

**Comment by YELANDAOKONG** [comment]
> db 65536???
> 
> 服务器连接配置里面，可以设定只显示指定数据库和不显示指定数据库。你把常用的库列出来，减少列表的db显示数量试下，有没有改善。
> 
> > 这个设置第一次切换有bug，你切换到后面选项第一次下面输入框不显示，要确认之后再次编辑就会有显示了。
> > 这个问题我前两天修复了。
> 
> ![image](https://private-user-images.githubusercontent.com/137850705/341629614-a29e6b15-78d5-47ec-a557-94163d4a596f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDQwMTEsIm5iZiI6MTcxODk0MzcxMSwicGF0aCI6Ii8xMzc4NTA3MDUvMzQxNjI5NjE0LWEyOWU2YjE1LTc4ZDUtNDdlYy1hNTU3LTk0MTYzZDRhNTk2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNDIxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzM1MjMzYTU3ZDliODJlYjEwMTE1YjZkMmViYTczYTgzZTNjNDcwYThkYzE4ODJhYjkxN2Y4NWFhYmM2MjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oc6UTlAG80Y0ws7oFnnCxRed8g_DJQ2pbPa4VN3hMjQ)

确实一点都不卡了，不过还是建议添加一下检测db数量的逻辑哦

**Comment by tiny-craft** [comment]
> 确实一点都不卡了，不过还是建议添加一下检测db数量的逻辑哦

什么逻辑？这个是导致选项过多已经达到web瓶颈了，要么就像Redis Insight那样只给输入数字来切换

**Comment by YELANDAOKONG** [comment]
> > 确实一点都不卡了，不过还是建议添加一下检测db数量的逻辑哦
> 
> 什么逻辑？这个是导致选项过多已经达到web瓶颈了，要么就像Redis Insight那样只给输入数字来切换

或许可以在连接的时候检测一下db数量然后给出提示

**Comment by tiny-craft** [comment]
> 或许可以在连接的时候检测一下db数量然后给出提示

嗯，这个问题会在我重做Pro版本的时候优化，数量太多的情况下改成输入的方式

**Comment by ydq** [comment]
> > 确实一点都不卡了，不过还是建议添加一下检测db数量的逻辑哦
> 
> 什么逻辑？这个是导致选项过多已经达到web瓶颈了，要么就像Redis Insight那样只给输入数字来切换

使用虚拟滚动是不是可以改善

**Comment by tiny-craft** [comment]
> 使用虚拟滚动是不是可以改善

我之前试了，他这到65535这个量级，改善不大。而且还有输入字符串过滤筛选。
