### ISSUE TITLE
[BUG]创建分组后再删除分组，无法删除现象

### ISSUE THREAD

**Issue by runants** [tiny-craft/tiny-rdm#288]
**Tiny RDM Version**
Tiny RDM 1.1.13

**OS Version**
Macos14.4.1 

**Redis Version**
none

**Describe the bug**
<img width="565" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/42563618/4c0f6491-513e-4a88-86c3-fc79bf348b76">
Steps to Reproduce:

1. 创建分组 A
2. 创建分组 B
3. 将 B组 迁移至 A组下
4. 创建新的rdb连接，关联至B组
5. 删除B组
6. 无法删除，出现此种现象

**Comment by tiny-craft** [comment]
第2步B组迁至A组，是指B组里面的连接移到A组，还是将B组塞进去

**Comment by tiny-craft** [comment]
最新版应该已经限制了分组塞进分组的操作，如果还有问题，欢迎回来反馈
