### ISSUE TITLE
[BUG]The frontend building failed with vite compiling issue

### ISSUE THREAD

**Issue by jxs1211** [tiny-craft/tiny-rdm#289]
**Tiny RDM Version**
What version of Tiny RDM are you using?
N/A

**OS Version**
Which OS and version did you launch? (Mac/Windows/Linux)
Windows WSL ubuntu2004

**Redis Version**
Which version of Redis are you using?
N/A

**Describe the bug**
I encountered a vite compiling error while executing wails dev on master branch, more details is posted on
https://github.com/wailsapp/wails/issues/3561

Steps to Reproduce:
1. https://github.com/wailsapp/wails/issues/3561

**Comment by tiny-craft** [comment]
It looks like the plugin `copy-text-to-clipboard` cannot be introduced. Have you try to remove it and all the associated code? 

I add this  plugin few days ago to resolve the issue that can not copy Chinese text on macOS(https://github.com/tiny-craft/tiny-rdm/issues/246).

**Comment by jxs1211** [comment]
> It looks like the plugin `copy-text-to-clipboard` cannot be introduced. Have you try to remove it and all the associated code?
> 
> I add this plugin few days ago to resolve the issue that can not copy Chinese text on macOS(#246).

I checkout to a previous commit before the problematic one, it works now.
```
➜  tiny-rdm git:(aa8c549)
...
2024/06/24 16:32:31 memory usage name SAMPLES 0
2024/06/24 16:32:31 zcard name
2024/06/24 16:32:31 type name
2024/06/24 16:32:31 zrange name 0 2999 withscores
2024/06/24 16:32:33 pipeline:  type stream: stream
2024/06/24 16:32:33 pipeline:  ttl stream: -1ns
2024/06/24 16:32:33 memory usage stream SAMPLES 0
2024/06/24 16:32:33 xlen stream
2024/06/24 16:32:33 type stream
2024/06/24 16:32:33 xrevrange stream + - count 3000
2024/06/24 16:32:49 pipeline:  type name: zset
2024/06/24 16:32:49 pipeline:  ttl name: -1ns
2024/06/24 16:32:49 memory usage name SAMPLES 0
2024/06/24 16:32:49 zcard name
2024/06/24 16:32:49 type name
2024/06/24 16:32:49 zrange name 0 2999 withscores
