### ISSUE TITLE
[BUG]: 点击新建链接弹框，鼠标左键随便点击弹框的任意位置，然后鼠标拖动，整个软件会随着鼠标推动而动

### ISSUE THREAD

**Issue by ALIFED** [tiny-craft/tiny-rdm#29]
![image](https://github.com/tiny-craft/tiny-rdm/assets/32628192/677900a0-6689-406d-b71b-01325d05f1f6)

**Comment by tiny-craft** [comment]
已经修复了，等下一个发布版本即可
d3fb920
