### ISSUE TITLE
[BUG]显示不全

### ISSUE THREAD

**Issue by liu-yfeng** [tiny-craft/tiny-rdm#291]
![image](https://github.com/tiny-craft/tiny-rdm/assets/8706840/ba13d5b9-f905-487a-b7c3-2c3ab56fb441)
![image](https://github.com/tiny-craft/tiny-rdm/assets/8706840/e7edef7b-b5ea-4e97-8e45-4f61b0e5b525)

**Comment by ydq** [comment]
RDM(RESP) 很傻 是一次性加在了全部，线上几亿Key直接傻掉

显示不全是因为没有加载所有的key，你需要手动选择加载更多 或者 一次性把剩下的加载完
如果你细心的话 你会发现 在 tiny-rdm 左侧 树的最下面有按钮，可以加载更多
<img width="288" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/8097340/a96b22e5-6fa5-4722-9ff2-406733d6030d">

**Comment by tiny-craft** [comment]
我看1楼的key好像不多，也加载不完整吗？是高级设置改了什么，还是比较特殊的部署，比如集群什么的

**Comment by liu-yfeng** [comment]
> 我看1楼的key好像不多，也加载不完整吗？是高级设置改了什么，还是比较特殊的部署，比如集群什么的

没有，就是单机，单机实例

**Comment by tiny-craft** [comment]
行，分段继续加载或者直接加载全部（如果key不是特别多的话）即可。
