### ISSUE TITLE
[FEATURE]希望增加每个Redis数据库添加备注的功能

### ISSUE THREAD

**Issue by Calonyction** [tiny-craft/tiny-rdm#292]
![image](https://github.com/tiny-craft/tiny-rdm/assets/39676176/0fb75a87-9696-4fff-92f7-09219c7242f8)
像这样 希望能给每个分库 右边添加备注，例如db0  **库， db1  ** 库

**Comment by tiny-craft** [comment]
每个连接的设置里面有数据库别名设置

![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/5511de47-7d28-4383-9d69-9d81f0294c0d)
