### ISSUE TITLE
[BUG] 数据显示不全，跟AnotherRedisDesktopManager相比，结果少了很多

### ISSUE THREAD

**Issue by Muscleape** [tiny-craft/tiny-rdm#293]
**Tiny RDM Version**
1.1.13

**OS Version**
Mac OS 13.2.1

**Redis Version**
6.2.31(BaiduReleased)

**Describe the bug**

很多key查询不到，跟另一款软件相比，很多数据都查不出来

<img width="759" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/16682039/b9cd4be7-a1b3-488c-b437-9ee095994cce">

**Comment by tiny-craft** [comment]
这是集群模式的吗？

**Comment by tiny-craft** [comment]
哦，你是没有按回车键，这只是在当前结果内进行筛选而已。
关于搜索的更多详细用法，可以参考官网文档：https://redis.tinycraft.cc/zh/guide/filter/

**Comment by Muscleape** [comment]
> 哦，你是没有按回车键，这只是在当前结果内进行筛选而已。 关于搜索的更多详细用法，可以参考官网文档：https://redis.tinycraft.cc/zh/guide/filter/

奥奥，确实，这里是查询和筛选两种操作，都在这个框里，个人感觉是不是两个操作分开更易懂一点

**Comment by 947612227** [comment]
我试了按回车不按回车的结果，不按回车还有两个结果，按了以后什么都木有，对比结果是Another Redis Desktop Manager
按了回车结果：
![image](https://github.com/user-attachments/assets/5b8e040e-9148-4347-ba7f-754327abc84d)
不按回车结果
![image](https://github.com/user-attachments/assets/e5fc26a7-0fba-4b33-bce0-7a2908a103c6)

**Comment by tiny-craft** [comment]
默认情况下，通配符只加在了结尾。所以你`assets/150163250`应该是能出来的。或者手动在前后加通配符。这个确实有点误解，可以优化下默认前后都加通配符
