### ISSUE TITLE
请大佬打包个AppImage包

### ISSUE THREAD

**Issue by yuelwish** [tiny-craft/tiny-rdm#3]
如题: 请大佬打包一下 AppImage 的包,  能够让更多人使用(我是更多人中的一员)

**Comment by wxyShine** [comment]
+1

**Comment by tiny-craft** [comment]
wails目前没有打包AppImage，我得找时间试下。有相关的github action也可以发我我研究下

**Comment by tiny-craft** [comment]
> [pkg2appimage](https://github.com/AppImageCommunity/pkg2appimage/) 这个工具可以将deb转为AppImage

有没有伙伴熟悉Linux的帮忙试下，我的认知盲区~

**Comment by raojinlin** [comment]
@yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。

[tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)

**Comment by tiny-craft** [comment]
> @yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。
> 
> [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)

很棒，我这也能打开，大概用了下和deb版本没啥区别，就是版本号填错了，应该是`1.1.9`
这个打包有没有记录步骤，有的话可以分享下，等我有空转成github action。或者可以的话你弄个action也行。
**再次感谢~**

**Comment by raojinlin** [comment]
> > @yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。
> > [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)
> 
> 很棒，我这也能打开，大概用了下和deb版本没啥区别，就是版本号填错了，应该是`1.1.9` 这个打包有没有记录步骤，有的话可以分享下，等我有空转成github action。或者可以的话你弄个action也行。 **再次感谢~**

好嘞，这个是在github action构建的，我等下提个PR。

**Comment by yuelwish** [comment]
> @yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。
> 
> [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)

Manjaro Linux x86_64   运行没反应

 `[lin@82l7 Downloads]$ ./tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage 
Gtk-Message: 10:12:59.717: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:12:59.789: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:12:59.790: Failed to load module "canberra-gtk-module"
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal

** (tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage:685072): ERROR **: 10:13:00.887: Unable to spawn a new child process: 生成子进程“/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess”失败（没有那个文件或目录）
SIGTRAP: trace trap
PC=0x7f2954524cef m=0 sigcode=128
signal arrived during cgo execution

goroutine 1 gp=0xc0000061c0 m=0 mp=0x1a96b80 [syscall, locked to thread]:
runtime.cgocall(0xab7bf0, 0xc000397a08)
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc0003979e0 sp=0xc0003979a8 pc=0x41004b
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_SetupWebview(0x241df40, 0x24d0260, 0x0, 0x1)
	_cgo_gotypes.go:791 +0x4c fp=0xc000397a08 sp=0xc0003979e0 pc=0x7a96ac
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow.func8(0xc01c5f?, 0xc0000f02c0, 0x1)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x90 fp=0xc000397a50 sp=0xc000397a08 pc=0x7b2c70
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow(0xc0000f02c0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x2c5 fp=0xc000397af8 sp=0xc000397a50 pc=0x7b22a5
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x14bee10, 0xc0003bc330}, 0xc0000f02c0, 0xc000012408, 0xc0000e01c0, {0x14bbf40, 0xc0000d3340})
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:196 +0x57a fp=0xc000397cf8 sp=0xc000397af8 pc=0x7acc3a
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/desktop_linux.go:16
github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc0000f02c0)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/app/app_production.go:86 +0x5af fp=0xc000397e40 sp=0xc000397cf8 pc=0x7bcfef
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc0000b2880)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/pkg/application/application.go:58 +0x25 fp=0xc000397e60 sp=0xc000397e40 pc=0x7bdd25
github.com/wailsapp/wails/v2.Run(0xc0000f02c0?)
	/home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/wails.go:14 +0x9a fp=0xc000397e88 sp=0xc000397e60 pc=0x7bdf1a
main.main()
	/home/runner/work/tiny-rdm/tiny-rdm/main.go:53 +0x7bd fp=0xc000397f50 sp=0xc000397e88 pc=0xab5b5d
runtime.main()
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/proc.go:271 +0x29d fp=0xc000397fe0 sp=0xc000397f50 pc=0x44635d
runtime.goexit({})
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000397fe8 sp=0xc000397fe0 pc=0x4791c1
`

**Comment by raojinlin** [comment]
> > @yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。
> > [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)
> 
> Manjaro Linux x86_64 运行没反应
> 
> `[lin@82l7 Downloads]$ ./tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage Gtk-Message: 10:12:59.717: Failed to load module "xapp-gtk3-module" Gtk-Message: 10:12:59.789: Failed to load module "canberra-gtk-module" Gtk-Message: 10:12:59.790: Failed to load module "canberra-gtk-module" Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
> 
> ** (tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage:685072): ERROR **: 10:13:00.887: Unable to spawn a new child process: 生成子进程“/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess”失败（没有那个文件或目录） SIGTRAP: trace trap PC=0x7f2954524cef m=0 sigcode=128 signal arrived during cgo execution
> 
> goroutine 1 gp=0xc0000061c0 m=0 mp=0x1a96b80 [syscall, locked to thread]: runtime.cgocall(0xab7bf0, 0xc000397a08) /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc0003979e0 sp=0xc0003979a8 pc=0x41004b github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_SetupWebview(0x241df40, 0x24d0260, 0x0, 0x1) _cgo_gotypes.go:791 +0x4c fp=0xc000397a08 sp=0xc0003979e0 pc=0x7a96ac github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow.func8(0xc01c5f?, 0xc0000f02c0, 0x1) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x90 fp=0xc000397a50 sp=0xc000397a08 pc=0x7b2c70 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow(0xc0000f02c0, 0x0, 0x0) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x2c5 fp=0xc000397af8 sp=0xc000397a50 pc=0x7b22a5 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x14bee10, 0xc0003bc330}, 0xc0000f02c0, 0xc000012408, 0xc0000e01c0, {0x14bbf40, 0xc0000d3340}) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:196 +0x57a fp=0xc000397cf8 sp=0xc000397af8 pc=0x7acc3a github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/desktop_linux.go:16 github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc0000f02c0) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/app/app_production.go:86 +0x5af fp=0xc000397e40 sp=0xc000397cf8 pc=0x7bcfef github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc0000b2880) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/pkg/application/application.go:58 +0x25 fp=0xc000397e60 sp=0xc000397e40 pc=0x7bdd25 github.com/wailsapp/wails/v2.Run(0xc0000f02c0?) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/wails.go:14 +0x9a fp=0xc000397e88 sp=0xc000397e60 pc=0x7bdf1a main.main() /home/runner/work/tiny-rdm/tiny-rdm/main.go:53 +0x7bd fp=0xc000397f50 sp=0xc000397e88 pc=0xab5b5d runtime.main() /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/proc.go:271 +0x29d fp=0xc000397fe0 sp=0xc000397f50 pc=0x44635d runtime.goexit({}) /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000397fe8 sp=0xc000397fe0 pc=0x4791c1 `

试下这个呢
[tiny-rdm_1.1.9_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.1.9/tiny-rdm_1.1.9_linux_amd64.AppImage)

**Comment by yuelwish** [comment]
> > > @yuelwish @shy1118999 @wxyShine
> > > [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)@yuelwish @shy1118999 @wxyShine 打包了一个AppImage的包，看看能不能用。在Ubuntu 22.04是可以打开的。
> > > [tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.0.9-ubuntu22.04/tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage)
> > 
> > 
> > Manjaro Linux x86_64 运行没反应Manjaro Linux x86_64 运行没反应
> > `[lin@82l7 Downloads]$ ./tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage Gtk-Message: 10:12:59.717: Failed to load module "xapp-gtk3-module" Gtk-Message: 10:12:59.789: Failed to load module "canberra-gtk-module" Gtk-Message: 10:12:59.790: Failed to load module "canberra-gtk-module" Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal'[lin@82l7下载]$./tiny-rdm_1.0.9-ubuntu22.04_linux_amd64. AppImage Gtk-Message：10:12:59.717：无法加载模块"xapp-gtk3-module"Gtk-Message：10:12:59.789：无法加载模块"canberra-gtk-module"Gtk-Message：10:12:59.790：无法加载模块"canberra-gtk-module"覆盖信号10的现有处理程序。如果您希望WebKit使用不同的信号，请设置JSC_SIGNAL_FOR_GC
> > ** (tiny-rdm_1.0.9-ubuntu22.04_linux_amd64.AppImage:685072): ERROR **: 10:13:00.887: Unable to spawn a new child process: 生成子进程“/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess”失败（没有那个文件或目录） SIGTRAP: trace trap PC=0x7f2954524cef m=0 sigcode=128 signal arrived during cgo execution**（tiny-rdm_1.0.9-ubuntu22.04_linux_amd64. AppImage：685072）：错误**：10:13:00.887：无法生成新的子进程：生成子进程"/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess"失败（没有那个文件或目录）SIGTRAP：跟踪陷阱PC=0x7f2954524cef m=0 sigcode=128信号在cgo执行期间到达
> > goroutine 1 gp=0xc0000061c0 m=0 mp=0x1a96b80 [syscall, locked to thread]: runtime.cgocall(0xab7bf0, 0xc000397a08) /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc0003979e0 sp=0xc0003979a8 pc=0x41004b github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_SetupWebview(0x241df40, 0x24d0260, 0x0, 0x1) _cgo_gotypes.go:791 +0x4c fp=0xc000397a08 sp=0xc0003979e0 pc=0x7a96ac github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow.func8(0xc01c5f?, 0xc0000f02c0, 0x1) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x90 fp=0xc000397a50 sp=0xc000397a08 pc=0x7b2c70 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow(0xc0000f02c0, 0x0, 0x0) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/window.go:104 +0x2c5 fp=0xc000397af8 sp=0xc000397a50 pc=0x7b22a5 github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x14bee10, 0xc0003bc330}, 0xc0000f02c0, 0xc000012408, 0xc0000e01c0, {0x14bbf40, 0xc0000d3340}) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:196 +0x57a fp=0xc000397cf8 sp=0xc000397af8 pc=0x7acc3a github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/desktop_linux.go:16 github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc0000f02c0) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/internal/app/app_production.go:86 +0x5af fp=0xc000397e40 sp=0xc000397cf8 pc=0x7bcfef github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc0000b2880) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/pkg/application/application.go:58 +0x25 fp=0xc000397e60 sp=0xc000397e40 pc=0x7bdd25 github.com/wailsapp/wails/v2.Run(0xc0000f02c0?) /home/runner/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.0/wails.go:14 +0x9a fp=0xc000397e88 sp=0xc000397e60 pc=0x7bdf1a main.main() /home/runner/work/tiny-rdm/tiny-rdm/main.go:53 +0x7bd fp=0xc000397f50 sp=0xc000397e88 pc=0xab5b5d runtime.main() /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/proc.go:271 +0x29d fp=0xc000397fe0 sp=0xc000397f50 pc=0x44635d runtime.goexit({}) /opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000397fe8 sp=0xc000397fe0 pc=0x4791c1 `goroutine 1 gp=0xc0000061c0 m=0 mp=0x1a96b80[syscall，锁定到线程]： runtime.cgocall（0xab7bf0,0xc000397a08） /opt/hostedtoolcache/go/ /home/runner/x64/src/runtime/cgocall.go：157+0x4bfp=0xc0003979e0 sp=0xc0003979a8 pc=0x41004b0 m（0x241df40,0x24d0260,0x0,0x1）_cgo_gotypes.go：791+0x4c fp=0xc000397a08 sp=0xc0003979e0 pc=0x7a96acgithub.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewWindow.func8（0xc01c5f？，0xc0000f02c0,0x1） /home/runner/go/pkg/mod/github.com/wailsapp/wails/ /home/runner/go/pkg/mod/内部/前端/桌面/linux/windows.go：104+0x90 fp=0xc000397a50 sp=0xc000397a08 pc/go/pkg/mod/github.com/wailsapp/wails/ /opt/hostedtoolcache/go/内部/app/app_production. go：86+0x5af fp=0xc000397e40 sp=0xc000397cf8 pc=0x7bcfefgithub.com/wailsapp/wails/v2/pkg/application（*Application）。运行（0xc0000b2880） /home/runner/go/pkg/mod/github.com/wailsapp/wails/ /opt/hostedtoolcache/go/pkg/application/application.go：58+0x25 fp=0xc000397e60 sp=0xc000397e40 pc=0x7bdd25/go/pkg/mod（0xc0000f02c0？） /home/runner/go/pkg/mod/ /home/runner/go/pkg/mod/app_production/wails.go：14+0x9a fp=0xc000397e88 sp=0xc000397e60 pc=0x7bdf1a main.main（） /home/runner/work/tiny-rdm/tiny-rdm/main.go：53+0x7bd fp=0xc000397f50 sp=0xc000397e88 pc=0xab5b5d runtime.main（） /opt/hostedtoolcache/go/ /home/runner/work/tiny-rdm/tiny-rdm/main.go/x64/src/runtime/proc.go：271
> 
> [tiny-rdm_1.1.9_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.1.9/tiny-rdm_1.1.9_linux_amd64.AppImage)
> 
> 试下这个呢 [tiny-rdm_1.1.9_linux_amd64.AppImage](https://github.com/raojinlin/tiny-rdm/releases/download/v1.1.9/tiny-rdm_1.1.9_linux_amd64.AppImage)

现在的能打开窗口了，但是一点新建连接就卡住了

Gtk-Message: 09:40:22.180: Failed to load module "xapp-gtk3-module"
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Gtk-Message: 09:40:22.424: Failed to load module "xapp-gtk3-module"

(tiny-rdm:13470): Gdk-CRITICAL **: 09:40:22.463: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
2024/03/10 09:40:22 after save {{300 1024 768 false 0 32} {auto auto  [] 14 3000 0 false false true } { [] 14 true true true true} {[] 14 block} []}
2024/03/10 09:40:23 after save {{300 1024 768 true 0 32} {auto auto  [] 14 3000 0 false false true } { [] 14 true true true true} {[] 14 block} []}
