### ISSUE TITLE
[BUG]redis服务没开的情况，点击连接第一次提示无法连接信息，第二次点击连接直接闪退

### ISSUE THREAD

**Issue by dyongjun** [tiny-craft/tiny-rdm#301]
**Tiny RDM Version**
What version of Tiny RDM are you using?
![image](https://github.com/tiny-craft/tiny-rdm/assets/39371723/e9004750-bc36-4d7a-8379-cbcb7214022d)

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
![image](https://github.com/tiny-craft/tiny-rdm/assets/39371723/e5598015-052a-464f-8280-fb9e7ab6d19a)

**Redis Version**
Which version of Redis are you using?
![image](https://github.com/tiny-craft/tiny-rdm/assets/39371723/9aee2b32-67e9-4f8a-b857-cacdd06c5d11)

**Describe the bug**
redis服务没开的情况，点击连接第一次提示无法连接信息，第二次点击连接直接闪退
![image](https://github.com/tiny-craft/tiny-rdm/assets/39371723/c98a422d-cdff-405d-b515-86defbd5acac)

Steps to Reproduce:

1.不开启redis服务，直接点击连接
2.

**Comment by tiny-craft** [comment]
最新版已经修复了这个问题
