### ISSUE TITLE
hash类型的字段文字对齐方式居左

### ISSUE THREAD

**Issue by webguosai** [tiny-craft/tiny-rdm#304]
![image](https://github.com/user-attachments/assets/b7fa7493-447a-4c3f-bcf4-4ae24740d3e6)
这个字段的文字能够居左显示吗，现在居中，有点不好看

**Comment by tiny-craft** [comment]
嗯，我会考虑下把左对齐和居中对齐加上~

**Comment by tiny-craft** [comment]
最新版已经支持设置居中还是居左
