### ISSUE TITLE
不支持macos 13.5.2 (22G91)

### ISSUE THREAD

**Issue by xywf221** [tiny-craft/tiny-rdm#31]
下载软件后打开提示 `你无法打开应用程序“Tiny RDM”，因为这台Mac不支持此应用程序。`

**Comment by tiny-craft** [comment]
是不是下载错包了，intel的下载amd64，M芯片的下载arm64

**Comment by tiny-craft** [comment]
@xywf221 问题解决了吗

**Comment by tiny-craft** [comment]
先关闭了，如果还有问题可以再新开个issue
