### ISSUE TITLE
Connection Error in Cluster Mode（集群模式下连接报错）

### ISSUE THREAD

**Issue by chenyudaima** [tiny-craft/tiny-rdm#310]
create conenction error:ERR SELECT is not allowed in cluster mode

redis version：redis-7.2.3

**Comment by tiny-craft** [comment]
连进去就这样了吗，还是做了其他操作会提示这个错误

**Comment by chenyudaima** [comment]
> 连进去就这样了吗，还是做了其他操作会提示这个错误

打开连接或则测试连接提示这个错误，然后连不上，不过我当时还没分配哈希槽和主从节点
