### ISSUE TITLE
[BUG]下载Tiny RDM 火绒 说是病毒 请开发者看看是哪里有问题

### ISSUE THREAD

**Issue by Wang-Mer** [tiny-craft/tiny-rdm#312]
**OS Version**
Windows

**Describe the bug**
在github 使用正版IDM 下载Tiny RDM时
Steps to Reproduce:

![image](https://github.com/user-attachments/assets/bae98edb-de43-4087-ad99-c3304c76c9e9)

**Comment by Wang-Mer** [comment]
@tiny-craft

**Comment by tiny-craft** [comment]
这个目前没办法，Wails的应用新建个空项目都被很多杀软认为是病毒。

估计要购买微软证书打包才能解决，目前暂不采取这个方案。

如果不放心可以先自行代码编译运行。

**Comment by Wang-Mer** [comment]
ok，明白了
