### ISSUE TITLE
批量删除键功能希望可以增加是否模糊匹配开关[FEATURE]

### ISSUE THREAD

**Issue by NB611** [tiny-craft/tiny-rdm#317]
![image](https://github.com/user-attachments/assets/ef10f412-5364-493a-b246-50fe6a65e0b1)
批量删除时，每次都要前后加*,希望可以增加一个checkbox是否模糊匹配，提高效率。

**Comment by tiny-craft** [comment]
这个暂时不考虑哈，因为这样对大部分用户，特别是第一次接触的来说，很容易误操作，一但删除就不可逆了😂
