### ISSUE TITLE
[FEATURE]兼容 Linux 语言设置为英文，软件无法切换中文输入法问题

### ISSUE THREAD

**Issue by yunxi177** [tiny-craft/tiny-rdm#319]
现象：当系统语言设置为英文，打开软件无法切换中文输入法
输入法框架： fcitx5
目前解决办法，在启动软件前指定 LANG。
```shell
env LANG=zh_CN.UTF-8 tiny-rdm
```

**Comment by tiny-craft** [comment]
有在你机器上编译运行代码吗，有的话帮忙试下在main.go方法中加入`os.Setenv("LANG", "zh_CN.UTF-8")`是不是能达到一样效果。

大致增加代码如下：
```go
import “os”

func main() {
	os.Setenv("LANG", "zh_CN.UTF-8")
	...
}
```

**Comment by yunxi177** [comment]
按照你说的试过了，打包后可以正常切换输入法，已提 PR

**Comment by tiny-craft** [comment]
> 按照你说的试过了，打包后可以正常切换输入法，已提 PR

嗯，这个不能单纯设置环境，不确定会不会导致其他语言环境会出现类似问题。
应该还要根据软件设置里面是不是中文再决定要不要设，还有切换语言时应该也要同步设置。我晚点再加上。

**Comment by tiny-craft** [comment]
@yunxi177 问下你出现这个情况是，软件内的语言选择是`使用系统语言`还是`简体中文`？

![QQ_1722930996337](https://github.com/user-attachments/assets/8d720ebf-9d55-404e-b84b-c6d61ef156e1)
