### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by CrazyBeginner** [tiny-craft/tiny-rdm#324]
![image](https://github.com/user-attachments/assets/7f950237-79b3-4e58-ade1-550614867bf4)

![image](https://github.com/user-attachments/assets/e2a55b7d-2a26-4a73-8670-d3b508b2d89b)

当有大量的记录和文件夹的时候，文件夹排在上边，单个的记录排在下边。

**Comment by tiny-craft** [comment]
不是很懂，现在不是文件夹排前面啊。你现在是还没全部key加载完

**Comment by tiny-craft** [comment]
太久没回复，这个问题先关闭了，如果还有问题可以继续在这里留言
