### ISSUE TITLE
[BUG] 在监控命令功能里，开启监控后，按停止按钮状态不会刷新

### ISSUE THREAD

**Issue by devilmagic** [tiny-craft/tiny-rdm#326]
**Tiny RDM Version**
What version of Tiny RDM are you using? 

1.2.0

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

Windows

**Redis Version**
Which version of Redis are you using?

6.2.6

**Describe the bug**

在监控命令功能里，开启监控后，按停止按钮没有反应，只有在下一条监控命令到达时才会更新按钮状态

Steps to Reproduce:

1.  开启监控
2.  停止监控  按钮状态不会变更

**Comment by sincerefly** [comment]
同 1.2.0 最新版本，不确定是不是同一 BUG，我点击「停止监控」后，25 秒钟才变化状态

**Comment by tiny-craft** [comment]
是同一个，go-redis会停止监控时会阻塞当前方法，因为里面在等锁，但是锁又被等待新命令的线程持有，要直到新执行的命令被读到它才解锁。

已经提交修复了

**Comment by tiny-craft** [comment]
`1.2.1`已经修复这个问题
