### ISSUE TITLE
[BUG] SET添加键值页面报错后无法工作

### ISSUE THREAD

**Issue by DevilGenius** [tiny-craft/tiny-rdm#327]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.14 -> v1.2.0
v1.2.0出现问题

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows

**Redis Version**
Which version of Redis are you using?
7.2.4

**Describe the bug**
页面报错后无法正常工作

Steps to Reproduce:

1.按钮添加 SET类型 key-value
2.key添加另一个value值报错 TypeError: Cannot read properties of null (reading 'emitsOptions')
![Screenshot 2024-08-14 113852](https://github.com/user-attachments/assets/ff87c3a8-8206-47b9-96f0-6c34117cff6c)

**Comment by tiny-craft** [comment]
win10吗？之前1.1.14不会有问题是吧？

**Comment by tiny-craft** [comment]
步骤是:

1. 添加一个新键，类型选`Set`
2. 添加后在打开的页面点`插入行`插入一条新数据

是这样吗

**Comment by DevilGenius** [comment]
使用Set类型使用相同的key插入两条数据

**Comment by tiny-craft** [comment]
![QQ_1723691392653](https://github.com/user-attachments/assets/5b86d6e8-2a3a-4155-9d61-4dc4f7516cb8)
这样吗？还是添加后，再插入新行`aa`。两种方式我都试了下，macOS下没出现这样的情况

**Comment by DevilGenius** [comment]
添加后再插入新行报错，没有试一次性插入的情况

**Comment by DevilGenius** [comment]
数据是正常插入了的，但是界面报错后就无法使用了

**Comment by tiny-craft** [comment]
就是先添加新的Set，初始项是`aa`，然后再插入新行`aa`这样吗？似乎我没法重现

在这之前还有没有做过其他操作，还是打开软件直接这样操作就必然出现。如果方便的话，麻烦给我发个重现的视频

**Comment by DevilGenius** [comment]
可能是我描述错了，不是在键内部插入行
使用左上方重新载入右侧 【添加新键】 键：a 类型：Set 值：1
然后再次使用左上方 【添加新键】 键：a 类型：Set 值：2
两次添加键和类型相同
HASH LIST SET ZSET STREAM都存在这个问题，JSON不支持不知道应该也存在相同问题

**Comment by tiny-craft** [comment]
行，重现问题，已经修复提交了。等下个新版本就行

**Comment by tiny-craft** [comment]
`1.2.1`已经修复这个问题
