### ISSUE TITLE
[BUG]前端无法编译，编译报错

### ISSUE THREAD

**Issue by icetech233** [tiny-craft/tiny-rdm#329]
F:\rediscode\tiny-rdm-main\frontend>cnpm run build

> frontend@0.0.0 build
> vite build

vite v5.4.0 building for production...
✓ 100 modules transformed.
x Build failed in 1.50s
error during build:
[vite:load-fallback] Could not load /F:/rediscode/tiny-rdm-main/frontend/wailsjs/runtime/runtime.js (imported by src/App.vue): ENOENT: no such file or directory, open 'F:\F:\rediscode\tiny-rdm-main\frontend\wailsjs\runtime\runtime.js'
Error: Could not load /F:/rediscode/tiny-rdm-main/frontend/wailsjs/runtime/runtime.js (imported by src/App.vue): ENOENT: no such file or directory, open 'F:\F:\rediscode\tiny-rdm-main\frontend\wailsjs\runtime\runtime.js'

**Comment by tiny-craft** [comment]
参看仓库首页README，你这个还没生成go->js的函数绑定文件

**Comment by icetech233** [comment]
> 参看仓库首页README，你这个还没生成go->js的函数绑定文件

啥绑定文件，你readme没有写啊

**Comment by tiny-craft** [comment]
`wails dev`
wails就会自动生成

**Comment by icetech233** [comment]
> `wails dev` wails就会自动生成

我试试

**Comment by tiny-craft** [comment]
太久没回复，这个问题先关闭了，如果还有问题可以继续在这里留言
