### ISSUE TITLE
[FEATURE] 是否考虑支持导出数据功能?

### ISSUE THREAD

**Issue by seth-shi** [tiny-craft/tiny-rdm#330]
如题, 比如某个 list 存储了白名单设备号, 想要批量导出

**Comment by tiny-craft** [comment]
现在就有
![QQ_1723711705588](https://github.com/user-attachments/assets/8e9de96f-d1c7-4de5-9144-fc4545041ec0)

选中指定的key导出，然后下面有导出选项

![QQ_1723711734570](https://github.com/user-attachments/assets/0a105b96-b584-45fd-9999-6625b0e9eb02)

**Comment by seth-shi** [comment]
导出的是一串字符串, 想要的是原始的内容, 比如就按这个原始的导出
![image](https://github.com/user-attachments/assets/38ea3198-1709-487f-86d4-d0038a9865d9)

**Comment by tiny-craft** [comment]
redis里面存的内容不一定是正常的文本，可能是一些没法显示的二进制，比如一张图片的数据。所以没法按文本的通用方法来导出

**Comment by seth-shi** [comment]
现在导出是纯 十六进制的, 完全不可用

**Comment by tiny-craft** [comment]
现在的用途就是用作导入导出。
你是想导出来单独用的是吧？这个可以考虑下，是另外一个角度了，算是表格内容编辑了

**Comment by seth-shi** [comment]
对的, 是要导出数据来查看
