### ISSUE TITLE
[FEATURE]希望扫描服务器功能可以增加过滤表达式选择功能

### ISSUE THREAD

**Issue by zhengshangjinx** [tiny-craft/tiny-rdm#331]
写在前面：
工具做的很棒，颜值很高，并且轻量化，现有功能基本满足开发阶段使用。
已Star，也会推荐身边朋友用起来，大佬加油！

希望增加功能如图：
![Xnip2024-08-16_16-23-09](https://github.com/user-attachments/assets/ba448e48-654d-4fd7-9f3e-e1559730b69c)

另外希望可以增加全匹配**模式供筛选，比如执行命令：`scan 0 MATCH *dict* COUNT 10000`
虽然此模式对Redis扫描会很多，但是一般使用此工具都在开发阶段，而且可以选择性使用。

**Comment by tiny-craft** [comment]
你输入`*dict*`按下回车，就是这个效果了

**Comment by tiny-craft** [comment]
太久没回复，这个问题先关闭了，如果还有问题可以继续在这里留言
