### ISSUE TITLE
[BUG] json类型添加新key，value错误是需要重新填写

### ISSUE THREAD

**Issue by sys-xander** [tiny-craft/tiny-rdm#338]
![image](https://github.com/user-attachments/assets/9f908355-378e-4a67-878e-d28621001d77)
![image](https://github.com/user-attachments/assets/226bbc21-a2cf-4e39-a134-03972efcbb13)

希望支持可以重新编辑，希望可以在原输入上修改，而不是全部重新编辑

**Comment by tiny-craft** [comment]
`1.2.1`版本后添加数据出错不再关闭对话框
