### ISSUE TITLE
[BUG] Ubuntu24.04不显示画面

### ISSUE THREAD

**Issue by KongZouXiang** [tiny-craft/tiny-rdm#344]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.2.0
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

**Redis Version**
Which version of Redis are you using?

**Describe the bug**
![1724209544143](https://github.com/user-attachments/assets/40c60d3b-814f-4e62-8ce5-9e54c10d7e4c)
![1724209586449](https://github.com/user-attachments/assets/42ac6f50-4f88-4685-9299-e0db40888251)

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment]
你是通过代码运行的吗

**Comment by KongZouXiang** [comment]
通过amd64.deb安装的

**Comment by tiny-craft** [comment]
> 在最新版本的 Webkit2Gtk (2.42.0) 中，由于 Nvidia 专有驱动未完全实现 DMABUF，将导致无法启动和崩溃的情况发生，如果遇到 段错误 或 Tiny RDM 无法启动的情况，请尝试在 /etc/environment （或者其他设置环境变量的地方）中加入 WEBKIT_DISABLE_DMABUF_RENDERER=1 环境变量关闭 DMABUF 的使用。

试下上面这个方式能不能解决

**Comment by KongZouXiang** [comment]
![1724222685236](https://github.com/user-attachments/assets/c27d80ad-94e8-4bdd-849e-2705420403af)
用这种方式可以的,非常感谢

**Comment by tiny-craft** [comment]
@KongZouXiang 你的24.04安装的时候有遇到这个老外的问题吗，他说安装不上。你在安装Tiny RDM之前装了哪个依赖，可以到这issue下面说下吗。
https://github.com/tiny-craft/tiny-rdm/issues/333

我原以为是限制了libwebkit2gtk才导致安装不上的😂，所以让他尝试下代码编译
