### ISSUE TITLE
[FEATURE] 如何自定义Java Serializable?

### ISSUE THREAD

**Issue by darkSystemCode** [tiny-craft/tiny-rdm#347]
@tiny-craft 
1、我按照GUIDE编写了java自定义序列化程序，并在偏好设置中配置了自定义解码
2、配置如图：
![Uploading PixPin_2024-08-22_17-44-45.png…]()

3、如2所示，这样配置是否正确，但至少结果是不正确的，我无法通过配置的自定义序列化解码Base64结果，请问我该如何修改呢，目前想查看本地日志，但是没发现日志文件。

**Comment by darkSystemCode** [comment]
续2图![image](https://github.com/user-attachments/assets/faf72bea-b773-4a8f-b75f-9c4761826401)

**Comment by tiny-craft** [comment]
路径不是java文件，应该是java命令的路径，java文件只是命令里面的一个参数

**Comment by darkSystemCode** [comment]
我是以java的命令运行这个文件，还是tiny有通用的命令运行呢？

**Comment by tiny-craft** [comment]
> 续2图![image](https://private-user-images.githubusercontent.com/50562636/360381584-faf72bea-b773-4a8f-b75f-9c4761826401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjM2OTAsIm5iZiI6MTcyNDQyMzM5MCwicGF0aCI6Ii81MDU2MjYzNi8zNjAzODE1ODQtZmFmNzJiZWEtYjc3My00YThmLWI3NWYtOWM0NzYxODI2NDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YjM0NTQyYjQ1ZjQ5OWM1YjBkOWUxNmM4M2FkOTIxODE2YjM1M2RjODVkNTE2NTgxOWNiNWMxYjY0YTNlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bhNTXglAt549Ql8kzIJn-qa9nRjTxX3d7ORpG1e-twE)

你图里的配置不对，执行路径应该是java命令的路径，如果你环境变量配置了，直接填`java`就可以了，不是java文件。第一个参数才是`Java文件`，第二个参数是`{VALUE}`

具体使用方式可以参考官网自定义php解码器的方式 https://redis.tinycraft.cc/zh/guide/custom-decoder/

**Comment by tiny-craft** [comment]
> 我是以java的命令运行这个文件，还是tiny有通用的命令运行呢？

Tiny RDM里面没有通用命令，它调用的是系统命令，所以你可以先在命令行上测试`java xxx/file.java {VALUE}`能不能正常执行，再根据情况填进去就行了

**Comment by darkSystemCode** [comment]
我按照您的方案做出了新的修改，我使用cmd测试Decode.java能正确输出Base64字符串，Base64字符串内容（eyJzZXJpYWxWZXJzaW9uVUlEIjoxMDAsImlkIjoxMCwibmFtZSI6InNodVlhbiIsImNoaWxkIjpudWxsfQ==）。但是我配置到Tiny使用了自定义解码，页面无法正确显示Base64字符串实际的json数据。
![PixPin_2024-08-30_15-29-09](https://github.com/user-attachments/assets/b6cc3d3b-3d9c-477e-b0aa-f2d5db457e01)
![PixPin_2024-08-30_15-29-33](https://github.com/user-attachments/assets/0991116a-41c3-4c04-ae83-61c6f5565b54)

**Comment by darkSystemCode** [comment]
没有效果，现在不确定是协议不对还是什么问题
![image](https://github.com/user-attachments/assets/880d034f-cf36-4c7a-ad40-9a38e5988d33)

**Comment by darkSystemCode** [comment]
可以了，问题在于我没有System.out.println()，把Base64的字符串集打印出来

**Comment by darkSystemCode** [comment]
但是存在一个bug，我点击删除按钮把{VALUE} marshalling删除，仅保留两个，点击保存，tiny依旧会帮我拼接回这两个参数，导致存在重复问题，如下图所示：
![image](https://github.com/user-attachments/assets/b080d907-cc2c-48d3-80f3-b70d62b67f9b)

**Comment by tiny-craft** [comment]
> 但是存在一个bug，我点击删除按钮把{VALUE} marshalling删除，仅保留两个，点击保存，tiny依旧会帮我拼接回这两个参数，导致存在重复问题，如下图所示： ![image](https://private-user-images.githubusercontent.com/50562636/363399540-b080d907-cc2c-48d3-80f3-b70d62b67f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDU0MTUsIm5iZiI6MTcyNTI0NTExNSwicGF0aCI6Ii81MDU2MjYzNi8zNjMzOTk1NDAtYjA4MGQ5MDctY2MyYy00OGQzLTgwZjMtYjcwZDYyYjY3ZjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAyNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGM5OTE2NjFkMDI3YTZmNTllOTI5MWIxY2VjOWQyMGQ2Yjc5NDhhZjRjNzQzMDBlMzlmY2JjOWM4N2NiMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pH-ihTMmwAXnk35asGHuKq67B-a9OPL9sgteGu2zol8)

是保存后再回头修改，打算删除两个参数吗

**Comment by darkSystemCode** [comment]
首先，我只填写了{VALUE}和marshalling这两个参数，点击保存后再进入修改页面就变成了如图所示的两组参数了，不管我怎么删除，再次进入修改都是保持两组参数

**Comment by tiny-craft** [comment]
> 首先，我只填写了{VALUE}和marshalling这两个参数，点击保存后再进入修改页面就变成了如图所示的两组参数了，不管我怎么删除，再次进入修改都是保持两组参数

好，这个问题我看下什么原因

**Comment by tiny-craft** [comment]
![QQ_1725245828336](https://github.com/user-attachments/assets/db013d7b-25a0-43ff-a86e-a9ce1baaf3f5)

是这样吗？试了下没有重现，无论重新打开，还是重启应用打开

**Comment by darkSystemCode** [comment]
![PixPin_2024-09-02_11-01-32](https://github.com/user-attachments/assets/532bcd40-c224-4e6d-87dd-4ada61a28ef3)
这问题一致的，你看下gif复现情况。

**Comment by tiny-craft** [comment]
> 。

没看明白，这不是能正常删除吗😂
图里也没看到多出两个重复的参数

**Comment by darkSystemCode** [comment]
这个gif我没复现上面提到的两个参数，但是复现的问题是和这两个参数一致的bug，我详细看gif，我删除了最后的一个参数，点击保存再次进入修改页面，最后的参数又重新出现了。

**Comment by tiny-craft** [comment]
`1.2.1`已经修复自定义参数不能移除的问题了
