### ISSUE TITLE
[BUG] 在目录上刷新，数据不会加载出来。需要顶部刷新按钮才会出来

### ISSUE THREAD

**Issue by getpro** [tiny-craft/tiny-rdm#348]
**Tiny RDM Version**
v1.2.0

**OS Version**
Win10

**Redis Version**
7.0.2

**Describe the bug**
在目录上刷新，数据不会加载出来。需要顶部刷新按钮才会出来

Steps to Reproduce:

1. 删除该目录下的所有数据
2. 在目录上点击刷新，多个上级目录都刷新了也不行
3. 数据未更新

**Comment by tiny-craft** [comment]
`1.2.1`已经修复这个问题
