### ISSUE TITLE
[BUG]打开白屏

### ISSUE THREAD

**Issue by wenbochang888** [tiny-craft/tiny-rdm#349]
**Tiny RDM Version**
1.2.0

**OS Version**
![1](https://github.com/user-attachments/assets/2b899de2-443b-44ea-b382-83e173887353)

**Redis Version**
还没有打开软件

**Describe the bug**
白屏
![2](https://github.com/user-attachments/assets/abdd7764-d103-4273-aa3e-fd74cd0eafa2)

Steps to Reproduce:

**Comment by tiny-craft** [comment]
10.15.x已经不支持，web组件不兼容导致报错白屏。可以等我正在重写的Pro版本
