### ISSUE TITLE
[BUG]未查询到全量KEY，只能查询到1/3的KEY

### ISSUE THREAD

**Issue by awesomeZhu** [tiny-craft/tiny-rdm#351]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.2.0
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows
**Redis Version**
Which version of Redis are you using?

**Describe the bug**
没有加载全量的key，只能查询到一部分，搜索也不能查询到。

**Comment by tiny-craft** [comment]
键太多的时候会进行分段加载，关于键加载可以参考官方文档：https://redis.tinycraft.cc/zh/guide/key-loading/

**Comment by tiny-craft** [comment]
太久没回复，这个问题先关闭了，如果还有问题可以继续在这里留言
