### ISSUE TITLE
[BUG] redis连接后报错'no db loaded'

### ISSUE THREAD

**Issue by AzusaZzzz** [tiny-craft/tiny-rdm#353]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.2.0

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Windows
**Redis Version**
Which version of Redis are you using?
redis:7.4.0-debian-12-r2
**Describe the bug**

Steps to Reproduce:
k8s下部署的redis，通过nodePort访问后报错

<img width="720" alt="15223D92-E406-47cb-A0C6-C2F71D2EA8F2" src="https://github.com/user-attachments/assets/3953a6cd-fc3c-441b-b93e-0595adf0b91a">

**Comment by tiny-craft** [comment]
是不是没有读取库个数的权限，通过命令行连接能不能执行`config get databases`或者`info keyspace`命令

还是Tiny RDM里面你在连接设置把所有能用的库都隐藏掉了呢

**Comment by AzusaZzzz** [comment]
> 是不是没有读取库个数的权限，通过命令行连接能不能执行`config get databases`或者`info keyspace`命令
> 
> 还是Tiny RDM里面你在连接设置把所有能用的库都隐藏掉了呢

命令行能执行
<img width="508" alt="81485343-662D-4f6c-9453-49A8B2CB5764" src="https://github.com/user-attachments/assets/2687ae58-068b-43c7-9a42-0afdf3670502">

连接设置如下
![image](https://github.com/user-attachments/assets/1574c267-0f84-4a63-8dd4-330a9548743f)

**Comment by tiny-craft** [comment]
高级设置里面，`数据库过滤方式`有没有设置？

**Comment by tiny-craft** [comment]
`1.2.1`已经修复这个问题，可以看看还会不会提示这个`no db loaded`错误，有问题可以随时在这里反馈
