### ISSUE TITLE
[BUG] redis实际值和tiny内容显示不全

### ISSUE THREAD

**Issue by OctoberMoon** [tiny-craft/tiny-rdm#358]
**Tiny RDM Version**
v1.2.0
**OS Version**
mac 12.7.1 

**Redis Version**
v5.0.13

**Describe the bug**
内容显示不全 如图:
tinyRdm
<img width="328" alt="image" src="https://github.com/user-attachments/assets/8d1b5ed4-9567-49fd-a33f-181b124324d6">
其他rdm
<img width="448" alt="image" src="https://github.com/user-attachments/assets/95ac3f07-baab-44bc-97f0-39e1b375f89a">

Steps to Reproduce:
1. 内容显示不全
2. 实际上是有的 通过命令查询可查到

**Comment by OctoberMoon** [comment]
键太多的时候会进行分段加载，关于键加载可以参考官方文档：https://redis.tinycraft.cc/zh/guide/key-loading/

**Comment by tiny-craft** [comment]
你自问自答，所以是找到答案了吗😂

**Comment by OctoberMoon** [comment]
> 你自问自答，所以是找到答案了吗😂

是的  看了下文档  
<img width="445" alt="image" src="https://github.com/user-attachments/assets/c52f5014-01ce-4430-9045-5a14e48f324b">
如果可以标识全部数量 或者  可以强制加载出来  知道里面还有其他键值 就好了 
我初以为程序问题  缓存没写进去 查了半天换了个工具才确定程序没问题 😂😂😂

**Comment by tiny-craft** [comment]
> > 你自问自答，所以是找到答案了吗😂
> 
> 是的 看了下文档 <img alt="image" width="445" src="https://private-user-images.githubusercontent.com/26913481/369589114-c52f5014-01ce-4430-9045-5a14e48f324b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjI5NTAsIm5iZiI6MTcyNzE2MjY1MCwicGF0aCI6Ii8yNjkxMzQ4MS8zNjk1ODkxMTQtYzUyZjUwMTQtMDFjZS00NDMwLTkwNDUtNWExNGU0OGYzMjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA3MjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMzJlMjI4NzQyZDQzYzhjNTAyYTkwNWNmMDE3ZTliMjFkYmQxMDQ4MTcyZTIwMjQ4OWVhNTE5MzUzNzFmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zSA4rn4OOnqTggCrHRE10j1a8ZGTBDgemRXwojWC5XM"> 如果可以标识全部数量 或者 可以强制加载出来 知道里面还有其他键值 就好了 我初以为程序问题 缓存没写进去 查了半天换了个工具才确定程序没问题 😂😂😂

搜索框下面有加载量的进度条，下面数据库选择那也有显示已经在数量和所有数量，你在设置里面把分段加载数量填大，比你数据库的key数量大就可以每次都全量加载，就是每次打开可能需要等
