### ISSUE TITLE
[FEATURE]macpro2019 intel 命令行输入命令时按空格无反应

### ISSUE THREAD

**Issue by zwlj** [tiny-craft/tiny-rdm#364]
macpro2019 intel 命令行输入命令时按空格无反应，需要从外部复制命令进命令行操作，单独输入空格字符无效。

**Comment by tiny-craft** [comment]
是不是搜狗输入法之类的

**Comment by zwlj** [comment]
已经解决，是输入法的问题，我换成了原生的输入法就可以了，之前使用的是搜狗输入法
