### ISSUE TITLE
[BUG]3.39G的数据导入失败。

### ISSUE THREAD

**Issue by masensei** [tiny-craft/tiny-rdm#369]
Tiny RDM Version
v1.2.1

OS Version
intel Mac OS 15

Redis Version
Redis 7.2.6

尝试在远程服务器导出一个比较小的KEY，导出后文件571M，在本地可以成功导入。
尝试在远程服务器导出了一个比较大的KEY，导出后文件3.39G，在本地导入时显示成功0，忽略1 。
远程Redis版本2.8.8

请问Tiny 是以什么方式导出的，能不能用redis-cli什么的替代导入？

**Comment by tiny-craft** [comment]
是不是导出的redis版本和导入的不一样

**Comment by masensei** [comment]
> 是不是导出的redis版本和导入的不一样

是不一样，但是小一点的key(一百多万数据的)试了好几个都能成功导入导出。大的key（五六百万条数据的）就被忽略。

或者我想办法在本地搞个2.8.8再试试。

**Comment by tiny-craft** [comment]
是导入过程卡住了，还是操作后完全没反应。
这个导出的格式是Tiny RDM的，还是Redis的`Dump`命令

**Comment by masensei** [comment]
> 是导入过程卡住了，还是操作后完全没反应。 这个导出的格式是Tiny RDM的，还是Redis的`Dump`命令

导入过程没有卡，就转了一会儿圈圈然后提示导入完成，成功0，忽略1 。 导出的格式是Tiny 的csv。

**Comment by masensei** [comment]
问题找到了。原来是redis-server配置中的缓存太小了，调大以后就好了。多谢。

**Comment by tiny-craft** [comment]
方便的话也可以在这里说一下redis server配置哪里调大缓存，以供后来者参考😂

**Comment by masensei** [comment]
> 方便的话也可以在这里说一下redis server配置哪里调大缓存，以供后来者参考😂

#client-query-buffer-limit 64gb

这一项，我也不知道填多少直接填了我的最大内存.

**Comment by masensei** [comment]
另外导出的数据如果直接以二进制存储的话可以节省很多空间。tiny导出的数据部分我转成bytes直接瘦身了一半。

**Comment by tiny-craft** [comment]
> 另外导出的数据如果直接以二进制存储的话可以节省很多空间。tiny导出的数据部分我转成bytes直接瘦身了一半。

在重写的Pro版本，会考虑更高压缩和redis版本兼容的导入导出，敬请期待
