### ISSUE TITLE
[BUG]The WebView2 process crashed and the application needs to be restarted.

### ISSUE THREAD

**Issue by Granttt** [tiny-craft/tiny-rdm#371]
**Tiny RDM Version**
1.2.1

**OS Version**
Windows

**Redis Version**
Which version of Redis are you using?

**Describe the bug**
The WebView2 process crashed and the application needs to be restarted.

Steps to Reproduce:

1.
2.
![QQ截图20241012165609](https://github.com/user-attachments/assets/cec84674-426e-4166-a576-25f9a9ea0deb)

**Comment by tiny-craft** [comment]
Have you resolve this issue? This happens on some Windows platform.

**Comment by DaZhang98** [comment]
> Have you resolve this issue? This happens on some Windows platform.

This issue is related to the webview2 runtime and can be resolved by reinstalling the webview2 runtime.

[Try this](https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/)
