### ISSUE TITLE
[FEATURE] 建议新增值长度格式化显示

### ISSUE THREAD

**Issue by mdddj** [tiny-craft/tiny-rdm#378]
<img width="285" alt="image" src="https://github.com/user-attachments/assets/788a25b9-9d2f-4c2d-a50f-d5a19d6b0909">

希望左边长度大小,像内存占用一样格式化显示

**Comment by tiny-craft** [comment]
每3位用逗号隔开？还是用`K`之类代替千这种？

**Comment by mdddj** [comment]
> 每3位用逗号隔开？还是用`K`之类代替千这种？

大佬,一起用也行,像123.33kb,100md,1.1gb, 这样就不用开一个网页去转换大小了

**Comment by tiny-craft** [comment]
> > 每3位用逗号隔开？还是用`K`之类代替千这种？
> 
> 大佬,一起用也行,像123.33kb,100md,1.1gb, 这样就不用开一个网页去转换大小了

但这是长度，咋用KB，GB..

**Comment by mdddj** [comment]
> > > 每3位用逗号隔开？还是用`K`之类代替千这种？
> > 
> > 
> > 大佬,一起用也行,像123.33kb,100md,1.1gb, 这样就不用开一个网页去转换大小了
> 
> 但这是长度，咋用KB，GB..

这个不是value的数据大小吗? 应该可以用这种方式来表现吧

**Comment by tiny-craft** [comment]
不是，这个字符串的话就是字符串长度，如果是其他类似LIST/HASH，就是它们内部的个数
