### ISSUE TITLE
[FEATURE]发布/订阅页面的频道/消息体，建议右键可复制或右键菜单也复制

### ISSUE THREAD

**Issue by thinkclaves** [tiny-craft/tiny-rdm#386]
#需求

频繁需要检查redis的channel和body内容是否正常、格式是否正常，需要将消息体复制粘贴到JSON格式校验网址中校验、预览。

目前不支持复制频道和消息，使用起来有所不便。

这个就是原因

![Snipaste_2024-11-04_11-13-49](https://github.com/user-attachments/assets/878c7348-9139-48fd-8b8d-0c09979f13e8)

#Requirement
There is a frequent need to check whether the channel and body content of Redis are normal and whether the format is correct. It is necessary to copy and paste the message body into a JSON format validation website for validation and preview.

Currently, copying channels and messages is not supported, which makes it inconvenient to use.

This is the reason.

#需求
频需检视Redis之频道与内容是否正常，格式是否合规，需将消息体复制粘贴至JSON格式校验网址以验其真伪，预览之。

今不支复制频道与消息，使用颇为不便。

此其故也。

**Comment by tiny-craft** [comment]
哈，三种文体颇有意思。订阅发布功能在Pro重写版本中有计划优先增强，这个需求一定会加上，敬请期待
