### ISSUE TITLE

1.1.13版本 通过数据类型列举key失败（无内容显示）

### ISSUE THREAD

**Issue by MoJingYan** [tiny-craft/tiny-rdm#392]
如标题，All能显示key，但是通过string或者set或者其他类型都无法列举key

**Comment by tiny-craft** [comment]
是不是Redis服务器的版本太低了，不支持类型筛选

**Comment by MoJingYan** [comment]
> 是不是Redis服务器的版本太低了，不支持类型筛选

5.x版本的看样子不支持，感谢回复。
更新到最新版有提示信息说不支持了。

**Comment by tiny-craft** [comment]
是的，6.0以上版本才支持类型筛选
