### ISSUE TITLE
『bug』按钮无反应，复制时会拖动整个窗口

### ISSUE THREAD

**Issue by declandragon** [tiny-craft/tiny-rdm#4]
![image](https://github.com/tiny-craft/tiny-rdm/assets/37643710/ec2afed4-1f0b-45bd-a8b0-db4051d50ec4)

**Comment by declandragon** [comment]
还有一个不确定是不是BUG，我账号密码是对的，在另外一个客户端可以链接，这个客户端无法链接。

**Comment by tiny-craft** [comment]
你连的这个是单机的还是其他主从之类的部署

**Comment by declandragon** [comment]
> 你连的这个是单机的还是其他主从之类的部署

好像是弹性IP，具体不是很清楚

**Comment by tiny-craft** [comment]
@declandragon 你登录的服务器是不是有用户名和密码的？

**Comment by declandragon** [comment]
> @declandragon 你登录的服务器是不是有用户名和密码的？

这个不是登录服务器，是运维部署好了，只告诉我IP端口密码，代码里填上就行，别的工具可以正常用，这个工具连不上，所以我说不确定是不是BUG

**Comment by tiny-craft** [comment]
> > @declandragon 你登录的服务器是不是有用户名和密码的？
> 
> 这个不是登录服务器，是运维部署好了，只告诉我IP端口密码，代码里填上就行，别的工具可以正常用，这个工具连不上，所以我说不确定是不是BUG
> 
> 举个例子，类似于你 ssh 账号密码在 Xshell 上可以用，在 FinalShell 上不可用

@declandragon 暂时找不到可以复现的环境。如果可以的话，最好能提供一个类似的docker环境给我。或者提供多一点登录失败时的错误信息给我看看

**Comment by tiny-craft** [comment]
登录不了的问题可以试下最新版新增的哨兵或集群，看看连的是不是哨兵节点或者集群节点。如果还有问题再开新的issue吧。按钮的问题之前的版本也改过了，这个先关闭了
