### ISSUE TITLE
自动压缩（或展开）中间层级

### ISSUE THREAD

**Issue by Songzhizong** [tiny-craft/tiny-rdm#40]
目前只有一key的话也要一级一级点下去，很不方便。
<img width="620" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/22743270/dd4b887b-57b4-456f-ab43-7fb008faa02b">

**Comment by tiny-craft** [comment]
1.0.4已经支持只有单键的多层级目录自动全部展开
