### ISSUE TITLE
希望可以支持导出和导入redis配置

### ISSUE THREAD

**Issue by TankCool** [tiny-craft/tiny-rdm#41]
这样可以在不同设备之间同步配置，不需要重复手动添加

**Comment by bzw1204** [comment]
> 这样可以在不同设备之间同步配置，不需要重复手动添加

如果支持webdav就更好了， 配置可以自己同步到自己的webdav服务器，一机配置到处使用

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)已经加入导入导出连接配置
