### ISSUE TITLE
sentinel 支持

### ISSUE THREAD

**Issue by chachae** [tiny-craft/tiny-rdm#42]
好像不支持sentinel，测试链接通过，但是保存后打开链接提示ERR 报错
<img width="337" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/25251252/4ec455cd-eb25-4972-ae4a-fb978fba2262">

**Comment by tiny-craft** [comment]
Duplicate of #16

**Comment by tiny-craft** [comment]
1.0.4已经支持哨兵模式
