### ISSUE TITLE
windows defender 直接报木马了

### ISSUE THREAD

**Issue by MoeMoeFish** [tiny-craft/tiny-rdm#48]
刚刚下载的 1.0.4

windows 11

虽说应该没问题，不过对于用户体验太不好了

![图片](https://github.com/tiny-craft/tiny-rdm/assets/7419357/48931b40-e3b0-464b-a75a-11f6520549f9)

**Comment by MoeMoeFish** [comment]
绿色版

**Comment by Laifang** [comment]
安装版1.0.4 也报了

**Comment by tiny-craft** [comment]
可以试下1.0.5版本，我之前也遇到过，用github action打包出来的exe有时会莫名其妙报毒...

**Comment by tiny-craft** [comment]
这个issue先关闭了，后面有机会我也会申请个正规的Windows的证书来签名打包。或者上架Windows Store之类的App商城
