### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by devswork** [tiny-craft/tiny-rdm#49]
版本：1.0.4
操作系统：Windows 11

当 key 名称为 "\x00\x01" 这种命名的键，在数据库中会显示为方块，并且点击后会有 key 不存在的错误。

![Snipaste_2023-10-09_18-15-16](https://github.com/tiny-craft/tiny-rdm/assets/18701798/032aca37-c217-425c-ac70-05bfcaf0de5f)

使用 RDM（RESP） 不会出现此问题，会正常显示 \x00 \x01 ....

**Comment by devswork** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/18701798/017c338b-2932-4a84-8334-7f0bbb24b294)

**Comment by tiny-craft** [comment]
@devswork 1.0.5版本已经修复这个问题，可以再看看~
