### ISSUE TITLE
【改进】值（value）的类型判断不准确

### ISSUE THREAD

**Issue by MoeMoeFish** [tiny-craft/tiny-rdm#50]
版本: 1.0.4
windows 11

我这边很多字符串（plain text）类型都判断为 hex 类型，显示不方便。比如下面的两个图中的示例。
很多文字都有这个问题。
感觉有中文的字符串比较容易误判，但是没有仔细测试

![图片](https://github.com/tiny-craft/tiny-rdm/assets/7419357/56c5cdee-6b25-4dc9-a3a8-78ae25bdc078)

![图片](https://github.com/tiny-craft/tiny-rdm/assets/7419357/90cd7f21-07c4-4bdb-805e-f62509b59af4)

**Comment by tiny-craft** [comment]
1.0.5版本已经修复这个问题，可以再看看~
