### ISSUE TITLE
【bug】以JSON方式查看，较大数值显示错误

### ISSUE THREAD

**Issue by buxiua** [tiny-craft/tiny-rdm#52]
版本: 1.0.4
windows 11

使用原始文本显示，数值正常显示
![image](https://github.com/tiny-craft/tiny-rdm/assets/50450965/e1198133-2679-4bc7-b5bb-6a11e38bd7cb)

当使用JSON方式查看的时候，数值精度缺失，这应该与js不能精确存储**较大数**有关。
![image](https://github.com/tiny-craft/tiny-rdm/assets/50450965/716fa60e-86b5-4a93-a6e4-d04c55ac945a)

**Comment by tiny-craft** [comment]
@buxiua 1.0.5版本已经修复这个问题，可以再看看~
