### ISSUE TITLE
连接名称不能包含中文

### ISSUE THREAD

**Issue by TankCool** [tiny-craft/tiny-rdm#56]
![image](https://github.com/tiny-craft/tiny-rdm/assets/5235399/8b06e372-1ce7-4691-8486-c1090750134a)

**Comment by tiny-craft** [comment]
可以保存和更新，点测试的时候有问题，已重现。晚点修

**Comment by tiny-craft** [comment]
紧急修复了这个问题，可以下载1.0.7版本
