### ISSUE TITLE
希望增加Mac Intel版系统安装包

### ISSUE THREAD

**Issue by 110sec** [tiny-craft/tiny-rdm#57]
大佬在打包一个Mac Intel处理器的安装包

**Comment by tiny-craft** [comment]
[TinyRDM_1.0.6_mac_amd64.dmg](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.6/TinyRDM_1.0.6_mac_amd64.dmg)
[TinyRDM_1.0.6_mac_amd64.zip](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.6/TinyRDM_1.0.6_mac_amd64.zip)
这两个都是Intel处理器的安装包哦，每个版本的release页面都有
---
看来要改下名称了，发现你们容易看错amd64和arm64。。。

**Comment by tiny-craft** [comment]
> [TinyRDM_1.0.6_mac_amd64.dmg](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.6/TinyRDM_1.0.6_mac_amd64.dmg) [TinyRDM_1.0.6_mac_amd64.zip](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.6/TinyRDM_1.0.6_mac_amd64.zip) 这两个都是Intel处理器的安装包哦，每个版本的release页面都有
> 
> 看来要改下名称了，发现你们容易看错amd64和arm64。。。

[TinyRDM_1.0.7_mac_amd64.dmg](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.7/TinyRDM_1.0.7_mac_amd64.dmg)
[TinyRDM_1.0.7_mac_amd64.zip](https://github.com/tiny-craft/tiny-rdm/releases/download/v1.0.7/TinyRDM_1.0.7_mac_amd64.zip)
紧急修复了一个问题，用1.0.7版本的吧
