### ISSUE TITLE
子key列表也加入过滤项

### ISSUE THREAD

**Issue by RuoBingCoder** [tiny-craft/tiny-rdm#58]
希望在子key列表也加入过滤项

**Comment by tiny-craft** [comment]
这个是不是和复合表达式差不多。后续会考虑加入多条件筛选功能

**Comment by tiny-craft** [comment]
[v1.1.2](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.2)key列表支持匹配查询后，再进行二次筛选。操作步骤：

1. 输入需要匹配的glob，并回车或者按搜索
2. 在匹配结果中，再次输入二级查询字符即可直接筛选当前结果
