### ISSUE TITLE
拆分压缩算法和查看方式

### ISSUE THREAD

**Issue by Songzhizong** [tiny-craft/tiny-rdm#60]
<img width="543" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/22743270/dcd84118-e1a8-4efb-b726-9b0e1fc87636">

目前压缩算法和查看方式显示在同一个下拉框下，这两者应该是独立的功能，最好能拆分成两个下拉框。

此外能否自动识别压缩算法并解压缩，就像RDM那样。

<img width="667" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/22743270/f5388249-c3e8-4976-92a7-836fe538cda9">

**Comment by tiny-craft** [comment]
这个也是我规划后续版本的功能，解码方式和查看方式拆分。解码方式应该会在连接高级设置里面可选默认解码

**Comment by Songzhizong** [comment]
> 这个也是我规划后续版本的功能，解码方式和查看方式拆分。解码方式应该会在连接高级设置里面可选默认解码

在连接设置里设置默认解码应该不是好的方案，实际使用可能会用到多种压缩算法。

压缩后的字节数组头部应该携带了压缩算法的表示，是否可以通过识别此标识来确认压缩算法？

**Comment by tiny-craft** [comment]
解码方式不一定是压缩算法，可能是自定义的加密方式之类的，因为还会加入用户自定义解码/编码。所以连接设置会提供“自动识别”和其他所有解码方式。默认是自动，自动会尝试用所有可用的解码方式。

而且除了设置连接，每个值详情内也能手动再切换查看方式和解码方式。这样我觉得已经足够大部分情况使用了

**Comment by tiny-craft** [comment]
1.0.8版本已经拆分查看格式和解压/解码方式
