### ISSUE TITLE
The window has no shadow and is difficult to distinguish from the rear window

### ISSUE THREAD

**Issue by akschy** [tiny-craft/tiny-rdm#62]
I wish you could add a form shadow and that the shadow could have different styles depending on focus and out of focus

**Comment by tiny-craft** [comment]
Which OS you launch? Can you provide any relevant screenshots? I had added outer border to the window in version 1.0.2.
Wails have less permissions to control native window.

**Comment by tiny-craft** [comment]
The new version 1.0.8 already added window shadow on macOS
