### ISSUE TITLE
v1.0.7 版本在 macbook m1 芯片上安装失败 

### ISSUE THREAD

**Issue by okkoye** [tiny-craft/tiny-rdm#63]
软件版本：tiny-rdm v1.0.7
错误提示：
<img width="375" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/48524298/3ef25e36-8503-402d-99cb-98f03420d3e5">

> 目前安装 v1.0.5 版本可以使用

**Comment by tiny-craft** [comment]
zip压缩包的也一样吗？还有1.0.6的也可以试下
可以尝试命令行再执行下下面的命令
```shell
 sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
```

**Comment by tiny-craft** [comment]
@okkoye 安装还有没有问题？这个issue我先关闭了，最新发的1.0.8也可以试下，有问题再发issue吧

**Comment by okkoye** [comment]
> zip压缩包的也一样吗？还有1.0.6的也可以试下 可以尝试命令行再执行下下面的命令
> 
> ```shell
>  sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
> ```

今天从 1.0.6 升级到 1.0.9 后，运行提示已损坏，通过 ` sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app` 命令可正常运行。
