### ISSUE TITLE
【功能】：希望大佬能对于hash结构的子 value 加入多种解析数据结构功能 比如“{"\name\":\"hello\"}” 能解析为标准的json格式

### ISSUE THREAD

**Issue by RuoBingCoder** [tiny-craft/tiny-rdm#65]
![image](https://github.com/tiny-craft/tiny-rdm/assets/29751035/3332425e-9219-40a0-98f7-b7e3bbe3429c)

**Comment by tiny-craft** [comment]
在未来的版本规划，1.0.8版本又重构拆分了解析逻辑，等自动解析再完善点，会把其他各个类型的值解析补上

**Comment by tiny-craft** [comment]
[v1.1.0](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.0)版本已经支持复杂结构选格式查看和编辑
