### ISSUE TITLE
[FEATURE]展示Keys时支持设置分隔符

### ISSUE THREAD

**Issue by ZhaoQi99** [tiny-craft/tiny-rdm#66]
* 能否像[RedisInsight 2.0](https://redis.com/redis-enterprise/redis-insight/)一样展示Keys的时候支持设置分隔符
* 能支持设置多个分隔符就更好了！！
![image](https://github.com/tiny-craft/tiny-rdm/assets/25344334/560e7f6c-087f-477a-829f-216ba0463a58)

**Comment by tiny-craft** [comment]
<img width="630" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/9c44507c-cefe-4b31-b933-c8b180186d26">
每个连接设置里面的高级配置标签页有

**Comment by ZhaoQi99** [comment]
> <img alt="image" width="630" src="https://user-images.githubusercontent.com/137850705/280238068-9c44507c-cefe-4b31-b933-c8b180186d26.png">
> 每个连接设置里面的高级配置标签页有

感谢🙏, 找到啦

**Comment by ZhaoQi99** [comment]
计划支持设置多个分隔符吗？(不知道这个需求是不是很常见😂...我的Key格式是XXX:1:A.B.C...)

**Comment by ZhaoQi99** [comment]
还有一个问题: 不用DB使用用的分隔符有可能不一样....可能存在频繁切换分隔符的场景.....(现在切换分隔符的话，需要切换到 服务器+ 断开连接+编辑连接配置)

**Comment by tiny-craft** [comment]
这个，貌似先有的所有同类产品都没有支持多个分隔符的吧？这会导致一眼看不出key值，比如A:B.C和A:B:C都在同层级同名了
第二个问题，频繁切换分隔符是会导致树形列表的所有key都要重新刷新重组的，如果不断开直接切换，可能key很多的情况下客户端会假死。而且貌似也没有太多频繁切换的需求吧，同一个库不应该有多重分隔符。如果是不同的库，可以复制连接，只保留那个库就行了
