### ISSUE TITLE
[FEATURE] SSL add SNI support 

### ISSUE THREAD

**Issue by lost22git** [tiny-craft/tiny-rdm#67]

**Comment by tiny-craft** [comment]
<img width="624" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/a004853d-671d-4693-9ecb-84b19f5492ca">

Would adding an input field for entering the server name here meet your requirements?

**Comment by tiny-craft** [comment]
![image](https://github.com/tiny-craft/tiny-rdm/assets/137850705/52d95f17-9dda-45f0-9f01-408932b4f82b)
[v1.1.4](https://github.com/tiny-craft/tiny-rdm/releases) already support SNI.
