### ISSUE TITLE
[BUG] 安装之后打不开界面

### ISSUE THREAD

**Issue by cqbaixin** [tiny-craft/tiny-rdm#68]
**Tiny RDM Version**
What version of Tiny RDM are you using?
tiny-rdm_1.0.9_linux_amd64.deb

**OS Version**
Linux act 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

![image](https://github.com/tiny-craft/tiny-rdm/assets/42137335/442a7a64-8426-4fc3-98c6-e8079374d14c)

**Comment by tiny-craft** [comment]
看起来大概是开启了全透明之后webview 不支持。有没有尝试更新系统的webview依赖？

**Comment by cqbaixin** [comment]
webview 版本信息
gambas3-gb-gtk3-webview/jammy 3.16.3-3 amd64
gambas3-gb-qt5-webview/jammy 3.16.3-3 amd64
libqt5webview5-dev/jammy 5.15.3-1build1 amd64
libqt5webview5/jammy 5.15.3-1build1 amd64
libqt6webview6/jammy 6.2.4-2 amd64
libqt6webviewquick6/jammy 6.2.4-2 amd64
libwxgtk-webview3.0-gtk3-0v5/jammy 3.0.5.1+dfsg-4 amd64
libwxgtk-webview3.0-gtk3-0v5/jammy 3.0.5.1+dfsg-4 i386
libwxgtk-webview3.0-gtk3-dev/jammy 3.0.5.1+dfsg-4 amd64
libwxgtk-webview3.0-gtk3-dev/jammy 3.0.5.1+dfsg-4 i386
orthanc-webviewer/jammy 2.8-1 amd64
python3-webview/jammy,jammy 3.3.5+dfsg-1 all
python3-wxgtk-webview4.0/jammy 4.0.7+dfsg-13build1 amd64
qml-module-qtwebview/jammy 5.15.3-1build1 amd64
qml6-module-qtwebview/jammy 6.2.4-2 amd64
qt6-webview-dev/jammy 6.2.4-2 amd64
qt6-webview-plugins/jammy 6.2.4-2 amd64
qtwebview5-doc-html/jammy,jammy 5.15.3-1build1 all
qtwebview5-doc/jammy,jammy 5.15.3-1build1 all
qtwebview5-examples/jammy 5.15.3-1build1 amd64

**Comment by tiny-craft** [comment]
这个我晚点虚拟机装个一样版本的ubuntu试下看有没救。
或者有没有这个系统的镜像下载地址，直接发我更省事。

**Comment by cqbaixin** [comment]
版本在1.0.9之后就可以了
