### ISSUE TITLE
[BUG] 批量删除不生效（命令没判断redis版本号）

### ISSUE THREAD

**Issue by ydq** [tiny-craft/tiny-rdm#69]
**Tiny RDM Version**
V1.0.9

**OS Version**
MacOS 14.1 (23B74)

**Redis Version**
3.2.12

**Describe the bug**
测试批量删除  -  **不等待操作结果** 使用的是  unlink 命令来操作的， unlink 命令[官方文档](https://redis.io/commands/unlink/)显示是在 redis 4.0.0 以上版本才开始支持，而我们的某个环境的 redis 版本为 3.x，不支持 unlink 所以导致批量删除失败（查看日志才发现这个问题，最后使用 **等待操作结果** 内部切换为了 del 命令才操作成功），而且批量删除使用 **不等待操作结果** UI上面默认为删除成功了，直接在整个 tree 上删除掉了数据，给开发会造成删除成功的错误心智。所以如果替代命令的情况下，高版本的命令在使用之前内部是否可以判断一下版本号，判断用户当前的版本不支持的时候内部降级到低版本命令去执行，或者判断某个功能不支持的情况下，UI上面就直接禁止选择这样的（比如获取到用户的版本号低于4.0的时候  **不等待操作结果** 操作是禁用的）。

另外 在 tree 模式下，不支持在某个路径上直接刷新该路径下的数据（可以直接根据前缀去scan），当前只能整个进行刷新

**Comment by tiny-craft** [comment]
第一个问题，我到时把不支持的给个报错，或者失败后尝试改为使用 del 命令
第二个问题，因为 1.0.8 加入部分加载，所以没有全量加载清况下单独刷新指定层级是会搞乱 cursor 的，而且某个层级下有大量kye 的时候，是单独加入批量加载还是全量加载呢？这个问题比较纠结，不过确实有这方面需求，我会考虑在数据库全量加载完成后，启用指定层级刷新的按钮

**Comment by tiny-craft** [comment]
v1.1.0已经改为unlink命令失效，就会使用del命令代替
同时也把指定路径刷新加回来了，需要全部key加载完成才能使用
