### ISSUE TITLE
[FEATURE] 【数据加载】

### ISSUE THREAD

**Issue by RuoBingCoder** [tiny-craft/tiny-rdm#70]
1、对于key比较多的，例如hash key 有几千或者上万的，点击左边目录，会一直卡住，希望右边数据能懒加载，避免一次性加载完。

**Comment by tiny-craft** [comment]
这个功能刚好是下一个版本的内容，正在开发中

**Comment by tiny-craft** [comment]
v1.1.0 已经支持各个类型分批加载
