### ISSUE TITLE
[FEATURE] 命令行操作的时候能加个复制粘贴

### ISSUE THREAD

**Issue by Jian0326** [tiny-craft/tiny-rdm#73]
命令行操作的时候能加个复制粘贴

**Comment by Jian0326** [comment]
命令行操作的时候能加个复制粘贴

**Comment by tiny-craft** [comment]
现在用CTRL+C/V应该是可以的

**Comment by fulinkapp** [comment]
> 现在用CTRL+C/V应该是可以的

1.0.9 貌似不支持哦。

**Comment by tiny-craft** [comment]
> 1.0.9 貌似不支持哦。

是哪个系统的？我在mac下是可以的

**Comment by fulinkapp** [comment]
> > 1.0.9 貌似不支持哦。
> 
> 是哪个系统的？我在mac下是可以的

win10

**Comment by tiny-craft** [comment]
现在把浏览器默认菜单显示出来了，邮件会弹出有复制的菜单。不过有个问题就是鼠标可能要右键双击才会出菜单，不确定是不是term.js拦截了一次事件还是别的原因
