### ISSUE TITLE
[BUG]windows下1.0.9-进行哨兵连接时，测试连接成功，创建后无法打开连接

### ISSUE THREAD

**Issue by Chivenh** [tiny-craft/tiny-rdm#75]
**Tiny RDM Version**
1.0.9

**OS Version**
Windows

**Describe the bug**
哨兵连接时，编辑窗口可以测试通过，也可以自行发现哨兵名称，创建后从列表双击打开，提示
![image](https://github.com/tiny-craft/tiny-rdm/assets/28721089/feffbb9f-d6fb-40cf-8342-01e9bb2aed12)

大佬，貌似哨兵的连接创建不太对.

**Comment by tiny-craft** [comment]
可以了吗，应该是你连的哨兵节点所监控的主节点，没有select指令权限，或者连读取数据的权限都没有之类的

**Comment by Chivenh** [comment]
同样的连接，代理开启的时候就会报这个错，我也是后面发现，😂感觉大佬你可以优化下。(QuickRedis同样的情况下没这个问题)



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月15日 10:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [tiny-craft/tiny-rdm] [BUG]windows下1.0.9-进行哨兵连接时，测试连接成功，创建后无法打开连接 (Issue #75) |

可以了吗，应该是你连的哨兵节点所监控的主节点，没有select指令权限，或者连读取数据的权限都没有之类的

**Comment by tiny-craft** [comment]
> 同样的连接，代理开启的时候就会报这个错，我也是后面发现，😂感觉大佬你可以优化下。(QuickRedis同样的情况下没这个问题)
@Chivenh 你那哨兵节点上返回的mater地址是需要通过ssh访问的，还是不需要ssh也能访问？
