### ISSUE TITLE
[BUG]部分键不显示

### ISSUE THREAD

**Issue by amsterdan5** [tiny-craft/tiny-rdm#76]
**Tiny RDM Version**
1.0.9

**OS Version**
mac m1

**Describe the bug**
创建hash键名为：delivery:1、delivery:2 依次类推
结果：只显示 delivery:6 一条记录

**Comment by tiny-craft** [comment]
有勾选了立即刷新吗

**Comment by amsterdan5** [comment]
加载剩余键有显示了，以为一开始就全部加载，感谢

**Comment by tiny-craft** [comment]
如果没有勾选添加后立即刷新，确实有些问题。不过这部分的逻辑刚好这个版本在重构，我到时再优化下

**Comment by amsterdan5** [comment]
批量删除key的时候，能否做个提示，刚好要删除1W+的数据，任务异步执行，有点慢，没有提示，以为没操作成功，或者任务提交后提示一下并关闭窗口

**Comment by tiny-craft** [comment]
> 批量删除key的时候，能否做个提示，刚好要删除1W+的数据，任务异步执行，有点慢，没有提示，以为没操作成功，或者任务提交后提示一下并关闭窗口
异步执行操作的状态提示，这个可以有
