### ISSUE TITLE
[BUG]Can not connect to redis server if server banned command 'client' for security reasons

### ISSUE THREAD

**Issue by uleelx** [tiny-craft/tiny-rdm#78]
**Tiny RDM Version**
v1.0.9

**OS Version**
Windows 10

**Redis Version**
5.0.7

**Describe the bug**
Can not connect to redis server if server banned command 'client', it alerts error "ERR unknown command `client`, with args beginning with: `setname` `XXXXXXXX`"

**Comment by tiny-craft** [comment]
v1.1.0 already fix this issue.
