### ISSUE TITLE
[BUG] SSH隧道测试链接第一次失败之后第二次点击直接显示成功连接到redis服务器

### ISSUE THREAD

**Issue by lscho** [tiny-craft/tiny-rdm#79]
**Tiny RDM Version**

v1.0.9

**OS Version**

Mac

**Describe the bug**

 SSH隧道测试链接第一次失败之后第二次点击直接显示成功连接到redis服务器

Steps to Reproduce:

1.SH隧道，点击测试链接，等待超时
2.再次点击直接显示成功连接到redis服务器

<img width="689" alt="QQ20231119-215118@2x" src="https://github.com/tiny-craft/tiny-rdm/assets/11583677/6bfce837-142d-4070-89e2-cdebf432e6d8">

**Comment by tiny-craft** [comment]
每次都这样吗，还是第一次确实网络不好超时了

**Comment by lscho** [comment]
我的意思是这个ssh隧道确实是链接不了的。

但是第二次点击测试链接的时候，却显示了成功链接的消息，等测试链接的loading效果结束，才隐藏

**Comment by tiny-craft** [comment]
v1.1.0已经修复测试状态显示不太对的问题
