### ISSUE TITLE
[BUG] 命令行换行符号显示不正常

### ISSUE THREAD

**Issue by ctfang** [tiny-craft/tiny-rdm#80]
例如执行 CLIENT LIST 命令时，输出结果没有排版；

复制结果粘贴到编辑器正常显示，预计是 UI 界面显示换行符号出现了问题。

**Comment by tiny-craft** [comment]
[v1.1.0](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.0)已经修复输出内容可能没换行的问题
