### ISSUE TITLE
[BUG] connect sentinel node error

### ISSUE THREAD

**Issue by stardustman** [tiny-craft/tiny-rdm#82]
**Tiny RDM Version**
What version of Tiny RDM are you using?
1.0.9
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Mac
**Redis Version**
Which version of Redis are you using?
6.2.13
**Describe the bug**
1. with this sentinel config, test connection is ok.
<img width="603" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/22998204/a56e3bba-f895-404c-a8cc-997c266b9fe3">

2. but when I connect the sentinel node from sidebar, error report:
<img width="1365" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/22998204/422d35f9-20c3-4ae7-aae8-1ec6ad0c1a30">

Steps to Reproduce:

1. set up a master-replica  sentinel cluster has 1 master, 2 replica, 3 sentinels
3. choose one sentinel to connect. the error reports.

**Comment by tiny-craft** [comment]
@stardustman did you disable the "SELECT" command?

**Comment by stardustman** [comment]
> @stardustman did you disable the "SELECT" command?

no, all master and the replicas can select db correctly.

**Comment by tiny-craft** [comment]
192.168.50.248

> > @stardustman did you disable the "SELECT" command?
> 
> no, master and the replicas can select db correctly. here are my scripts for setting up redis master-replica with sentinels. [redis/6.2.13/sentinel scritps](https://github.com/stardustman/scripts/tree/main/redis/6.2.13/sentinel) may it can help you set up quickly.

I use this script to setup redis master-replica environment, but Tiny RDM successful connected without any error reported.
Here is my connection config:

<img width="624" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/a1baa4e3-3b46-4da7-ad64-cb003b0b8d93">
<img width="627" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/6ebe1bf3-6a12-45d8-aada-93960c75e3e9">

Are there any configuration settings different from yours?

**Comment by stardustman** [comment]
I didn't select "Serve as Sentinel Node". 
but after I select the "Serve as Sentinel Node", click "Test Connection" failed. here is the gif link show the problem.
![problem](https://github.com/tiny-craft/tiny-rdm/assets/22998204/0e3c6103-5934-4b4e-b79f-ef0fe3cc9fc8)

**Comment by tiny-craft** [comment]
It seems like your local machine is unable to access 127.0.0.1:6382.
Can the master node be accessed locally through 127.0.0.1:6382? Have you attempted to successfully log in using the command line?

**Comment by stardustman** [comment]
> It seems like your local machine is unable to access 127.0.0.1:6382. Can the master node be accessed locally through 127.0.0.1:6382? Have you attempted to successfully log in using the command line?

I deploy the redis service not on my local machine. it was deployed on 192.168.6.40. with 1 master,2 replicas, 3 sentinel.

**Comment by stardustman** [comment]
I start the redis service on my local machine. this time connect sucess.

**Comment by tiny-craft** [comment]
If you deploy the redis server on 192.168.6.40, you should add below lines to [redis-6380.conf.bak](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/redis-6380.conf.bak)
`
bind 192.168.6.40
protected-mode no
`
and add change line in both [sentinel-26380.conf.bak](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/sentinel-26380.conf.bak),  [sentinel-26380.conf.bak](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/sentinel-26381.conf.bak),  [sentinel-26380.conf.bak](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/sentinel-26381.conf.bak)
`
sentinel monitor mymaster 192.168.50.248 6380 2
`

Finally, change the startup script [start-redis-sentinel.sh](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/start-redis-sentinel.sh)
`
redis-cli -p 6381 slaveof 192.168.50.248 6380
redis-cli -p 6382 slaveof 192.168.50.248 6380
`

You need to expose the accessible address of the master node for the client to access.

**Comment by stardustman** [comment]
> [redis-6380.conf.bak](https://github.com/stardustman/scripts/blob/main/redis/6.2.13/sentinel/redis-6380.conf.bak)

it works. thanks!
