### ISSUE TITLE
[FEATURE] 应修改 窗口最大化为不保存状态 或 添加初始窗口为最大化

### ISSUE THREAD

**Issue by qing-shang** [tiny-craft/tiny-rdm#84]
https://github.com/tiny-craft/tiny-rdm/blob/71978c325b6d6eca66410a63580368dd097a7c82/backend/services/system_service.go#L74

这行上面添加
`if runtime.WindowIsMaximised(s.ctx) {
	continue
}`
取消对窗口最大化的保存不然 初始窗口为最大化 但是按钮为最大化

**Comment by tiny-craft** [comment]
可以，不过不是这里。这里逻辑在最大化的时候，还有别的操作，比如取消圆角，mac上标题靠左等

**Comment by qing-shang** [comment]
> 可以，不过不是这里。这里逻辑在最大化的时候，还有别的操作，比如取消圆角，mac上标题靠左等

是的，应该修改后面`if !fullscreen && !minimised && !maximised {` 添加`!maximised`

**Comment by tiny-craft** [comment]
参考其他Windows上的软件后，目前的方案是保存窗口最大化状态，再次启动的时候会根据状态切换到最大化还是普通尺寸，并且保留最大化前的窗口尺寸，方便启动是最大化状态时可以还原
