### ISSUE TITLE
删除键操作提示错误

### ISSUE THREAD

**Issue by seffeng** [tiny-craft/tiny-rdm#86]
**Tiny RDM Version**
1.1.0

**OS Version**
Windows 10

**Redis Version**
7.0.12

**Describe the bug**
删除键操作提示错误。
![image](https://github.com/tiny-craft/tiny-rdm/assets/3509779/432c279e-ff9d-4385-930e-010ef75f8489)

**Comment by seffeng** [comment]
修改标题

**Comment by tiny-craft** [comment]
[v1.1.2](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.2)已经修复这个问题，欢迎使用
