### ISSUE TITLE
[BUG] M1 MAC安装完成后打不开，“Tiny RDM”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by TianKongXiaSha** [tiny-craft/tiny-rdm#88]
**Tiny RDM Version**
1.1.0

**OS Version**
mac

**Redis Version**
3.2.12

**Describe the bug**
M1 MAC安装完成后打不开，“Tiny RDM”已损坏，无法打开。 你应该将它移到废纸篓。

**Comment by tiny-craft** [comment]
@TianKongXiaSha 在终端执行下面命令就可以了
```shell
 sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
```

**Comment by TianKongXiaSha** [comment]
> @TianKongXiaSha 在终端执行下面命令就可以了
> 
> ```shell
>  sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
> ```

可以了，感谢

**Comment by tiny-craft** [comment]
> intel 芯片的 mac 也是用一样的命令处理吗？
> 
> 

是的，intel只要第一次安装运行需要，arm每次替换新版本后运行都需要
