### ISSUE TITLE
[FEATURE]希望能增加一个数据类型的选项

### ISSUE THREAD

**Issue by Newink-Stars** [tiny-craft/tiny-rdm#89]
![Snipaste_2023-11-29_17-58-41](https://github.com/tiny-craft/tiny-rdm/assets/64735245/c8fbce2c-fc74-46e1-a622-b8aa0cc308dd)

**Comment by tiny-craft** [comment]
右下角就有哦，解码方式和查看方式，可以手动切换

**Comment by tiny-craft** [comment]
@Newink-Stars 
<img width="585" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/ad22801a-30a0-4f10-b9c7-1225c4e2c5c1">

右下角是可以选择切换的，而且如果是json文件会自动切换到json视图
