### ISSUE TITLE
[FEATURE] 建议Key筛选，直接在列表用输入框

### ISSUE THREAD

**Issue by shockerli** [tiny-craft/tiny-rdm#91]
- 现状：每次要点筛选按钮，再输入，再确认。过于繁琐，筛选Key是个高频操作
- 建议：直接在输入框中就筛选了，能快捷很多

谢谢~❤️

**Comment by tiny-craft** [comment]
<img width="335" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/137850705/3cefccd0-7492-497f-8c8a-9425916a58a8">

这个功能这几天正好在做，敬请期待下个版本
