### ISSUE TITLE
[zset value 和 score] 显示的一样

### ISSUE THREAD

**Issue by iszhangsc** [tiny-craft/tiny-rdm#92]
**Tiny RDM Version**
1.1.0

**OS Version**
Mac M1

**Redis Version**
5.0.4

**Describe the bug**

1.添加一个redis zset 类型的key,添加多个元素后，zset的成员 值和分值变成一样了
<img width="742" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/41824454/38113746-bbdc-45e1-a485-765d2bb1f857">
2.从命令行中获取的则是，第一步中的数据展示有误，你把value当成score进行展示了
<img width="399" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/41824454/c3340e0e-11a7-436d-86cd-7de65a7fb261">

**Comment by tiny-craft** [comment]
ab8077999d08dd6dc4590ab20481e081b80ddab0 这个提交已经修复此问题，新版本未来几天会发布~

**Comment by tiny-craft** [comment]
[v1.1.2](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.2)已经修复这个问题
