### ISSUE TITLE
[BUG] mac安装报错 “Tiny RDM”已损坏，无法打开。 你应该推出磁盘映像。

### ISSUE THREAD

**Issue by xwlops** [tiny-craft/tiny-rdm#93]
MAC Apple M1 
MAC OS 14.0 (23A344)
<img width="656" alt="image" src="https://github.com/tiny-craft/tiny-rdm/assets/76082537/282adb35-3f19-4d97-bf8c-57cae4730817">

**Comment by jae-jae** [comment]
M1 遇到同样问题

**Comment by huangliu** [comment]
执行命令
```bash
sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
```

**Comment by xwlops** [comment]
> 执行命令
> 
> ```shell
> sudo xattr -d com.apple.quarantine /Applications/Tiny\ RDM.app
> ```

完美解决！
