### ISSUE TITLE
[FEATURE] 能不能edit 进去的json展示 美化一下

### ISSUE THREAD

**Issue by lycheezhou** [tiny-craft/tiny-rdm#94]
![截图_20231206164238](https://github.com/tiny-craft/tiny-rdm/assets/33309728/e6ff1eb2-2c77-4195-b18f-87fd80f379b2)

![截图_20231206164323](https://github.com/tiny-craft/tiny-rdm/assets/33309728/1dea07b8-3278-4863-b5f4-23d768b5a673)

**Comment by huangliu** [comment]
这什么版本，1.1.1是有美化的

**Comment by lycheezhou** [comment]
![截图_20231206175234](https://github.com/tiny-craft/tiny-rdm/assets/33309728/a1446267-bbc9-477e-8353-5d329f966a7e)
1.1.1 的

**Comment by lycheezhou** [comment]
1.1.0的
