### ISSUE TITLE
[BUG] 内容序列化后无法正常显示，并会造成左侧key隐藏的情况

### ISSUE THREAD

**Issue by xingcxb** [tiny-craft/tiny-rdm#96]
**Tiny RDM Version**
What version of Tiny RDM are you using?
v1.1.1
**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)
Mac
**Redis Version**
Which version of Redis are you using?
v6.0.0
**Describe the bug**
如果redis中某个key存储的是已经序列化的数据，当双击这个key的时候会提示load key summary fail:key not exists，并且当前这个key会在左侧列表中不见，实际数据还是在redis中
Steps to Reproduce:

1. 
2.

**Comment by tiny-craft** [comment]
@xingcxb 不确定是不是1.1.1有个加载key的类型而导致的bug，会出现这种情况，[1.1.2](https://github.com/tiny-craft/tiny-rdm/releases/tag/v1.1.2)修复了那个问题，可以试下还会不会出现这种情况
