### ISSUE TITLE
[FEATURE] 支持CTRL+S快捷键的方式完成保存

### ISSUE THREAD

**Issue by summer-boythink** [tiny-craft/tiny-rdm#97]
![Snipaste_2023-12-07_19-49-46](https://github.com/tiny-craft/tiny-rdm/assets/57977288/4f9091ab-2593-4bc1-8866-9203ff233c05)

**Comment by tiny-craft** [comment]
不错，这个刚好在我的todo list内

**Comment by tiny-craft** [comment]
[1.1.4](https://github.com/tiny-craft/tiny-rdm/releases)已经支持此功能
