### ISSUE TITLE
[BUG]Mac下输入框输入内容会自动首字母大写

### ISSUE THREAD

**Issue by iszhangsc** [tiny-craft/tiny-rdm#98]
**Tiny RDM Version**
1.1.2

**OS Version**
MacOS  M1 14

**Redis Version**
5.0.4

**Describe the bug**
1.在任意输入框中输入内容： ugc
2.会联想出： Ugh ，鼠标点击其他区域我的输入框内容就变成了Ugh了

**Comment by tiny-craft** [comment]
ac76131f189e0233f2a540bc7ba8391ea75be53f 这个提交修复了这个问题, comment里面定位错issue

**Comment by tiny-craft** [comment]
[最新版](https://github.com/tiny-craft/tiny-rdm/releases)优化了这个问题，可以下载最新版试下
